### ISSUE TITLE
Add Dockerfile for deploy this service 

### ISSUE THREAD

**Issue by batazor** [timlrx/tailwind-nextjs-starter-blog#1004]
**Is your feature request related to a problem? Please describe.**
It would be cool to have an example of a good Dockerfile to deploy this blog on your machine

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by timlrx** [comment]
You should refer to next.js site for how to [deploy on docker](https://nextjs.org/docs/app/building-your-application/deploying#docker-image). Don't feel a need to add it since it's pretty much the same.

**Comment by eshut** [comment]
@timlrx Then how to add this to compose? Missing dockerfile is a huge issue here, from my perspective

**Comment by timlrx** [comment]
@eshut, perhaps to be clearer, I should have recommended to follow the [official repo docker build instructions](https://github.com/vercel/next.js/tree/canary/examples/with-docker) instead. You can use the __same__ dockerfile and set:
```
// next.config.js
module.exports = {
  // ... rest of the configuration.
  output: "standalone",
};
```
as recommended in the `README.md`. This will support all the features and give a small and efficient build. I think this is better than maintaining a separate build. You can refer to the [docker compose repo](https://github.com/vercel/next.js/tree/canary/examples/with-docker-compose) if you are intending to use that instead.
