### ISSUE TITLE
in V2 Deploy use GitHub Pages visit feed.xml get 404

### ISSUE THREAD

**Issue by geekskai** [timlrx/tailwind-nextjs-starter-blog#1027]
1. use v2 version
2. use GitHub Pages deploy to  https://my-domains.com
3. open url: my-domains.com/feed.xml
4. See 404

**Expected behavior**
use Vercel deploy  is ok

**Comment by timlrx** [comment]
Sorry for the late fix but it was due to the difference in output directory for a static build. You can verify that it works over here - https://timlrx.github.io/tailwind-nextjs-starter-blog/feed.xml
