### ISSUE TITLE
Api and server action always returns static results

### ISSUE THREAD

**Issue by tidvn** [timlrx/tailwind-nextjs-starter-blog#1038]
**Describe the bug**
I want to build simple endpoints. However . Since the build completed, it seems like the api has been turned into a static page so every access returns the same result.

**Expected behavior**
i want the fix or config to work

**Screenshots**
![image](https://github.com/user-attachments/assets/4cc31137-2fb4-40d2-96b8-5c387a6d7fa3)

**Comment by timlrx** [comment]
Please see the Next.js docs for any framework specific questions or issues. It is explained over here: https://nextjs.org/docs/app/building-your-application/routing/route-handlers#caching

**Comment by tidvn** [comment]
<img width="1409" alt="Screenshot 2024-10-17 at 13 39 48" src="https://github.com/user-attachments/assets/c0480d5e-5e1e-4dd6-ab0d-36be44e9ffef">
i have problem with server action. The data in the component only calls the action once when building and becomes a static page
