### ISSUE TITLE
<TOCInline toc={props.toc} exclude="Introduction" /> adding random number at the last of link

### ISSUE THREAD

**Issue by jagdish-kumawat** [timlrx/tailwind-nextjs-starter-blog#1044]
I am using 
`<TOCInline toc={props.toc} exclude="Introduction" />`

For example, I have a heading as prerequisites - in the url, it is coming as #prerequisites-8. Basically for all the headings, it is appending a number at the last.

Also, all my headings are unique for a blog.

**Comment by rgvillanueva28** [comment]
Also experiencing this issue. All items on the table of content was appended with **-#**. The table of content is on the Post Layout, not on the mdx file.

On the table of content
![image](https://github.com/user-attachments/assets/ae603549-7e00-455f-b971-847a44372292)

On the post content
![image](https://github.com/user-attachments/assets/09f5264f-b181-412b-b697-4657aac2cefc)

**Comment by timlrx** [comment]
Able to reproduce the bug - it's due to `GithubSlugger` being initialiased globally so it wrongly keeps track of references across files.

**Comment by timlrx** [comment]
Published the fix in pliny@0.4.0
