### ISSUE TITLE
Segmentation fault in dev

### ISSUE THREAD

**Issue by PabloC** [timlrx/tailwind-nextjs-starter-blog#105]
Hi! 
I'am getting a Segmentation Fault error while in dev, after going to the about page. The about page has an image and I guess that's the problem.

```
event - compiled successfully
zsh: segmentation fault  npm run dev
```

I've read somewhere that this is related to next/image but cannot find the source.

This happens on an M1 without Rosetta2 installed.

Any idea?

**Comment by PabloC** [comment]
Related issue

https://github.com/vercel/next.js/issues/24564

**Comment by timlrx** [comment]
Users in the next.js issue you linked suggested downgrading to node 15. Does that work for you?

**Comment by PabloC** [comment]
I've downgraded to node 14.7.3 and now works. Tks!
