### ISSUE TITLE
404 page when in development

### ISSUE THREAD

**Issue by leevinikkila** [timlrx/tailwind-nextjs-starter-blog#106]
Hey, I like the blog template a lot, thanks. 

But I have an issue with getting the 404 "Sorry we couldn't find this page." when opening the homepage at http://localhost:3000/. It works fine after building and then starting it, but not in development mode. What could be causing this?

**Comment by rsipakov** [comment]
Try rename the index.xml to the eed.xml and remove a manual rewrite rule in the next.config.js (see more by this link https://github.com/timlrx/tailwind-nextjs-starter-blog/commit/5945a724913f7313c9b58ce6dfaa917901828b25#comments)

**Comment by timlrx** [comment]
Yup, @rsipakov is right. I might just make the change in the `v1` version so new users would not have this problem

**Comment by rsipakov** [comment]
> Yup, @rsipakov is right. I might just make the change in the `v1` version so new users would not have this problem

I think it will be useful.
