### ISSUE TITLE
ESLint migration needed ASAP

### ISSUE THREAD

**Issue by Alejogb1** [timlrx/tailwind-nextjs-starter-blog#1061]
I think it needs to migrate to the new ESLint configuration file *(typically configured in .eslintrc.js or .eslintrc.json files) to the new flat config format (typically configured in an eslint.config.js file).

[eslint docs](https://eslint.org/docs/latest/use/configure/migration-guide#ignoring-files)

**Comment by trillium** [comment]
Great opportunity for a PR!

**Comment by timlrx** [comment]
Yep, appreciate a PR on this! In the meantime, Next 15 should still support the older ESLint config file styles at least until the next major upgrade.
