### ISSUE TITLE
Remove husky as a requirement?

### ISSUE THREAD

**Issue by DoctorDerek** [timlrx/tailwind-nextjs-starter-blog#11]
Hey @timlrx ,
Do you think it's better to include instructions on using husky or to remove it as a dependency?

I went to commit locally after cloning the template, but I couldn't because husky not being configured threw an error.

That meant I had to pause what I was doing to `npm uninstall husky` -- then commit the package.json & package-lock.json files -- and then commit my actual changes.

I'm happy to update your template for whichever solution you think is best.

**Comment by timlrx** [comment]
Hi Derek, 

Husky is a pre-commit hook to ensure that new code committed runs through prettier and eslint. I guess you were having some eslint errors? If so, the solution is to fix it, then recommit. Or use `--no-verify` as an escape hatch. 

Would still prefer it to be there for the template, but I can understand users opting to remove them for their own repos. Let me know what problem you ran into and I will see whether I can replicate / fix it.

**Comment by DoctorDerek** [comment]
Hi Tim,
Bumping this. I don't get it?

![image](https://user-images.githubusercontent.com/761231/113788086-e3f24900-9701-11eb-8e93-8e5902f29f5f.png)

I mean, sure, I get it -- but isn't the appropriate place for this type of hook to be in some type of automation after the pull request? 

I'll submit a PR that will let me not have ESLint errors...
--> They're caused by not having a .gitattributes file when I'm a Windows developer, so every single file in the PR has a ESLint error on every line, see https://github.com/tailwindlabs/tailwindcss/pull/3760 

But fundamentally husky seems like an odd dependency, given that it forces someone to use the command line -- at least if they're a Windows developer like myself using GitHub Desktop. I'm one of those developers who thinks the GUI (GitHub Desktop) is a better choice and never commit from the command line except in case of emergency.

The error is related to "cygpath" not being found (because GitHub Desktop doesn't know what that means); the ESLint errors get auto-fixed by running husky:
![image](https://user-images.githubusercontent.com/761231/113788548-cbcef980-9702-11eb-99c0-fc4c9e32c2c4.png)

Anyway, I'll close the issue since you're keeping the dependency. No worries.

**Comment by DoctorDerek** [comment]
Just to follow up in case anybody stumbles on this in Google, GitHub Desktop will work with husky as configured, but only if you've already done npm install (so husky is in PATH locally).

There were previously various bugs (on both macOS and GitHub Desktop) with husky not working, but pre-commit hooks like @timlrx  has set up for https://github.com/timlrx/tailwind-nextjs-starter-blog/ will work fine:
`package.json`
```
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.+(js|jsx|ts|tsx)": [
      "eslint --fix"
    ],
    "*.+(js|jsx|ts|tsx|json|css|md|mdx)": [
      "prettier --write"
    ]
  }
```

Cheers!
