### ISSUE TITLE
Feature: Add support for Google Analytics

### ISSUE THREAD

**Issue by PabloC** [timlrx/tailwind-nextjs-starter-blog#117]
Is it possible to add the correct react component to include Google Analytics? It would be great if we can enable it only adding the ID in siteMetaDatajs.

I would try to add it and send a pull. If anyone is interested on this, could you vote? 

References:
https://thetombomb.com/posts/google-analytics-nextjs
https://stackoverflow.com/questions/45848142/how-to-set-up-google-analytics-through-google-tag-manager-for-next-js

**Comment by timlrx** [comment]
I have this added on [my site](https://github.com/timlrx/timlrx.com/blob/master/pages/_document.js#L44). If there are many others who wants it within the template, we can consider adding it in. If that's the case, I would prefer a better abstracted analytics component that could support other providers as well - similar to how the WIP comments feature is implemented.

**Comment by DoctorDerek** [comment]
FWIW using Google Analytics requires a Cookies Banner 🍪

**Comment by emptypockets-dev** [comment]
Would the set up be the same for the new "Google Analytics 4" version? https://support.google.com/analytics/answer/10089681

**Comment by timlrx** [comment]
yes it should work for GA 4 too since I am using gtag

**Comment by timlrx** [comment]
Added official support for google analytics, plausible and simple analytics in the latest template with `next/script`. Give it a try and let me know if there are issues!
