### ISSUE TITLE
Small Bug: Tags

### ISSUE THREAD

**Issue by osseonews** [timlrx/tailwind-nextjs-starter-blog#135]
Hi there,
There is a small bug in the code, in that it expects every MD post to have tags. Ocassionally, a post doesn't have a tag yet, or the tags array is empty. As the code has tags.map in several places, this throws an error. The fix that worked for us, was just to do: tags?.map in the code (adding the ?). Might be something you may want to fix in the core. Hope this helps.

**Comment by timlrx** [comment]
yup, as specified in the readme - `tags`  is required but can be an empty array
