### ISSUE TITLE
Changing /blog dir to /

### ISSUE THREAD

**Issue by iliamrv** [timlrx/tailwind-nextjs-starter-blog#136]
Hi there,

I'd like to move my current weblog to tailwind-nextjs-starter-blog preserving URL structure. The problem that I need [website]/[id] instead of [website]/blog/[id]. For example:

http://localhost:3000/guide-to-using-images-in-nextjs

As I am a newbie in Next.js, I don't know what should I change exactly in source code. Can you help me? Thanks.

**Comment by timlrx** [comment]
Hi, I would probably recommend redirecting your existing routes to the new ones. You can see an example of that [on my blog](https://github.com/timlrx/timlrx.com/blob/master/next.config.js).

**Comment by iliamrv** [comment]
thanks a lot for the solution!
