### ISSUE TITLE
Skipping a line in code does not show up after render

### ISSUE THREAD

**Issue by amalshaji** [timlrx/tailwind-nextjs-starter-blog#139]
For example, the following code block,

````
```js
export const MDXLayoutRenderer = ({ layout, mdxSource, ...rest }) => {
  const LayoutComponent = require(`../layouts/${layout}`).default
  
  return (
    <LayoutComponent {...rest}>
      <MDXRemote {...mdxSource} components={MDXComponents} />
    </LayoutComponent>
  )
}
```
````

renders by removing the new line

```js
export const MDXLayoutRenderer = ({ layout, mdxSource, ...rest }) => {
  const LayoutComponent = require(`../layouts/${layout}`).default
  return (
    <LayoutComponent {...rest}>
      <MDXRemote {...mdxSource} components={MDXComponents} />
    </LayoutComponent>
  )
}
```

**Comment by timlrx** [comment]
It does?
![image](https://user-images.githubusercontent.com/28362229/126523812-91373bf5-63ef-4823-b4fb-edf2ad7b13dd.png)

**Comment by timlrx** [comment]
I guess you are probably using one of the older versions. Try updating to new v1 setup which uses xdm instead of mdx (the results might differ)

**Comment by timlrx** [comment]
On further investigations, it is probably caused by my `rehype-prism-plus` plugin. Will try to fix it over the weekends.
