### ISSUE TITLE
Could not resolve "./PageTitle.js"

### ISSUE THREAD

**Issue by TatTran22** [timlrx/tailwind-nextjs-starter-blog#149]
This error happened when click **New features in v1** topic
The things I changed were just some parameters in siteMetadata.js the version of dependencies was preserved.

webpage
> Server Error
> Error: Build failed with 1 error:
> components/_mdx_bundler_entry_point.mdx:11:22: error: Could not resolve "./PageTitle.js"
> 
> This error happened while generating the page. Any console logs will be displayed in the terminal window.
> Call Stack
> failureErrorWithLog
> file:///Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js (1449:15)
> <unknown>
> file:///Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js (1131:28)
> runOnEndCallbacks
> file:///Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js (921:63)
> buildResponseToResult
> file:///Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js (1129:7)
> <unknown>
> file:///Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js (1236:14)
> <unknown>
> file:///Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js (609:9)
> handleIncomingPacket
> file:///Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js (706:9)
> Socket.readFromStdout
> file:///Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js (576:7)
> Socket.emit
> node:events (394:28)
> addChunk
> node:internal/streams/readable (312:12)

console
> components/_mdx_bundler_entry_point.mdx:11:22: error: Could not resolve "./PageTitle.js"
>     11 │ import PageTitle from './PageTitle.js';
>        ╵                       ~~~~~~~~~~~~~~~~
> 
> Error: Build failed with 1 error:
> components/_mdx_bundler_entry_point.mdx:11:22: error: Could not resolve "./PageTitle.js"
>     at failureErrorWithLog (/Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js:1449:15)
>     at /Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js:1131:28
>     at runOnEndCallbacks (/Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js:921:63)
>     at buildResponseToResult (/Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js:1129:7)
>     at /Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js:1236:14
>     at /Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js:609:9
>     at handleIncomingPacket (/Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js:706:9)
>     at Socket.readFromStdout (/Users/tattran22/Documents/tailwind-blog/node_modules/esbuild/lib/main.js:576:7)
>     at Socket.emit (node:events:394:28)
>     at addChunk (node:internal/streams/readable:312:12) {
>   errors: [
>     {
>       detail: undefined,
>       location: [Object],
>       notes: [],
>       pluginName: '',
>       text: 'Could not resolve "./PageTitle.js"'
>     }
>   ],
>   warnings: []
> }

**Comment by timlrx** [comment]
so what were the siteMetadata.js parameters that you changed? And there's no problem with a fresh cloned repo?

**Comment by TatTran22** [comment]
You can see what I have changed [here](https://github.com/TatTran22/tailwind-blog/commit/c5450c9dcef037abe1ddc6935ea5658c4e330361)

**Comment by TatTran22** [comment]
Yes. There are no problems with fresh clone

**Comment by timlrx** [comment]
Actually, there is a problem with a fresh clone, sorry about it. It's related to this issue: https://github.com/kentcdodds/mdx-bundler/issues/66

I have fixed it in the template by upgrading the dependencies. You can do the same in your repo by setting "mdx-bundler": "^5.1.2" and adding "esbuild": "^0.12.15" (it's now peer dependency).

**Comment by itxuye** [comment]
the same error in branch typescript .

**Comment by timlrx** [comment]
Fixed. The ts branch error was due to the example importing `PageTitle.js` but since it is ts, the example should have been `PageTitle.tsx` 😆
