### ISSUE TITLE
gif to video transcoding

### ISSUE THREAD

**Issue by shanewasley** [timlrx/tailwind-nextjs-starter-blog#152]
**Is your feature request related to a problem? Please describe.**
I am creating a personal site with a blog and projects and I need to include animations in addition to static images. I prefer to use compressed MP4 looping videos for displaying the animations because they are far smaller in file size than animated gifs.

**Describe the solution you'd like**
A built in transcoder to turn GIFs into to muted looping autoplaying MP4 videos.

**Describe alternatives you've considered**
Alternatively, my problem could be solved by just installing a video player component, such as [react-player](https://www.npmjs.com/package/react-player) or [next-videos](https://www.npmjs.com/package/next-videos). However I don't know how to install and use these components. I've tried and failed.

**Additional context**
This feature exists on this 11ty blog template: https://github.com/google/eleventy-high-performance-blog, more specifically: 
- https://github.com/google/eleventy-high-performance-blog/blob/main/_11ty/video-gif.js 
- https://github.com/google/eleventy-high-performance-blog/blob/main/_11ty/img-dim.js

**Comment by timlrx** [comment]
Thanks for the feature request. It should be technically feasible by extending the next image component and passing gifs through ffmpeg like the _11ty example link above. react-player and next-videos are different and won't work.

I won't prioritise it though as you can convert the gif to mp4 externally and just add the video. Will keep this issue open if anyone is interested in working on it.

**Comment by shanewasley** [comment]
Oh, I'm such a noob. I didn't realize I could just paste in the html <video> element directly into the MDX post. Yes, I will just convert the gifs externally and add the videos to the posts, as you suggested. Thanks!

**Comment by timlrx** [comment]
No worries! It's still a nice idea and enhancement if we can do it automatically.
