### ISSUE TITLE
Comment Box is not showing properly in Window 10 

### ISSUE THREAD

**Issue by ryadav96** [timlrx/tailwind-nextjs-starter-blog#154]
**To Reproduce**
1. Go to 'https://tailwind-nextjs-starter-blog.vercel.app/blog/nested-route/introducing-multi-part-posts-with-nested-routing' and scroll down to the comment section.
2. Click on 'Load comments.'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/30411972/127384995-ccd7ad26-00fc-4cfc-bfe1-0a0d228dede2.png)

**System Info
 - Window 10

**Browser Info (if display / formatting issue):**
- Device: Desktop
- Browser chrome
- Version: Version 91.0.4472.164 (Official Build) (64-bit)

**Comment by timlrx** [comment]
I get the same issue as well. @laymonage did you change any of the iframe styling and any advice what we should fix or whether it would be patched? Thanks

**Comment by laymonage** [comment]
Hey @timlrx, sorry about the issue. Yeah, I did change a configuration in giscus, but I found out there was a mistake in your template's config which causes this issue. I'm making a PR.

**Comment by laymonage** [comment]
PR: #155
