### ISSUE TITLE
Multilingual

### ISSUE THREAD

**Issue by vahidtakro** [timlrx/tailwind-nextjs-starter-blog#158]
Hello, how can I create multilingual content? different styles (rtl/ltr direction) for each language? and different locale for showing date format?

I have already added const nextTranslate = require('next-translate'), in my config, but still don't know how to translate mdx files, and let them change on locale, I know how to do it on Hugo, but about this, I don't know.

**Comment by vahidtakro** [comment]
and also, how can I change URLs for blog? for example I want to create different categories for my blog (example: personal/music/video) for now I found that I need to create a folder in data/blog, like "music" and put my mdx there, and the url of my post will be mysite.com/blog/music/newpost,

how can I remove "/blog" from the URL?
and how can I add categories, aliases, and series to the mdx file?

**Comment by timlrx** [comment]
Hi, it might be easier to go with an existing hugo template that supports all the features you require. Using this template and customizing it your needs will require some knowledge of nextjs and react.

Translate - you can take a look at https://github.com/timlrx/tailwind-nextjs-starter-blog/discussions/92, though to properly support rtl it would require additional work styling the components.

Routing - you can make a copy / rename the pages and data related to the blog component.

Categories - easiest way is to use tag as categories but if you want both tags and categories, you would have to create it yourself.

Aliases - use [redirects in next config](https://nextjs.org/docs/api-reference/next.config.js/redirects)

Series - use [nested routing](https://tailwind-nextjs-starter-blog.vercel.app/blog/nested-route/introducing-multi-part-posts-with-nested-routing)

**Comment by vahidtakro** [comment]
> Hi, it might be easier to go with an existing hugo template that supports all the features you require. Using this template and customizing it your needs will require some knowledge of nextjs and react.
> 
> Translate - you can take a look at #92, though to properly support rtl it would require additional work styling the components.
> 
> Routing - you can make a copy / rename the pages and data related to the blog component.
> 
> Categories - easiest way is to use tag as categories but if you want both tags and categories, you would have to create it yourself.
> 
> Aliases - use [redirects in next config](https://nextjs.org/docs/api-reference/next.config.js/redirects)
> 
> Series - use [nested routing](https://tailwind-nextjs-starter-blog.vercel.app/blog/nested-route/introducing-multi-part-posts-with-nested-routing)

Thanks, I could finally do the style direction for each language, for now I just don't know how to change siteMetadata.locale and language, based on user selected local.
and I don't know how to localize posts, if you give me a clue, I will try to make it. thanks.

**Comment by timlrx** [comment]
You would have to refer to the `next-translate` readme for how to change the locale and language.  To localize post, as suggested in my comments in the discussion you could 

> separate the markdown content in different language folders or change the parsing of the markdown slug to detect different file extensions like blog-post.en.md vs blog.post.ru.md

**Comment by vahidtakro** [comment]
> You would have to refer to the `next-translate` readme for how to change the locale and language. To localize post, as suggested in my comments in the discussion you could
> 
> > separate the markdown content in different language folders or change the parsing of the markdown slug to detect different file extensions like blog-post.en.md vs blog.post.ru.md

I was trying all yesterday and today, this is the changes I've done to mdx.js file, nothing changes.
```
 const {defaultlocale} = require('../i18n.json')
.
.
.
export async function getFileBySlug(type, slug, slug) {
 const filename = locale === defaultlocale ? 'index.md' : `index.${locale}.md`
 const filenameMdx = locale === defaultlocale ? 'index.mdx' : `index.${locale}.mdx`

  const mdxPath = path.join(root, 'data', type, `${slug}`, filenameMdx)
  const mdPath = path.join(root, 'data', type, `${slug}`, filename)
  const source = fs.existsSync(mdxPath)
    ? fs.readFileSync(mdxPath, 'utf8')
    : fs.readFileSync(mdPath, 'utf8')
```

**Comment by timlrx** [comment]
Please see #160 for a demo of the changes required to support i18n

**Comment by rsipakov** [comment]
@vahidtakro Rename "blog" to "post" for example. Removing a folder like "blog" from the URL bar that contains .md files makes no sense, in my opinion. Also, maybe use this way for some content files:

/pages/terms.js

```
import { MDXLayoutRenderer } from '@/components/MDXComponents'
import { getFileBySlug } from '@/lib/mdx'

const DEFAULT_LAYOUT = 'ContentSimple'

export async function getStaticProps() {
  const contentDetails = await getFileBySlug('content', ['terms'])
  return { props: { contentDetails } }
}

export default function Terms({ contentDetails }) {
  const { mdxSource, frontMatter } = contentDetails

  return (
    <MDXLayoutRenderer
      layout={frontMatter.layout || DEFAULT_LAYOUT}
      mdxSource={mdxSource}
      frontMatter={frontMatter}
    />
  )
}
```

/data/content/terms.md

```
---
title: Would you like to read our terms?
date: '2021-08-03'
draft: false
summary: Example of terms
---
```

/layouts/ContentSimple.js

```
import PageTitle from '@/components/PageTitle'
import SectionContainer from '@/components/SectionContainer'
import { BlogSeo } from '@/components/SEO'
import siteMetadata from '@/data/siteMetadata'
import formatDate from '@/lib/utils/formatDate'

export default function ContentSimple({ frontMatter, authorDetails, next, prev, children }) {
  const { date, title } = frontMatter
  return (
    <SectionContainer>
      <BlogSeo url={`${siteMetadata.siteUrl}/blog/${frontMatter.slug}`} {...frontMatter} />
      <article>
        <div>
          <header>
            <div className="pb-10 space-y-1 text-center border-b border-gray-200 dark:border-gray-700">
              <dl>
                <div>
                  <dt className="text-sm font-medium leading-6 text-gray-500 dark:text-gray-400">
                    updated on:
                  </dt>
                  <dd className="text-sm font-medium leading-6 text-gray-500 dark:text-gray-400">
                    <time dateTime={date}>{formatDate(date)}</time>
                  </dd>
                </div>
              </dl>
              <div>
                <PageTitle>{title}</PageTitle>
              </div>
            </div>
          </header>
          <div
            className="pb-8 divide-y divide-gray-200 xl:divide-y-0 dark:divide-gray-700 "
            style={{ gridTemplateRows: 'auto 1fr' }}
          >
            <div className="divide-y divide-gray-200 dark:divide-gray-700 xl:pb-0 xl:col-span-3 xl:row-span-2">
              <div className="pt-10 pb-8 prose prose-lg dark:prose-dark max-w-none">{children}</div>
            </div>
          </div>
        </div>
      </article>
    </SectionContainer>
  )
}
```
> how can I remove "/blog" from the URL?

**Comment by rsipakov** [comment]
@vahidtakro try it https://github.com/timlrx/tailwind-nextjs-starter-blog/discussions/92#discussioncomment-1137663

**Comment by GautierArcin** [comment]
I think we can close this issue ? 

(see #172 for references)

**Comment by GuillaumeAmat** [comment]
Hey @GautierArcin @timlrx :wave: 

Reading different things (eg: README, issues, PR) I'm not sure about the status of the i18n possible support in the future. Especially when you merged a demo branch some days ago.

I would like to start a new (localized) blog, and I'm not sure if I need to use the demo or the main project. Will the demo stay synced overtime and/or will the main project introduce the i18n support?

Thanks for your feedback :)

**Comment by timlrx** [comment]
Hi @GuillaumeAmat, it is better to use @GautierArcin's branch directly (https://github.com/GautierArcin/i18n-tailwind-nextjs-starter-blog/tree/demo/next-translate)

I might include some elements to make localization easier on my template, but his branch has it working out of the box. I believe he would try to maintain it over time, but you can always refer back to this repo to get the latest changes - the structure is mostly similar.

**Comment by GautierArcin** [comment]
Hello @GuillaumeAmat,

I believe @timlrx  already responded to your questions. He's right when he says that I'll try to update and maintain the branch in the future. My own blog is based on the template, so I still have to update the template to update the blog.
The update took a little of delay at the time of writing it because I have to admit I'm currently seeking / interviewing for new jobs in my private life.

The `demo` should come with localized French / English support as an example, which might interest you. Also, if you decided to use the i18n template and any bugs, I'll be happy to include it in the template. I'm still a very junior engineer ! :sweat_smile:

**Comment by GuillaumeAmat** [comment]
Thanks guys! 👌 I'll look deeper at the demo then.
