### ISSUE TITLE
TOC Table of Contents for Posts

### ISSUE THREAD

**Issue by shanewasley** [timlrx/tailwind-nextjs-starter-blog#161]
**Is your feature request related to a problem? Please describe.**
The only problem I'm trying to solve is giving the reader (of a post) the option to skim the text with a table of contents. I write longer posts (10-20k words) with many headers. I think a TOC would be compassionate and helpful for readers that want to skip ahead.

**Describe the solution you'd like**
A table of contents feature that could be activated in the post's front matter, like a boolean TOC=true/false. The TOC would be limited to displaying the H1, H2, and H3 headers of the post. 

**Describe alternatives you've considered**
Creating a TOC manually and pasting it in to the MDX post.

**Additional context**
I really like how the TOC feature is implemented in [hugo-haperMod](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/).

![hugo-paperMod_TOC_example](https://user-images.githubusercontent.com/7918039/128393044-39a75473-8c0f-43ff-ae06-ca652584b9d1.gif)

**Comment by timlrx** [comment]
I like the idea too! I might implement as a component so you can insert it anywhere in the post like `<TOC />` rather than in the frontmatter.

**Comment by timlrx** [comment]
Implemented it in the recent pull request to master. Check it out over here - https://tailwind-nextjs-starter-blog.vercel.app/blog/new-features-in-v1#table-of-contents-component

**Comment by ryadav96** [comment]
@timlrx  I think it will be better if keep TOC STICKY on the right side of the blog.
When we scroll down TOC will be always visible and reader can click and navigate to any part of the post.
Like-
![image](https://user-images.githubusercontent.com/30411972/128627820-56d30fc7-8572-40e0-9ec3-743f5d1c9745.png)

**Comment by timlrx** [comment]
I prefer it inline for a blog. However, feel free to pass the `toc` object to layout and render it as you describe. It should be a relatively straightforward modification.

**Comment by shanewasley** [comment]
Thanks for implementing this @timlrx, it looks great!
