### ISSUE TITLE
Build directions don't work with NPM only Yarn on node/NPM version on v14.16.0/6.14.11

### ISSUE THREAD

**Issue by akuzni2** [timlrx/tailwind-nextjs-starter-blog#17]
Hello -

Just found your starter blog. It's definitely the best looking one out there! I am trying to run the blog but running into errors when using your build directions.

NPM Version:  6.14.11
Node Version: v14.16.0

To reproduce
```
$ git clone https://github.com/timlrx/tailwind-nextjs-starter-blog.git
$ cd tailwind-nextjs-starter-blog/
$ npm run dev

sh: next: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! tailwind-nextjs-starter-blog@0.2.0 dev: `next dev`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the tailwind-nextjs-starter-blog@0.2.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

```

However I'm able to start the app successfully by running
```
yarn dev
```
Yarn version: 1.22.10

Maybe we can update the docs to use yarn? Or should we use a specific version of NPM/Node?

**Comment by timlrx** [comment]
I guess you are missing an `npm install` =)

**Comment by akuzni2** [comment]
@timlrx got it! Totally new to javascript/node this ecosystem. Thanks
