### ISSUE TITLE
Next.js giving error when substituting default svg logo to new png logo.

### ISSUE THREAD

**Issue by ChinmayGopal931** [timlrx/tailwind-nextjs-starter-blog#175]
The error is : Failed to load resource: the server responded with a status of 400 (Bad Request).

**Comment by timlrx** [comment]
Hi, which logo are you referring to? Is it the one in `data/logo.svg`? That's because svg and png files are loaded differently. If you load an svg file you can do:

```
import Logo from '@/data/logo.svg'

const Component = () => {
  <>
      <Logo />
  </>
}
```

But if you are using an image you should load it like this:

```
import Image from '@/components/Image'

const Component = () => {
  <>
      <Image src="path to image file" width="60px" height="60px" />
  </>
}
```
The image path should also be in the `public/static` folder. Hope that helps.

**Comment by ChinmayGopal931** [comment]
Hi,
    I have done this and I still get the error. I believe that this is an
issue with the current NEXT.js version. I am not sure how I can upgrade the
project to make it work. I am still new to next.js so I am open to
anything. Below I have provided a screenshot of what I have done. Here is a
link to a stackoverflow problem that seems relevant:
https://stackoverflow.com/questions/67693355/400-bad-request-from-next-image

Best,
Chinmay

**Comment by timlrx** [comment]
Are you using an image from an external domain. If so, you need to configure next config to explicitly whitelist that domain. Otherwise, could you link to your repository so I can take a look at the issue?

**Comment by ChinmayGopal931** [comment]
Hi,
   I even tried to display the avatar.png that is already in the public
image directory. I haven't made much changes to the repo yet. Thanks so
much for your time. Here is the link to the repo:
https://github.com/ChinmayGopal931/tailwind-nextjs-starter-blog.

**Comment by timlrx** [comment]
There's no valid image at the path specified in this line - https://github.com/ChinmayGopal931/tailwind-nextjs-starter-blog/blob/master/components/LayoutWrapper.js#L20

Try changing the src to `/static/images/avatar.png` and it will work. The path should be relative to the public folder.

**Comment by ChinmayGopal931** [comment]
I finally got it working. Sometimes I can be a little daft that was the
silliest error. Thanks so much for your time, I really appreciate it.
Best,
Chinmay
