### ISSUE TITLE
Image loader option

### ISSUE THREAD

**Issue by iliamrv** [timlrx/tailwind-nextjs-starter-blog#186]
My project has more than 1k images. After I uploaded it to Vercel, I had message that I used exceeded my limits. Is it possible to use cashed images from local version of my project instead of Vercel Edge Network Optimization? I found the solution to change the line in img-to-jsx.js

from 
(imageNode.name = 'Image'),

to
(imageNode.name = 'img'),

but that way I disable optimisation. 

In other words, I need to turn off Vercel optimisation but use static files from my local dev server. Could you help please?

**Comment by timlrx** [comment]
You have to change [this line](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/components/Image.js#L4) in the image component, not `img-to-jsx.js`. No need to touch that file. This would just use your file as it is without optimization.

**Comment by iliamrv** [comment]
After changing this line I have a message:

Error: Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element.  @next/next/no-img-element

**Comment by timlrx** [comment]
Yes, that's just eslint... Put a `/* eslint-disable */` at the top of the file and try again

**Comment by iliamrv** [comment]
Thanks for the solution!
