### ISSUE TITLE
Inconsistent title(s) ?

### ISSUE THREAD

**Issue by GautierArcin** [timlrx/tailwind-nextjs-starter-blog#188]
Hello, 

I don't know if it can be considered a bug or not or if it's excepted, but title of page seems to be incosistent.

For some pages (`about`, `page`,  `blog`, `projects`, ...), uses `siteMetadata.author`. Example: projects page's title is  `Projects - ${siteMetadata.author}`}
For `[Tags]`, it uses `${siteMetadata.title}`.
For `[..slug]`, it uses only the post slug title.

I'm mainly thinking about `[tags]`, maybe we could change it to `${siteMetadata.author}` in order to be consistent ?

**Comment by timlrx** [comment]
Hi @GautierArcin, A lot of the decisions on the SEO part really depends on what you intend to use it for and whether you want to promote your own name or maybe the website's name. I very well could see some users preferring to change all the titles to include `${siteMetadata.title}` or removing it completely. But, I am not opposed to changing `[Tags]` to `${siteMetadata.author}` and adding it for `[...slug]` as well for consistency sake.

**Comment by timlrx** [comment]
Fix in #187
