### ISSUE TITLE
A more simple commenting system?

### ISSUE THREAD

**Issue by vahidtakro** [timlrx/tailwind-nextjs-starter-blog#189]
Hello, thanks for this amazing starter template. And best commenting systems that are already on. I know they are the best, and very complete, but these very complete and complex systems take this template out of the simplicity (in my opinion).
Is there anyone who can suggest a more simple commenting system?
a system with user profile, self hosted, asking the user only name, and email and message, notify users on replies, maybe with google firebase database or anything like that? something like Wordpress commenting system.
I'd appreciate any suggestions.

Also another question related to this, how can I let the template to show comments on post loads, instead of "Load Comments", or maybe showing the last 10 comments by default, and then "Load More".

**Comment by timlrx** [comment]
On the other hand, I think these are the simplest options available. Good luck rolling your own and having to manage authentication, moderation, notification and servers just for comments. 

> how can I let the template to show comments on post loads, instead of "Load Comments", or maybe showing the last 10 comments by default, and then "Load More".

Use `useEffect` to load the script instead of the current onClick event.

**Comment by vahidtakro** [comment]
> On the other hand, I think these are the simplest options available. Good luck rolling your own and having to manage authentication, moderation, notification and servers just for comments.

indeed yes, that's now easy to use, and difficult to make another one.

> Use `useEffect` to load the script instead of the current onClick event.

thanks, I'll try.

**Comment by laymonage** [comment]
You can try looking into https://github.com/djyde/cusdis.

**Comment by vahidtakro** [comment]
> You can try looking into https://github.com/djyde/cusdis.

Thanks! I tried Cusdis, this is the best in my opinion, I could use with embed code, and cusdis hosting, but I still don't know how to do self hosting, as I am very basic learner.
I don't know how to create my PostgreSQL,
```
postgresql://johndoe:randompassword@localhost:5432/mydb
```

**Comment by osseonews** [comment]
The best comment system we found, after experimenting with every single one: is https://talk.hyvor.com/ - and we've already integrated it with this amazing theme. It's easy to do, Hyvor has a React guide which you can easily port into this theme. Thanks again for the all the hard work on this theme.

**Comment by MehediHasan-75** [comment]
> Hello, thanks for this amazing starter template. And best commenting systems that are already on. I know they are the best, and very complete, but these very complete and complex systems take this template out of the simplicity (in my opinion). Is there anyone who can suggest a more simple commenting system? a system with user profile, self hosted, asking the user only name, and email and message, notify users on replies, maybe with google firebase database or anything like that? something like Wordpress commenting system. I'd appreciate any suggestions.
> 
> Also another question related to this, how can I let the template to show comments on post loads, instead of "Load Comments", or maybe showing the last 10 comments by default, and then "Load More".

Sire?

**Comment by MehediHasan-75** [comment]
> Hello, thanks for this amazing starter template. And best commenting systems that are already on. I know they are the best, and very complete, but these very complete and complex systems take this template out of the simplicity (in my opinion). Is there anyone who can suggest a more simple commenting system? a system with user profile, self hosted, asking the user only name, and email and message, notify users on replies, maybe with google firebase database or anything like that? something like Wordpress commenting system. I'd appreciate any suggestions.
> Also another question related to this, how can I let the template to show comments on post loads, instead of "Load Comments", or maybe showing the last 10 comments by default, and then "Load More".

**Comment by MehediHasan-75** [comment]
> > On the other hand, I think these are the simplest options available. Good luck rolling your own and having to manage authentication, moderation, notification and servers just for comments.
> 
> indeed yes, that's now easy to use, and difficult to make another one.
> 
> > Use `useEffect` to load the script instead of the current onClick event.
> 
> thanks, I'll try.

**Comment by MehediHasan-75** [comment]
> On the other hand, I think these are the simplest options available. Good luck rolling your own and having to manage authentication, moderation, notification and servers just for comments.
> 
> > how can I let the template to show comments on post loads, instead of "Load Comments", or maybe showing the last 10 comments by default, and then "Load More".
> 
> Use `useEffect` to load the script instead of the current onClick event.

Ok?

**Comment by MehediHasan-75** [comment]
> > On the other hand, I think these are the simplest options available. Good luck rolling your own and having to manage authentication, moderation, notification and servers just for comments.
> 
> indeed yes, that's now easy to use, and difficult to make another one.
> 
> > Use `useEffect` to load the script instead of the current onClick event.
> 
> thanks, I'll try.

**Comment by MehediHasan-75** [comment]
```

.markdown a:hover {
    color: #6f42c1;
    text-decoration: underline;
    background-color: rgba(130, 80, 223, 0.15);
}
```
