### ISSUE TITLE
[page] for tags

### ISSUE THREAD

**Issue by vahidtakro** [timlrx/tailwind-nextjs-starter-blog#190]
Hello,
this feature may be very good to be on this template. having different pages (pagination) for tags pages. For example I have posted 60 .md posts with a "hello" hashtag, if I go to mywebsite.com/tags/hello, I see all those 60 posts in one page , which may takes a long time to load.

**Comment by timlrx** [comment]
60 article titles and descriptions would probably contain fewer words than one blog post. Since everything is created at build time, I won't worry about page load speed. Nonetheless, if you wish to implement a paginated version you can adapt the code from `blog/page/[page].js`

**Comment by vahidtakro** [comment]
> 60 article titles and descriptions would probably contain fewer words than one blog post. Since everything is created at build time, I won't worry about page load speed. Nonetheless, if you wish to implement a paginated version you can adapt the code from `blog/page/[page].js`

thanks, however I am displaying post feature images under the titles, so indeed it takes a long time to load the images.

**Comment by timlrx** [comment]
I see, in that case do look at copying over the code from `blog/page/[page].js`

**Comment by vahidtakro** [comment]
> I see, in that case do look at copying over the code from `blog/page/[page].js`

Thanks! I will try.
