### ISSUE TITLE
SEO: author page URL be added to ‘Article’ Schema structured data

### ISSUE THREAD

**Issue by PabloC** [timlrx/tailwind-nextjs-starter-blog#193]
**Is your feature request related to a problem? Please describe.**
Google updated its Schema-based structured data recommendations to include linking to an author’s bio page to help it disambiguate the correct author for an article.

**Describe the solution you'd like**
https://www.coywolf.news/seo/google-recommends-adding-a-link-to-the-author-page-in-article-structured-data/?utm_source=%23SEOFOMO&utm_campaign=4951c096b6-seofomo-newsletter-by-aleyda-aug-15&utm_medium=email&utm_term=0_408af963b1-4951c096b6-1327162044

**Comment by timlrx** [comment]
Makes sense to me, but I think it is better for the user to implement it and link either to an external URL or create multiple about pages to support multiple authors. 

The current template does not make having an external profile page / linkedin URL necessary and it does not automatically generate an about page for each user, so it's hard to prescribe what should be added (unless you have suggestions in this area?)
