### ISSUE TITLE
Remark autolink heading

### ISSUE THREAD

**Issue by vahidtakro** [timlrx/tailwind-nextjs-starter-blog#195]
I saw that remark autolink headings are imported, but it seems that they are not working.

**Comment by timlrx** [comment]
It should be working fine. Example - https://tailwind-nextjs-starter-blog.vercel.app/blog/new-features-in-v1#blog-comments-system

Please post an example that does not work?

**Comment by vahidtakro** [comment]
Sorry, I made a mistake in name, what I want is to linkable heading titles (H2, H3) in markdown files.
like how it works [here](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/data/blog/github-markdown-guide.mdx), I don't even know what this featured is called. I thought it's remark autolink heading.

![Captkjure](https://user-images.githubusercontent.com/40500566/129923472-f2b3b67c-4fc8-4114-a874-7d5510351837.JPG)

**Comment by timlrx** [comment]
I realized the recommended approach is to use the rehype-autolink-headings package instead of the remark package. From there you can pass in an argument to `options.content` to render the svg icon and link. The docs are over [here](https://unifiedjs.com/explore/package/rehype-autolink-headings/#options) if you want to implement it yourself, otherwise, I will put it on the roadmap and let you know when it's ready.

**Comment by vahidtakro** [comment]
> I realized the recommended approach is to use the rehype-autolink-headings package instead of the remark package. From there you can pass in an argument to `options.content` to render the svg icon and link. The docs are over [here](https://unifiedjs.com/explore/package/rehype-autolink-headings/#options) if you want to implement it yourself, otherwise, I will put it on the roadmap and let you know when it's ready.

Thanks, I think I can wait for that, I afraid if I make a mistake.

**Comment by timlrx** [comment]
Merged the changes to the master branch (#199). To get a link icon like what you want requested for, you can add the following lines to `lib/mdx.js`:

```
import {s} from 'hastscript'

const content = s(
  'svg',
  {
    xmlns: 'http://www.w3.org/2000/svg',
    width: 16,
    height: 16,
    fill: 'black',
    viewBox: '0 0 16 16',
    style: { display: 'inline' }
  },
  s('path', {
    d: 'M7.775 3.275a.75.75 0 0 0 1.06 1.06l1.25-1.25a2 2 0 1 1 2.83 2.83l-2.5 2.5a2 2 0 0 1-2.83 0 .75.75 0 0 0-1.06 1.06 3.5 3.5 0 0 0 4.95 0l2.5-2.5a3.5 3.5 0 0 0-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 0 1 0-2.83l2.5-2.5a2 2 0 0 1 2.83 0 .75.75 0 0 0 1.06-1.06 3.5 3.5 0 0 0-4.95 0l-2.5 2.5a3.5 3.5 0 0 0 4.95 4.95l1.25-1.25a.75.75 0 0 0-1.06-1.06l-1.25 1.25a2 2 0 0 1-2.83 0z'
  })
)
```

And modify the plugin in this line https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/lib/mdx.js#L100 to the
following:

```
[rehypeAutolinkHeadings, { content, behavior: 'append' }],
```

**Comment by vahidtakro** [comment]
> [rehypeAutolinkHeadings, { content, behavior: 'append' }],

Thanks! it works!
can I make it to display only on hover? like how Leerob blog works.

**Comment by vahidtakro** [comment]
I think I could manage to get it like this:
modifying the plugin in this line [https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/lib/mdx.js#L100](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/lib/mdx.js#L100) to the
following:

```
        [rehypeAutolinkHeadings, { properties: {
          className: ['anchor']
        } }],
```

and adding these to style `tailwind.css`

```
.prose .anchor {
  @apply absolute invisible;

  margin-left: -1em;
  padding-right: 0.5em;
  width: 80%;
  max-width: 700px;
  cursor: pointer;
}

.anchor:hover {
  @apply visible no-underline;
}

.prose .anchor:after {
  @apply text-gray-300 dark:text-gray-700;
  content: '#';
}

.prose *:hover > .anchor {
  @apply visible no-underline;
}
```

**Comment by timlrx** [comment]
Great, thanks for sharing a solution!
