### ISSUE TITLE
Unable to have cyrillic tags

### ISSUE THREAD

**Issue by vitalybaev** [timlrx/tailwind-nextjs-starter-blog#197]
**Describe the bug**
`kebabCase` function doesn't work with non-Latin characters.

**To Reproduce**
1. Go to any blog post
2. Add any tag with non-Latin characters, for example `производительность` (performance in Russian)
3. See error

**Expected behavior**
Build passed and tag correctly works

**Screenshots**
<img width="990" alt="CleanShot 2021-08-18 at 20 21 42@2x" src="https://user-images.githubusercontent.com/724423/129944040-a1e23cce-5e32-42d9-a841-19cf214d4c69.png">

**System Info (if dev / build issue):**
 - OS: macOS
 - Node version: 14 LTS
 - Npm version: -

**Comment by timlrx** [comment]
Can you try and see if [github-slugger](https://github.com/Flet/github-slugger) would work for you? I do not mind switching to that if it works.

**Comment by vitalybaev** [comment]
Yes, it now works properly. I've created MR for this
