### ISSUE TITLE
Build is failing when draft is true and tags are present

### ISSUE THREAD

**Issue by maikdiepenbroek** [timlrx/tailwind-nextjs-starter-blog#2]
First of all let me start of with saying what an amazing starter template this is. I've set it up with docker and deployed it on my own server. It was a breeze, so good job!

Just now i wanted to upload a new version of my site and the build started failing. Next to that the compose file does not generate the correct post file.

Steps to reproduce

- `node ./scripts/compose.js "My fancy title" md`
- Generated `my-fancy title.md` (notice the first dash is only present
After editing the post title to be kebab case again, writing the actual post and having the `draft set to true` i wanted to build so i ran `npm run build`
- That resulted in `TypeError: Cannot read property 'date' of undefined` 

Whenever i switched the `draft to false` and ran `npm run build` again, all things were fine again.

**Comment by timlrx** [comment]
Try pulling the latest updates from the master branch. I fixed the slug title problem a few days ago. The date in the blog post has to be a string e.g. '2021-01-31' and is required for the post.

I replicated your steps with the master branch and it works fine so let me know if that fixes it?

**Comment by timlrx** [comment]
Ok, I get the `TypeError: Cannot read property 'date' of undefined` problem. As per your title that happens when there are tags and draft is false. Will fix it.

**Comment by timlrx** [comment]
The problem was due to tag pages still creating routes based on draft posts. Fixed it in the latest commit, so just pull the latest change and it should work.

**Comment by maikdiepenbroek** [comment]
Clear! And thanks so much for the quick response and fix! I can confirm it's indeed working now!
