### ISSUE TITLE
Suggestion: Enable React Strict Mode?

### ISSUE THREAD

**Issue by DoctorDerek** [timlrx/tailwind-nextjs-starter-blog#20]
Hey @timlrx ,

Just curious what you'd think about enabling this:
"React's Strict Mode is a development mode only feature for highlighting potential problems in an application. It helps to identify unsafe lifecycles, legacy API usage, and a number of other features."
https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode

I found this quote:
"However, writing code resilient to occasional re-running of useEffect is a good practice even without Fast Refresh. It will make it easier for you to introduce new dependencies to it later on and it's enforced by React Strict Mode, which we highly recommend enabling." -- https://nextjs.org/docs/basic-features/fast-refresh

I'm happy to submit the PR if you think it's a good idea.

**Comment by timlrx** [comment]
Yup, we can add it in, thanks
