### ISSUE TITLE
Lazyload with tiny thumbnail

### ISSUE THREAD

**Issue by vahidtakro** [timlrx/tailwind-nextjs-starter-blog#200]
this week I was trying to find a good way to load my blog images, I figured out that Next.js optimizes images by default, but for having a lazyload you need to create a thumbnail for images to let them load before the main images load. (with a blur effect of course)
finally I found [this starter](https://github.com/JoseRFelix/nextjs-starter-blog) yesterday, which is generating static tiny thumbnails by default, to show before the main images load. Maybe this is a very good feature to add to this template.

**Comment by timlrx** [comment]
The images are lazy loaded by default. If you want to have the blur effect you can modify the image component. Take a look at the [docs](https://nextjs.org/docs/api-reference/next/image) and this [github issue](https://github.com/vercel/next.js/discussions/26168) for some ideas.

**Comment by vahidtakro** [comment]
Thanks, I figured out through the github issue that I can add blurData like this:
```
blurDataURL={`/_next/image?url=${images}&w=16&q=1`}
```

but my problem is that I don't know how to add it to Image component at `compontents/Image.js` to let all Images keep following setting.

my posts and pages are using a lot images, which don't let user to click on something before everything is loaded, if the user click on a link before the images are fully loaded, the url won't open , and even after everything is loaded the URLs are not still working. so refreshing the page fixes the problem. I don't know how to solve this, is it something about Next.js or the template or Image loader.

**Comment by timlrx** [comment]
Sorry, I don't quite understand what you are trying to do or what's the problem. Can you try re-explaining or showing an example?

**Comment by vahidtakro** [comment]
> Sorry, I don't quite understand what you are trying to do or what's the problem. Can you try re-explaining or showing an example?

sure,
it happens when you open a page, with a lot of content (like many photos) and you click on an internal URL before everything loads , nothing will open, and even this makes the website not opening any URLs even after everything loads, the solution is refreshing the page.
for example in [this URL](https://testingvahid.vercel.app/tags/russia), which is the URL to posts with a specific tag, if you click on any post before all images are loaded, you'll not get to that post, even after everything loads. for not facing this the user need to wait for everything to load, and then click on the post.

This is not only happening in tags or lists, but also posts, if they have many photos, for example [this post](https://testingvahid.vercel.app/france/paris-pere-lachaise-cemetery), will have same issue, because there are many photos in there, they are all optimized.

**Comment by timlrx** [comment]
I don't see that happening on the links you provided - the pictures are all lazy loaded and you can click your link and navigate away while they are loading. 

> how to add it to Image component at compontents/Image.js to let all Images keep following setting.

```
const Image = ({ src, ...rest }) => <NextImage src={src} placeholder="blur" blurDataURL={`/_next/image?url=${src}&w=16&q=1`} {...rest} />
```

**Comment by vahidtakro** [comment]
> ```
> const Image = ({ src, ...rest }) => <NextImage src={src} placeholder="blur" blurDataURL={`/_next/image?url=${src}&w=16&q=1`} {...rest} />
> ```
Thanks! this is what I was looking for.

> I don't see that happening on the links you provided - the pictures are all lazy loaded and you can click your link and navigate away while they are loading.

This happens sometimes only, just right after you open a page and try to click on a link. after 2,3 seconds this may won't happen. You may should open the URLs in Incognito.

meanwhile I figured out this is more likely to happen on mobile devices.
