### ISSUE TITLE
Code Block: no spaces on the right side

### ISSUE THREAD

**Issue by renomureza** [timlrx/tailwind-nextjs-starter-blog#209]
**Describe the bug**

There are no spaces on the right side of the code block.

**Expected behavior**

The space on the right side must be the same as the left side.

**Screenshots** https://tailwind-nextjs-starter-blog.vercel.app/blog/new-features-in-v1

![image](https://user-images.githubusercontent.com/49445216/131235887-49351536-a6f0-4a55-9488-45efbf159e86.png)

**Comment by timlrx** [comment]
Agree that it would look better with some paddiwng on the right. Would gladly accept a PR on this if someone wants to contribute a fix!

**Comment by larbisahli** [comment]
@timlrx A small hack.

```css
/* globals.css */
.code-line > span:last-child {
    padding-right: 4px;
    }
```

**Comment by timlrx** [comment]
Fix in #216. Thanks @llovvoll for trying it out and @larbisahli for finding a fix that should work for all cases.

**Comment by renomureza** [comment]
This seems to be causing the line highlighting not to fully highlight the line.

Before: https://tailwind-nextjs-starter-blog-git-fork-humble-barn-a10bc2-timlrx.vercel.app/blog/new-features-in-v1#line-highlighting-and-line-numbers

![image](https://user-images.githubusercontent.com/49445216/132113562-c833ba11-5e83-439d-b0ca-523fd075617e.png)

After: https://tailwind-nextjs-starter-blog.vercel.app/blog/new-features-in-v1#line-highlighting-and-line-numbers

![image](https://user-images.githubusercontent.com/49445216/132113540-353ad46b-b90c-4782-801c-99a15f033b75.png)

**Comment by timlrx** [comment]
Yes, you are right, `w-max` breaks line highlighting.

**Comment by timlrx** [comment]
I will modify `rehype-prism-plus` plugin directly to wrap text nodes in a span so that the solution proposed by @llovvoll would work for all cases:

```
.code-line > span:last-child {
  @apply pr-4;
}
```

**Comment by renomureza** [comment]
Yes it seems to be the best solution and it can solve the same problem on mobile.

If possible we need to change the `div` with `span` to make it valid validator.w3.org like Tailwindcss documentation:: https://validator.w3.org/nu/?doc=https%3A%2F%2Ftailwindcss.com%2Fdocs%2Ffloat

Without error: _Error: Element div not allowed as child of element code in this context._

This error appears in tailwind-nextjs-starter-blog: https://validator.w3.org/nu/?doc=https%3A%2F%2Ftailwind-nextjs-starter-blog-timlrx.vercel.app%2Fblog%2Fnew-features-in-v1

**Comment by larbisahli** [comment]
@timlrx I think we can just add a width of 100% to the highlight-line class
```css
.highlight-line {
  width: 100%;
}
```

**Comment by timlrx** [comment]
Ok, I added a fix for this issue and several other related issues in #227. Let me know if you encounter any other issues, or I will proceed to merge.

**Comment by renomureza** [comment]
@timlrx I think everything is perfect, thanks for fixing
