### ISSUE TITLE
Errors on Vercel build

### ISSUE THREAD

**Issue by theapplegates** [timlrx/tailwind-nextjs-starter-blog#21]
I am getting some strange errors when I try to import the site to Vercel. I use the default values. I had the site up until a few days ago when it would fail to build. I am not a developer am not sure where to start. Here is the Vercel log file.

I made a gist for a more readable format. Not sure why it looks bad in a preview.

https://gist.github.com/theapplegates/e3d2d065ec51b8531ce13631cfaaf0e4

`01:17:37	Cloning github.com/theapplegates/crispy-parakeet-tailwind (Branch: main, Commit: 0e615ee)
01:17:38	Cloning completed: 652.690ms
01:17:38	Analyzing source code...
01:17:40	Installing build runtime...
01:17:45	Build runtime installed: 5222.614ms
01:17:49	Looking up build cache...
01:17:49	Build cache not found
01:17:51	Installing dependencies...
01:17:51	yarn install v1.22.10
01:17:51	warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
01:17:51	[1/4] Resolving packages...
01:17:51	[2/4] Fetching packages...
01:18:04	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
01:18:04	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
01:18:04	[3/4] Linking dependencies...
01:18:04	warning " > next-mdx-remote@2.1.3" has incorrect peer dependency "react@>=16.13.1 <=17.0.1".
01:18:04	warning " > next-mdx-remote@2.1.3" has incorrect peer dependency "react-dom@>=16.13.1 <=17.0.1".
01:18:04	warning " > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
01:18:15	[4/4] Building fresh packages...
01:18:16	Done in 24.48s.
01:18:16	Detected Next.js version: 10.1.3
01:18:16	Running "yarn run build"
01:18:16	yarn run v1.22.10
01:18:16	$ next build && node ./scripts/generate-sitemap
01:18:17	info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
01:18:17	info  - Checking validity of types...
01:18:17	Attention: Next.js now collects completely anonymous telemetry regarding usage.
01:18:17	This information is used to shape Next.js' roadmap and prioritize features.
01:18:17	You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
01:18:17	https://nextjs.org/telemetry
01:18:17	info  - Creating an optimized production build...
01:18:22	warn - You have enabled the JIT engine which is currently in preview.
01:18:22	warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
01:18:32	info  - Compiled successfully
01:18:32	info  - Collecting page data...
01:18:33	info  - Generating static pages (0/30)
01:18:34	info  - Generating static pages (7/30)
01:18:34	info  - Generating static pages (14/30)
01:18:35	info  - Generating static pages (22/30)
01:18:36	Error occurred prerendering page "/blog/introducing-tailwind-nextjs-starter-blog". Read more: https://nextjs.org/docs/messages/prerender-error
01:18:36	TypeError: unsupported file type: undefined (file: /vercel/path0/public/static/images/twitter-card.png)
01:18:36	    at lookup (/vercel/path0/node_modules/image-size/dist/index.js:51:11)
01:18:36	    at imageSize (/vercel/path0/node_modules/image-size/dist/index.js:118:16)
01:18:36	    at /vercel/path0/.next/server/pages/tags/[tag].js:551:26
01:18:36	    at overload (/vercel/path0/node_modules/unist-util-visit/index.js:27:12)
01:18:36	    at node (paragraph) (/vercel/path0/node_modules/unist-util-visit-parents/index.js:56:27)
01:18:36	    at node (root) (/vercel/path0/node_modules/unist-util-visit-parents/index.js:67:75)
01:18:36	    at visitParents (/vercel/path0/node_modules/unist-util-visit-parents/index.js:29:26)
01:18:36	    at visit (/vercel/path0/node_modules/unist-util-visit/index.js:22:3)
01:18:36	    at /vercel/path0/.next/server/pages/tags/[tag].js:546:3
01:18:36	    at wrapped (/vercel/path0/node_modules/trough/wrap.js:25:19)
01:18:40	info  - Generating static pages (30/30)
01:18:40	> Build error occurred
01:18:40	Error: Export encountered errors on following paths:
01:18:40		/blog/introducing-tailwind-nextjs-starter-blog
01:18:40	    at /vercel/path0/node_modules/next/dist/export/index.js:31:1106
01:18:40	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:5:584)
01:18:40	    at async /vercel/path0/node_modules/next/dist/build/index.js:43:49
01:18:40	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:5:584)
01:18:40	    at async /vercel/path0/node_modules/next/dist/build/index.js:25:1475
01:18:40	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:5:584)
01:18:40	error Command failed with exit code 1.
01:18:40	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
01:18:40	Error: Command "yarn run build" exited with 1`

**Comment by DoctorDerek** [comment]
That error basically says you're missing the /twitter-card.png image,
though it does look like it's present in the GitHub directory.

>

**Comment by theapplegates** [comment]
That file missing caused all that? wow. 
You were right, I did have the file. I then deleted it and uploaded it back and the site deployed fine. 
Thanks for the help.

**Comment by DoctorDerek** [comment]
Yeah it's a sucky bug because you usually don't catch it in development
(unless you try building locally, and why would you), but it will
completely crash deployment.

On the plus side, it's a fantastic check against missing resources and
pages lol -- no 404

Best regards,
Derek

Derek R. Austin, PT, DPT, MS, BCTMB, LMT, CSCS

[image: Headshot of Doctor Derek smiling and waving at the camera.]
<https://www.doctorderek.com/>
Dr. Derek Austin 🥳
SEO & Web Performance Expert
<https://doctorderek.com/> DoctorDerek.com <https://doctorderek.com/>
<https://www.linkedin.com/in/derek-austin> LinkedIn.com/in/Derek-Austin
<https://www.linkedin.com/in/derek-austin>
<https://twitter.com/AskDoctorDerek> Twitter.com/AskDoctorDerek
<https://twitter.com/AskDoctorDerek>
Read my blog:
<https://doctorderek.medium.com/> Medium.com/@DoctorDerek
<https://doctorderek.medium.com/>

**Comment by DoctorDerek** [comment]
Hey @theapplegates I think that was a transient bug I managed to cause while trying to update the `.gitattributes` file in #19, so sorry for the inconvenience. Hopefully everything is working OK now.
