### ISSUE TITLE
When you cancel OAuth permission it redirect you to localhost

### ISSUE THREAD

**Issue by larbisahli** [timlrx/tailwind-nextjs-starter-blog#210]
**Describe the bug**
When you cancel OAuth permission it redirects you to localhost:3000

**To Reproduce**
Steps to reproduce the behaviour:
On the comment section click login with GitHub and then click cancel.

**Expected behavior**
Redirect to the main website, not to localhost:3000

**Screenshots**
![Screenshot 2021-08-29 065359](https://user-images.githubusercontent.com/52937392/131240272-67a6d8f5-2d9a-4574-bb32-fa63d8ab583c.png)

**Additional context**
Redirect to:
http://localhost:3000/api/oauth/authorized?error=access_denied&error_description=The+user+has+denied+your+application+access.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23access-denied&state=e407365ecb2216a74bd8181cwqG9IbwVlqiQrHgefNsT4DrELP7zs5Gi7QW56DSSDL4ZKw%2FZeDJqh4phiDjlqutoLSTyIskwCEIyFS4JyweC96ElrLtcC2Hr5kF5Uk59ZwbQvr9ShhS%2BAymTdpds8oG3oKAiT2Hmhcsj620TGJroLwIrDh6eElYjH9B8GggD

**Comment by timlrx** [comment]
This happens when you are installing Giscus for your repository - https://github.com/apps/giscus? Or when you are trying to comment? Either way, opening an issue on Giscus would be better. Thanks.

**Comment by larbisahli** [comment]
This happened when I am trying to log in for comment in https://tailwind-nextjs-starter-blog.vercel.app/

**Comment by timlrx** [comment]
@laymonage any settings which I could specific the redirect link? Do I have to specify an `ORIGINS` env variable or does giscus automatically takes `location.origin`?

**Comment by laymonage** [comment]
Thanks for the report! I've pushed a possible fix in https://github.com/laymonage/giscus/pull/167, let me know if that fixed it.

**Comment by timlrx** [comment]
Thanks for the quick fix! @larbisahli let me know if it solves the problem?

**Comment by larbisahli** [comment]
@timlrx Yes, the problem is fixed thank you.
