### ISSUE TITLE
Support Diff Highlight

### ISSUE THREAD

**Issue by nguyenyou** [timlrx/tailwind-nextjs-starter-blog#223]
It would be nice if the template provides support for the code diff highlight.

![image](https://user-images.githubusercontent.com/38455472/132104343-385bc968-5f2e-4562-a16b-b93c000fb1be.png)
Ref: https://blog.tailwindcss.com/tailwindcss-2-2

The Tailwindcss blog implementation of this feature: https://github.com/tailwindlabs/blog.tailwindcss.com/blob/master/remark/vendor/prism-diff-highlight.js

**Comment by timlrx** [comment]
That would be quite a bit of work to implement since we don't use prismjs directly but through refractor which does it at build time so the plugin cannot be copied over. Happy to receive a PR over here - https://github.com/timlrx/rehype-prism-plus if anyone is interested in contributing.

**Comment by PsyGik** [comment]
Looks like refractor supports diff. https://github.com/wooorm/refractor/blob/main/lang/diff.js

Given,

````
```diff
-let foo = bar.baz([1, 2, 3]);
+foo = foo + 1;
const foo = bar.baz([1, 2, 3]) + 1;
console.log(`foo: ${foo}`);
```
````

Produces:

```html
<code class="language-diff">
  <span class="code-line">
    <span class="token deleted-sign deleted">
      <span class="token prefix deleted">-</span>
      <span class="token line">let foo = bar.baz([1, 2, 3]); </span>
    </span>
  </span>
  <span class="code-line">
    <span class="token deleted-sign deleted">
      <span class="token line"></span>
    </span>
    <span class="token inserted-sign inserted">
      <span class="token prefix inserted">+</span>
      <span class="token line">foo = foo + 1; </span>
    </span>
  </span>
  <span class="code-line">
    <span class="token inserted-sign inserted">
      <span class="token line"></span>
    </span>
    const foo = bar.baz([1, 2, 3]) + 1;
  </span>
  <span class="code-line">console.log(`foo: ${foo}`); </span>
</code>

````

which can then by styled as per convenience.

**Comment by PsyGik** [comment]
Looks like refractor supports diff. https://github.com/wooorm/refractor/blob/main/lang/diff.js

Given,

````
```diff
-let foo = bar.baz([1, 2, 3]);
+foo = foo + 1;
const foo = bar.baz([1, 2, 3]) + 1;
console.log(`foo: ${foo}`);
```
````

Produces:

```html
<code class="language-diff">
  <span class="code-line">
    <span class="token deleted-sign deleted">
      <span class="token prefix deleted">-</span>
      <span class="token line">let foo = bar.baz([1, 2, 3]); </span>
    </span>
  </span>
  <span class="code-line">
    <span class="token deleted-sign deleted">
      <span class="token line"></span>
    </span>
    <span class="token inserted-sign inserted">
      <span class="token prefix inserted">+</span>
      <span class="token line">foo = foo + 1; </span>
    </span>
  </span>
  <span class="code-line">
    <span class="token inserted-sign inserted">
      <span class="token line"></span>
    </span>
    const foo = bar.baz([1, 2, 3]) + 1;
  </span>
  <span class="code-line">console.log(`foo: ${foo}`); </span>
</code>

````

which can then by styled as per convenience.

**Comment by timlrx** [comment]
Thanks for discovering that! We can add some default styling to support it out of the box, should be relatively easy.

**Comment by timlrx** [comment]
Did a small improvement in `rehype-prism-plus` to tag the inserted or deleted line. See #273 for an example.
