### ISSUE TITLE
Slow indexing in Google

### ISSUE THREAD

**Issue by iliamrv** [timlrx/tailwind-nextjs-starter-blog#226]
hello Timothy,

I noticed that latest posts in my blog based on tailwind-nextjs-starter-blog are not indexed. Some fresh posts in your blog are not indexed too, for example:

https://www.timlrx.com/blog/creating-a-rehype-syntax-highlighting-plugin

Is sitemap.xml format optimal for google search console? Probably, it would be better to add lastmod property for every post to let crawler know when it was updated. 

Thanks.

**Comment by timlrx** [comment]
You can submit the rss feed to google if you are worried. I don't see the need to add more information to the sitemap, unless you can link some sources which suggest that that is the best practice.
