### ISSUE TITLE
npm run export

### ISSUE THREAD

**Issue by tebogo37** [timlrx/tailwind-nextjs-starter-blog#231]
I prefer firebase hosting to leverage the firebase database and functions.
This is how I am using images  < img className="-ml-12 " src={images} />

when I run npm run export 
Here is the error. 

` Copying "static build" directory
info  - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Use any provider which supports Image Optimization (like Vercel).
    - Configure a third-party loader in `next.config.js`.
    - Use the `loader` prop for `next/image`.
  Read more: https://nextjs.org/docs/messages/export-image-api
    at C:\Users\tebog\Documents\projects\sasdir\node_modules\next\dist\export\index.js:257:23
    at async Span.traceAsyncFn (C:\Users\tebog\Documents\projects\sasdir\node_modules\next\dist\telemetry\trace\trace.js:60:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tailwind-nextjs-starter-blog@1.1.1 export: `next export`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tailwind-nextjs-starter-blog@1.1.1 export script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. `

**Comment by timlrx** [comment]
You just need to change this [line](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/components/Image.js#L4) to `const Image = ({ ...rest }) => <img {...rest} />`

I have no idea what you are trying to do by placing images in the img tag.

Can I check that you are running `next build` first before running `next export`?

**Comment by tebogo37** [comment]
Thank you for that. Yes I am building before exporting. 

"build": "next build && node ./scripts/generate-sitemap",
"serve": "next start",
"export": "next export",


![image](https://user-images.githubusercontent.com/37803062/132528734-70d350a2-2c45-48d0-bc41-c0e259103381.png)

Same error

![image](https://user-images.githubusercontent.com/37803062/132528932-e660c7b2-3476-4049-a655-104c2a89ea02.png)

**Comment by tebogo37** [comment]
next export works perfectly. @timlrx Thank you very much!
