### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by hta218** [timlrx/tailwind-nextjs-starter-blog#233]
**Is your feature request related to a problem? Please describe.**
Add a changelog post to keep track of what changes in each update, now we have to view the commits

**Describe the solution you'd like**
Just a blog post about changelog

**Comment by timlrx** [comment]
Unfortunately, it takes quite a bit of time to write a detailed blog post describing the main updates like the v1.0 one. Have you seen the [release page](https://github.com/timlrx/tailwind-nextjs-starter-blog/releases/tag/v1.1.2)? Hopefully, that gives you an idea of the main changes across versions.

**Comment by hta218** [comment]
Yeah, saw it, but not much detail there :( I have to search through the project myself to see what changes in that log

**Comment by timlrx** [comment]
Sorry about this, but I doubt I will write a blog post for every release, just too time-consuming for a personal project. Thanks for your understanding.
