### ISSUE TITLE
Typescript branch is slightly outdated

### ISSUE THREAD

**Issue by timlrx** [timlrx/tailwind-nextjs-starter-blog#243]
Typescript branch is current sync to v1.1.0 while master is at v1.1.3. Any TS users willing to help update the TS branch to the latest version? Thanks!

**Comment by ryands17** [comment]
What's the main difference b/w the two branches? I could help with the update if I know the changes 🙂

**Comment by timlrx** [comment]
Hi @ryands17, it would be best to compare the differences in the js branch for the version tag at v1.1.0 and the current v1.1.3. A summary of the changes can also be viewed at the [release page](https://github.com/timlrx/tailwind-nextjs-starter-blog/releases). I think the two biggest things that needs to be sync are the new newsletter feature and the changes associated with code highlighting. The rest of the issues should be minor tweaks and fixes.

**Comment by ryands17** [comment]
One way that I could go about is version by version updating the changes based on the files. Wdyt?

**Comment by timlrx** [comment]
I recommend looking at the file changes across the versions and updating those files to the latest one directly in v1.1.3. You can try using the compare tool: https://github.com/timlrx/tailwind-nextjs-starter-blog/compare/v1.1.0...v1.1.3

**Comment by ryands17** [comment]
Awesome! Will get started on this one 🙂

**Comment by ryands17** [comment]
Done: https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/246

**Comment by wsameer** [comment]
@timlrx  This issue can be closed since a fix has been merged.
