### ISSUE TITLE
Doesn't work with target set to `serverless`

### ISSUE THREAD

**Issue by ryands17** [timlrx/tailwind-nextjs-starter-blog#247]
**Describe the bug**
When adding `target: serverless` to `next.config.js`, creating a build results in the following error:

![image](https://user-images.githubusercontent.com/19697099/133787931-cc45974d-3994-4df7-85ea-69f1ebbe8582.png)

**To Reproduce**
1. Clone the repo
2. Add `target: serverless` to `next.config.js`
3. Run `npm run build`

**Expected behavior**
It should build successfully.

**System Info (if dev / build issue):**
 - OS: Mac
 - Node version (please ensure you are using 12+): 14.17.4
 - Npm version: 6.14.4

**Comment by timlrx** [comment]
Hi @ryands17, it seems like serverless does not cover the full feature set and is no longer recommended. 

See related posts: https://github.com/vercel/next.js/issues/20790, https://github.com/vercel/next.js/issues/20487#issuecomment-753884085

**Comment by ryands17** [comment]
Would you have any idea of how to deploy this on Lambda for e.g. without the `serverless` target?

**Comment by timlrx** [comment]
> Would you have any idea of how to deploy this on Lambda for e.g. without the serverless target?
Unfortunately not. 

> If not, would it be possible to make this work with target: 'serverless' by coming up with a fix?
Have to check what's causing it first.

If anyone else has experience deploying it on Lambda, appreciate your input.

**Comment by timlrx** [comment]
Just tried replicating the problem on a freshly clone version of the master branch - it works for me with `target: serverless`. Are you using the js or ts branch? And does it work for you if you exclude the `target: serverless` line?

**Comment by ryands17** [comment]
Could you try installing the modules with `yarn` instead of `npm` and check? It seems that when I install them with `npm` it works fine, but on installing with `yarn` it gives me the above error.

**Comment by timlrx** [comment]
I get the same error as well with `yarn` and `serverless`. It works without the `serverless` setting, so I guess it's some interaction between `yarn`, nextjs `serverless` and webpack 5 that might be causing it.
