### ISSUE TITLE
MDX + KaTeX Pages

### ISSUE THREAD

**Issue by honeycombi** [timlrx/tailwind-nextjs-starter-blog#248]
Is there a way to make MDX pages not in the blog also render KaTeX? I've figured out how to make MDX pages by following the [MDX Guide](https://mdxjs.com/getting-started/next/), but the [Math Blocks Page](https://mdxjs.com/guides/math-blocks/) doesn't work. I would like to see pages that support MDX + KaTeX just like blog.

When I follow the [MDX Guide](https://mdxjs.com/getting-started/next/), I get
`next.config.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from package.json`

The first idea keeps telling me to make more files end in .cjs and looks like a cycle that never ends. The second idea tells me `SyntaxError: Cannot use import statement outside a module`. The third idea doesn't seem to do anything.

My NPM version is 7.24.1 and I just cloned this repository today.

Help would be greatly appreciated! Thanks in advance.

**Comment by timlrx** [comment]
Yes, it's possible - see the [author page](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/pages/about.js) for an example.

I am not sure what you are implementing on MDX. There should be no other configuration required since the template already uses XDM to compile MDX.

**Comment by honeycombi** [comment]
Hmm, if I don't configure anything and create a MDX files in the /pages directory, even without KaTeX it shows the following
<img width="1418" alt="Screen Shot 2021-09-25 at 7 11 53 AM" src="https://user-images.githubusercontent.com/83254658/134769414-67b130a2-b332-491a-8169-7a83022389f8.png">
Do I have to create it in a different folder?

**Comment by timlrx** [comment]
Yes, the `pages` folder only accepts `tsx` files. You have to load the `.md` or `.mdx` files from the data folder. Again, please see the author page for an example. This template does not use mdx-js loader so if you are looking for something like what you describe, you should look elsewhere.

**Comment by honeycombi** [comment]
Thanks for the help! I'll look elsewhere.
