### ISSUE TITLE
Is any way to add css/html classes to markdown?

### ISSUE THREAD

**Issue by iliamrv** [timlrx/tailwind-nextjs-starter-blog#249]
Hello,

For example, I'd like to add a button tag or 'download' class to 'a href' to my article. The only way I can see right now is to use html tags by themselves in .md files. 

Is any way to add css/html classes or snippets to markdown in next js? 

Thanks in advance for the answer!

**Comment by timlrx** [comment]
Yes, you can either just add a HTML tag in the markdown file or define your own MDX component and use it in the template like the newsletter component in the template. You just need to add the component to [MDXComponents](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/components/MDXComponents.js) and use it in your markdown file.

**Comment by iliamrv** [comment]
Thanks!
