### ISSUE TITLE
Blog Nested Routes??

### ISSUE THREAD

**Issue by mrhut10** [timlrx/tailwind-nextjs-starter-blog#25]
I plan on doing a either a series blog post or dividing a post into bite size chunks so wanted to support nested routing of the blog route.

I've got a local branch that already supports it,

would anyone else benefit from this, should I open a PR??

![image](https://user-images.githubusercontent.com/20330237/115061041-f8b5b480-9f2b-11eb-8941-595e38639a7b.png)

![image](https://user-images.githubusercontent.com/20330237/115061000-e6d41180-9f2b-11eb-8cf0-32558736960a.png)

**Comment by timlrx** [comment]
Thanks @mrhut10 for the new feature! Have merged it to the master branch and released it as v0.3.1 🎉
