### ISSUE TITLE
Add NextAuth to Theme

### ISSUE THREAD

**Issue by osseonews** [timlrx/tailwind-nextjs-starter-blog#255]
**Is your feature request related to a problem? Please describe.**
No, this feature is not related a problem.

**Describe the solution you'd like**
Can you add a basic integration with https://next-auth.js.org/ to this theme? We don't think you need to add every feature, but just a basic "protected" blog bost and page, which can then be obviously replicated for other posts/pages. The idea is that many blogs nowadays have some sort membership mechanism for monetization and add Next Auth would make it really easy to convert part of this theme to member-only blog posts. Thanks.

**Describe alternatives you've considered**
There many services to use for authentication but NextAuth is the best one we've seen for Next specific projects.

**Comment by timlrx** [comment]
Yup, I can see the use case. Happy to accept a PR if someone has it implemented for their own blog and wants to contribute back.

**Comment by timlrx** [comment]
Added it to the V2 discussion - https://github.com/timlrx/tailwind-nextjs-starter-blog/discussions/275

**Comment by vicheanath** [comment]
i have the same problame i to fixed it.
