### ISSUE TITLE
Broken When No Blog Files

### ISSUE THREAD

**Issue by mrhut10** [timlrx/tailwind-nextjs-starter-blog#26]
To support people setting up for the first time if they delete the template files then the application breaks. as there are hardcoded references to the first item in the posts array.

from memory its to access the date property on the first blog post. `post[0].date` 

would be good to have a fallback render thats safe for the `0` length posts array.

anyway its a small thing, should be a easy PR for any of the people watching

**Comment by timlrx** [comment]
Yes, sounds good. Happy to accept a PR on this

**Comment by timlrx** [comment]
It's fine, I deleted the posts and it shows:
![image](https://user-images.githubusercontent.com/28362229/115951359-e8e13600-a512-11eb-864e-91b4cfa9f791.png)

**Comment by NoldAndreas** [comment]
Hi, I really love the template. One thing: with the newest version (from May 4,2021, 0.3.0, commit 69a41932e7299b41558e489eb614d66000e4b3b0)  it still breaks when deleting posts. I got 
<img width="984" alt="Screen Shot 2021-05-04 at 14 16 25" src="https://user-images.githubusercontent.com/26619468/117002826-598f0c00-ace4-11eb-97b6-0fc11b6f9926.png">
when deleting the blog entry "the-time-machine.mdx".
