### ISSUE TITLE
eslint doesn't work well 

### ISSUE THREAD

**Issue by yangxin9527** [timlrx/tailwind-nextjs-starter-blog#265]
**Describe the bug**

when i use `npm i` ,   eslint doesn't work well .
but yarn is ok .

**To Reproduce**
1. use this template and clone it
2. npm i
3. npm run lint

**Expected behavior**
use `npm i ` and Eslint works well.

**Screenshots**

![image](https://user-images.githubusercontent.com/18702092/140036276-d60ebd59-3b6e-45ee-8ad1-cc8118296af2.png)

**System Info (if dev / build issue):**
 - OS: windows10
 - Node version : v14.17.0
 - Npm version : 6.14.13
 - Yarn version: 1.22.10

**Additional context**
thanks !!! I don't know what happened. O(∩_∩)O

**Comment by timlrx** [comment]
Hmm strange, it seems that it can't locate the `eslint-config-next` file which should be installed. I would just try to delete `node_modules` and `package-lock.json` and `npm install` again. It works for me on a freshly cloned version on windows.

**Comment by yangxin9527** [comment]
Perhaps because i use a china npm mirror , cnpm . now i change mirror , it works. Thank you !!
