### ISSUE TITLE
How can I add a new post to deployed app on vercel

### ISSUE THREAD

**Issue by ashwaniYDV** [timlrx/tailwind-nextjs-starter-blog#272]
I have deployed this blog on vercell. How can I add new post there?

**Comment by timlrx** [comment]
You will need to add the post in the `data/mdx` section being deploying. Or did I misunderstand the question?

**Comment by ashwaniYDV** [comment]
> You will need to add the post in the `data/mdx` section being deploying. Or did I misunderstand the question?

You mean if I have to add a new post I can add it to my github repo and it should be redeployed. Am I correct?

**Comment by timlrx** [comment]
Yes. Please checkout https://github.com/timlrx/tailwind-nextjs-starter-blog#extend--customize and https://github.com/timlrx/tailwind-nextjs-starter-blog#post for more information on extending and customizing.

**Comment by ashwaniYDV** [comment]
> Yes. Please refer to https://github.com/timlrx/tailwind-nextjs-starter-blog#extend--customize and https://github.com/timlrx/tailwind-nextjs-starter-blog#post for more information on extending and customizing.

Thanks a lot @timlrx :)
