### ISSUE TITLE
RFC: What would you like to see for V2?

### ISSUE THREAD

**Issue by timlrx** [timlrx/tailwind-nextjs-starter-blog#276]
Any feedback and suggestions? Kindly post them in https://github.com/timlrx/tailwind-nextjs-starter-blog/discussions/275

**Comment by louwers** [comment]
Typescript!

**Comment by timlrx** [comment]
Any particular feature in `contentlayer` that you are looking for? 

The 2 main advantages I can see are automatic content validation and support for other content types (but would you use Sanity together with Contentful and markdown?). 

The downsides are that is in alpha stage, is restricted to local content only and you have to manage two config files with similar information if you want to couple it with a git based CMS like netlifyCMS or forestry.io.

The additional boilerplate code will be addressed with the new repository structure where I will export these utility functions and types.

**Comment by bketelsen** [comment]
I haven't used it yet, but it appears to be a decent facade that would abstract the content source from the page building logic. That was the appeal when I was looking at it this morning.

**Comment by louwers** [comment]
Tailwind 3.0 was released https://tailwindcss.com/blog/tailwindcss-v3

**Comment by timlrx** [comment]
@louwers the main template is now on tailwind 3.0.

**Comment by fiqryq** [comment]
> Tailwind 3.0 was released https://tailwindcss.com/blog/tailwindcss-v3

hello i use this template using tailwind 2 how can I upgrade to tailwind 3?

**Comment by timlrx** [comment]
Hi @fiqryq, you can use the file diff in https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/295/files to update your template.

**Comment by derberg** [comment]
I love your template man! Great stuff!

I only had to add on my own YouTube support. So you can add it to your roadmap, super easy to add -> https://github.com/derberg/derberg.github.io/commit/1bbc5e4ab1d7fb32ecc6598d02343baf5fd1efda and then just use it like `<YouTube id="1GSaf4b1-Qw" />` in MDX files

**Comment by timlrx** [comment]
Thanks @derberg! Here's my preferred way of doing it: https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/311, as an iframe directly in the mdx. Or there's mdx-embed as well which supports many other social media widgets.

**Comment by derberg** [comment]
No worries. I personally prefer consistency always. So in mdx I want to use components, no HTML directly, especially avoiding iframes 😄 

- `mdx-embed` does look nifty! would be better
- also notice `ContentSecurityPolicy` that I had to modify to enable embedding youtube videos. So no matter what solution you choose, component or iframe, would be cool to explain it, probably another example article or something. I'm not sure if everyone would know how to get this fixed

I'm happy to contribute this part if you want, no matter what is your final decision. Thanks to your template I set up my blog (https://www.brainfart.dev/) in just a few hours, just love it mate! Want to pay back my time, if you need it!

**Comment by kevinzunigacuellar** [comment]
Hello! I love your template. I was thinking an i18n for blog posts in different languages would be nice. What do you all think?

**Comment by timlrx** [comment]
There is a [fork](https://github.com/GautierArcin/i18n-tailwind-nextjs-starter-blog/tree/demo/next-translate) by @GautierArcin that supports i18n, but the plan is to have better out of the box support for the new template.

**Comment by louwers** [comment]
Is it possible to change the metatags image per post?

**Comment by meherranjan** [comment]
Possible to co-locate post-related images next to the post itself? Like how it works in Gatsby.

**Comment by alexghi** [comment]
It would be interesting if somehow we could add images in md that can be viewed after in a "lightbox" gallery

**Comment by maartendamen** [comment]
First of all thank you so much for creating this starter, I love it.
It would be nice to include a search function. 

Also it would be nice if there would be an easier method to publish new posts. 
Right now I host this myself and I publish using a docker build, this is quite time consuming.

**Comment by alexghi** [comment]
There is a "search" functionality that goes through all the posts titles. Are you having in mind something more powerful that searches inside the articles as well? such as MeiliSearch (i like this one because it's powerful and lightweight, has very good doc)?

**Comment by derberg** [comment]
You can have full search with https://lunrjs.com/. I use it some time ago for building search index, pretty nifty, client-side search 💪🏼 

But out of the box integration with Algolia Docu Search would be nifty too

**Comment by timlrx** [comment]
Search would probably be implemented like the existing `analytics` or `comments` components, where you can pick and choose what works for you, or none at all. The first one would probably be Algolia given its popularity and ease of integration (for public projects). 

For reference, here are the [search options supported by docusaurus](https://docusaurus.io/docs/search).

**Comment by sokirill** [comment]
I love this theme! Have more of a question of sustaining the versioning and keeping up to date with customization. So in a way, increasing maintainability by understanding which components I can add / adjust and what is sort of a core that gets updated. Not sure if that is possible. 

I am also thinking of connecting a Notion API (so that the posts get pulled from notion instead) but that would probably mess with the MDX. 

Generally more out of the box integrations might be cool, but I guess depends on the demand.

**Comment by MiltonAkash** [comment]
The current version is not respecting the device's text size configurations. I have set VERY LARGE in my mobile and many other sites adjust text like this but this template doesn't adjust for it. Hard to read the small text

**Comment by piyushpaliwal** [comment]
I have a couple of suggestions

- Additional details for tag page
  - Currently it shows just the title of tag with posts; what would be interesting is the ability to add things like tag images, descriptions, etc.
- Ability to add reactions to post
- Support for reading time, with an optional flag in siteMetadata
- Author page layout for multi-authored blog
- Support for webmentions

**Comment by timlrx** [comment]
Please contribute to the discussion at https://github.com/timlrx/tailwind-nextjs-starter-blog/discussions/275 to centralize the information in one place.

This is just for notification purposes. I will delete any post after this. Thanks!

**Comment by alfredoperez** [comment]
+1 web mentions
I will like to add support for parsing Obsidian links.

**Comment by Xuanwo** [comment]
I would like to see the following features:

- i18n support
- native algolia search support

**Comment by DanMossa** [comment]
For those of us that choose to have analytics I think it would be really helpful for there to be some sort of cookie popup asking users to accept

**Comment by chuongmep** [comment]
need support zoom image when click in markdown.

**Comment by iliamrv** [comment]
I use tailwind-nextjs-starter-blog for a long time, thanks a lot for its development. I'd suggest some features which demanded: 

- links to similar articles (based on common tags)
- most popular articles on the front page
- breadcrumbs for articles

**Comment by anuuyu** [comment]
> I've been used tailwind-nextjs-starter-blog for a long time, thanks a lot for its development. I'd suggest some features which demanded:
> 
> * links to similar articles (based on common tags)
> * most popular articles on the front page
> * breadcrumbs for articles
> 
> > * Additional details for tag page (yes!)

**related post based on tags**

**Comment by khyamay** [comment]
any updates on v2?

**Comment by timlrx** [comment]
It's up! Check out https://github.com/timlrx/pliny. I would probably want to settle a few more issues before merging a copy of the template back over here. 

For more information, check out https://github.com/timlrx/tailwind-nextjs-starter-blog/discussions/469

**Comment by 15077693d** [comment]
Could it upgrade to react 18? 
since I would like to use latest react three fiber

**Comment by medkrimi** [comment]
> Could it upgrade to react 18? since I would like to use latest react three fiber

I've upgraded mine to react 18, next 12.3.4 and mdx-bundler to 9, [here is a copy](https://github.com/medkrimi/tailwind-nextjs-starter-blog/tree/typescript-upgrade-react18)

Please feel free to checkout and give it a try.

**Comment by darisi** [comment]
any updates on V2?
