### ISSUE TITLE
Many errors while deploying on vercel.

### ISSUE THREAD

**Issue by animemandir** [timlrx/tailwind-nextjs-starter-blog#283]
I am getting these errors during the build in vercel. I cloned the repo, made a few changes then tried to deploy it on vercel but it doesn't seem to work. Forgive my ignorance If I did a obvious mistake.
![image](https://user-images.githubusercontent.com/78192713/143893742-35b1085a-e50f-488b-9296-448dfc4c21c5.png)

Also, I used these custom cmds - 
![image](https://user-images.githubusercontent.com/78192713/143895014-6fa11a09-8ac5-4bd7-8c92-895f4c84fbf8.png)

Added this in package.json `"prepare": "husky install --unsafe-perm"` which fixed a small error.
But again, the build fails as shown in the 1st log screenshot.

**Comment by animemandir** [comment]
> You should lint your files first - npm run lint.

Alright, I'll use npm, but 1 more question, how does the lint affect the build process in vercel ? I suppose the `npm run lint` can only be run locally and not in vercel right? I'll try testing out the project locally. Thanks again, it's really an amazing project.

**Comment by timlrx** [comment]
It just helps to catch errors. See https://nextjs.org/docs/basic-features/eslint

In this case, it's just a formatting issue so no big deal and running `npm run lint` will auto fix it.

**Comment by animemandir** [comment]
> In this case, it's just a formatting issue so no big deal and running `npm run lint` will auto fix it.

Hmm I tried today , Here's what I got.
![image](https://user-images.githubusercontent.com/78192713/144005558-42857d94-e02b-4f00-965c-e404167fc62b.png)
The mentioned package is present in node_modules, but this error persists. I re-installed all but still the same.

**Comment by timlrx** [comment]
Can you verify that the current template on the master branch works for you, before adding any changes? I am not sure how it works with pnpm as well as any other local changes that you have done. 

There seems to be some issues with nextjs and pnpm - https://github.com/vercel/next.js/issues/16471

**Comment by timlrx** [comment]
Related issue - https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/280

Please fix preact to 10.5.15 as a temporary workaround and the build should work.

**Comment by animemandir** [comment]
> Related issue - #280
> 
> Please fix preact to 10.5.15 as a temporary workaround and the build should work.

Oh ic, Will do that.
Btw, I tired deploying directly to vercel via that link in readme. It worked - https://tailwind-nextjs-starter-blog-tau.vercel.app/
I'll try build with cloned repo with no changes on my local.
will prolly take 10mins.

**Comment by timlrx** [comment]
The reason is the current master branch has a package lock that locks preact to 10.5.15. If you clone it over the past week and tried using another package manager or updating the dependencies, you will run into the error.

**Comment by animemandir** [comment]
> That's because the current master branch has a package lock that locks preact to 10.5.15. If you clone it over the past week and tried using another package manager or updating the dependencies, you will run into the error.

Now I installed preact 10.5.15, it was updated in package.json but not in package-lock.
Should I edit the package-lock manually? will it affect badly?

**Comment by timlrx** [comment]
Good that it works. Please don't wait for any new features - they are all exploratory stage and there's no firm timelines. For thumbnails and different layout, it's best that you implement what you want / like directly. You can probably copy the code from other tailwind templates or websites as well.
