### ISSUE TITLE
Disable dark theme

### ISSUE THREAD

**Issue by gutsytechster** [timlrx/tailwind-nextjs-starter-blog#289]
I'd like to disable the dark theme temporarily. I hid the toggle button to switch the theme. However, the mobile view by default shows the dark theme, where can I configure that?

PS: Thanks for the project. It was an easy-to-use & configurable template.

**Comment by timlrx** [comment]
Thanks, it uses `system` by default so probably your mobile phone is configured to prefer dark theme. In any case, @llovvoll added a new `theme` setting in the config file which you can change to `light` to force it to prefer the light theme instead. You might have to clear your cookies to see the changes.

**Comment by gutsytechster** [comment]
Thank you for the work! I'll test it out, and will close this issue if everything works fine.

**Comment by timlrx** [comment]
All's good? If so, I will close the issue.
