### ISSUE TITLE
Theme switcher and menu icons are slightly vertically misaligned

### ISSUE THREAD

**Issue by AlexanderZeilmann** [timlrx/tailwind-nextjs-starter-blog#294]
**Describe the bug**
Theme switcher and menu item are slightly misaligned.

**To Reproduce**
1. Go to https://tailwind-nextjs-starter-blog.vercel.app/
2. Make the browser window small enough to show the menu icon.

**Expected behavior**
The theme switcher and menu icons should be vertically aligned.

**Screenshots**
Red line added for better visualization.
![misalignment](https://user-images.githubusercontent.com/901391/146162122-32861b83-1fc8-480c-a90d-0cf51dbb7a75.png)

**Browser Info (if display / formatting issue):**
Appears on any browser I tried so far.

**Comment by timlrx** [comment]
Indeed, you are right! Added a slight padding on the menu button to align both buttons.
