### ISSUE TITLE
Change banner img metadata

### ISSUE THREAD

**Issue by fiqryq** [timlrx/tailwind-nextjs-starter-blog#299]
Hello i want to ask how to change banner metadata on index?
banner on index : 
<img width="309" alt="Screen Shot 2021-12-19 at 09 08 59" src="https://user-images.githubusercontent.com/25787603/146661099-1e0a2103-dee5-4698-9305-e131e2cc77a7.png">

banner on other page :
<img width="310" alt="Screen Shot 2021-12-19 at 09 10 37" src="https://user-images.githubusercontent.com/25787603/146661112-8fbb0a2a-55ff-47a6-8490-8bd081a591c8.png">

This my code : 
```js
const siteMetadata = {
  title: 'Fiqry choerudin',
  author: 'Fiqry choerudin',
  headerTitle: '',
  description:
    'I was born in 1999. Being programmer since college in University. working as Frontend Developer. love making open source projects on Github.',
  language: 'en-us',
  siteUrl: 'https://fiqrychoerudin.dev/',
  siteRepo: 'https://github.com/fiqryq/Fiqrychoerudin.dev',
  siteLogo: '/public/static/images/avatar.png',
  image: '/static/images/avatar.png',
  socialBanner: '/static/images/social-banner.png',
  email: 'halo@fiqrychoerudin.dev',
  github: 'https://github.com/fiqryq',
  twitter: 'https://twitter.com/fiqryq_',
  facebook: 'https://facebook.com/fiqryq',
  youtube: 'https://youtube.com',
  linkedin: 'https://www.linkedin.com/fiqrychoerudin',
  locale: 'en-US',
  },
}
```

**Comment by timlrx** [comment]
You can customise the `PageSEO` component - https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/pages/index.js#L21

**Comment by fiqryq** [comment]
i have already customise PageSEO but still same
index page : 
![Screen Shot 2021-12-19 at 18 40 02](https://user-images.githubusercontent.com/25787603/146673780-6eb01b4f-6ac8-46e8-b8c0-4003e52c8ae9.png)
about page :
![Screen Shot 2021-12-19 at 18 39 53](https://user-images.githubusercontent.com/25787603/146673785-fab423c6-247b-4673-9693-1948867ec6b7.png)

it is working in another page but not index

**Comment by timlrx** [comment]
I just checked your site using [twitter post validator](https://cards-dev.twitter.com/validator) and it looks fine:
![image](https://user-images.githubusercontent.com/28362229/146675719-db34cdff-f27f-41a6-aacf-8c78ec3301af.png)

Probably just an old image that was cache. Nice job on the website 👍

**Comment by heyjumanji** [comment]
> You can customise the `PageSEO` component - https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/pages/index.js#L21

What i have to customised to get the blog images embedded?
