### ISSUE TITLE
Text is not contained in the class in the posts view

### ISSUE THREAD

**Issue by typeset-design** [timlrx/tailwind-nextjs-starter-blog#3]
I think its this:

class="prose text-gray-500 max-w-none dark:text-gray-400"

Text  is shown as one line breaking the container. I had a go to fix but only just started with tailwind.

**Comment by timlrx** [comment]
Hi, can you elaborate what the problem is or add a screenshot?

**Comment by typeset-design** [comment]
Hiya, sure,

![Screenshot 2021-02-02 at 17 43 07](https://user-images.githubusercontent.com/76000651/106640696-42723e00-657e-11eb-9715-8593fbabd80c.png)
![Screenshot 2021-02-02 at 17 43 36](https://user-images.githubusercontent.com/76000651/106640707-47cf8880-657e-11eb-80a9-e7cb90400a53.png)


On the 'Latest' pages, the excerpt runs off the page to the right. Once clicked onto the post, its good. 

A really great theme by the way

**Comment by timlrx** [comment]
That's strange... do you see it on https://tailwind-nextjs-starter-blog.vercel.app/ too or only your local version? There's an outer wrapper div which should prevent it from overflowing. If you see it on the sample website as well, can I check what browser are you using?

**Comment by typeset-design** [comment]
Hi, It still does it on the demo site above. I am using safari Version 13.1.1 (15609.2.9.1.2). However I just checked on another mac, and it doesn't do it on their so it must just be my machine. I don't know if some other code is missing, because when you change pages, the header navigation changes position. Also the footer is overlapping. 

Maybe just my machine but it also does this on the iPhone. Thanks for looking at it

**Comment by timlrx** [comment]
Ok, the problem is due to various flex bugs with safari and the fact that it might not support all the flex classes used in the template. As such, it looks different compared to chrome or safari. I tried to fix some of them. Let me know if you still get the same problems. If so, I welcome a pull request to fix the bugs

**Comment by typeset-design** [comment]
It's fixed the navigation issue thanks,
