### ISSUE TITLE
npm install warns about old package-lock.json version

### ISSUE THREAD

**Issue by AlexanderZeilmann** [timlrx/tailwind-nextjs-starter-blog#300]
**Describe the bug**
`npm install` warns about old package-lock.json version

**To Reproduce**
1. Get a fresh copy of `tailwind-nextjs-starter-blog`
2. Run `npm install`
3. The following warning appears:
```
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
```

**Expected behavior**
There should be no warning.

**System Info (if dev / build issue):**
 - Npm version 8.3.0 (current version as of today)

**Additional context**
This bug should be fixable by updating `npm` and running `npm install` again

**Comment by timlrx** [comment]
I am still running node v14.16.1 and npm v.6.14.12, which might still be using the old lockfile format. There's no issue over here, you can delete the lockfile and regenerate a new one based on your preferred node / yarn / npm system. It will work either way.

**Comment by AlexanderZeilmann** [comment]
Yes, I know it is not a big problem 🙂 
My thinking was that this might confuse not as experienced users what is going on. I completely understand if this is a "won't fix".

**Comment by timlrx** [comment]
Will update to the latest version one of these days or even switch to yarn. In the meantime don't worry too much about the warnings :)
