### ISSUE TITLE
$-signs with spacing are rendered as math 

### ISSUE THREAD

**Issue by AlexanderZeilmann** [timlrx/tailwind-nextjs-starter-blog#303]
**Describe the bug**
Despite the documentation, $-signs with spacing are rendered as math.

**To Reproduce**
1. Go to https://tailwind-nextjs-starter-blog.vercel.app/blog/deriving-ols-estimator#user-content-fn-2
2. Scroll down to the footnotes

**Expected behavior**
According to the `data/blog/deriving-ols-estimator.mdx` file:
> The dollar signal displays without issue since only text without space and between two `$` signs are considered as math symbols.[^2]

**Screenshots**
![Bildschirmfoto 2021-12-20 um 21 12 39](https://user-images.githubusercontent.com/901391/146827004-1270e397-15f1-43d8-a76e-d29fe380c674.png)

**Browser Info (if display / formatting issue):**
- Device: any
- Browser: any

**Additional context**
Workaround: Use `&dollar;` instead of `$` if a $-sign should appear.

I have no problems that the $-signs don't show up, as I need math formulas way more often than $-signs.
But is a (documentation?) bug nonetheless.

**Comment by timlrx** [comment]
It's probably due to a recent enhancement - https://github.com/remarkjs/remark-math/issues/63

Another workaround would be to escape the character `\$`. Will update the docs, thanks.
