### ISSUE TITLE
Add security HTTP response headers

### ISSUE THREAD

**Issue by AlexanderZeilmann** [timlrx/tailwind-nextjs-starter-blog#304]
**Is your feature request related to a problem? Please describe.**
[The `tailwind-nextjs-starter-blog` template does not define any security headers currently.](https://securityheaders.com/?q=https%3A%2F%2Ftailwind-nextjs-starter-blog.vercel.app%2F&hide=on&followRedirects=on)

**Describe the solution you'd like**
[Next.js makes it possible to define custom security headers.](https://nextjs.org/docs/advanced-features/security-headers)

The `X-Frame-Options`, `X-Content-Type-Options` and the `Referrer-Policy` headers should be always possible. 
The `Content-Security-Policy` and the `Permissions-Policy` header would also be nice, but it might be necessary for users to change them as they develop their website.
The `Strict-Transport-Security` header is automatically added by Vercel, but other hosters might not include it.

**Describe alternatives you've considered**
For some of the headers there are no alternatives. And even if there were alternatives, including them would be a good idea for a better security.

**Comment by timlrx** [comment]
Yes, this would be a nice addition. I modified a baseline off [Lee Robinson's blog](https://github.com/leerob/leerob.io/blob/af1fc3f3ce168fa351c46076a7a654d97db8f016/next.config.js)

As you mentioned, there would be some hassle involved if someone were to add external services, so we would probably have to add that to the readme, but otherwise I think this is a good start?

The alternative is to add it as a [middleware](https://github.com/leerob/leerob.io/blob/main/pages/_middleware.ts). Have not tried the middleware approach. Do you know whether it applies to static built sites as well? If it does not, then I think the preference would be to modify the config.

```
// You might need to insert additional domains in script-src if you are using external services
const ContentSecurityPolicy = `
  default-src 'self';
  script-src 'self' 'unsafe-eval' 'unsafe-inline';
  style-src 'self' 'unsafe-inline' *.googleapis.com;
  img-src * blob: data:;
  media-src 'none';
  connect-src *;
  font-src 'self' 'fonts.gstatic.com';
`;

const securityHeaders = [
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
  {
    key: 'Content-Security-Policy',
    value: ContentSecurityPolicy.replace(/\n/g, '')
  },
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
  {
    key: 'Referrer-Policy',
    value: 'strict-origin-when-cross-origin'
  },
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
  {
    key: 'X-Frame-Options',
    value: 'DENY'
  },
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
  {
    key: 'X-Content-Type-Options',
    value: 'nosniff'
  },
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-DNS-Prefetch-Control
  {
    key: 'X-DNS-Prefetch-Control',
    value: 'on'
  },
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
  {
    key: 'Strict-Transport-Security',
    value: 'max-age=31536000; includeSubDomains; preload'
  },
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy
  {
    key: 'Permissions-Policy',
    value: 'camera=(), microphone=(), geolocation=()'
  }
];
```

**Comment by AlexanderZeilmann** [comment]
The headers look good! I also have no experience with middleware in Next.js. My preference would be to put the headers in the `next.config.js` file, too.

Two minor comments:
1. We need to add `cdn.jsdelivr.net` to `style-src` and `font-src` to load the CSS files and fonts for katex.
2. The `'fonts.gstatic.com'` in `font-src` should not be in quotes.


I also had a look, whether we really need the `unsafe-eval` and `unsafe-inline` directives in the CSP. Answer: Sadly yes.
* Next.js is using `Function` which would be blocked by `script-src 'unsafe-eval'`
* `next-themes` requires `script-src 'unsafe-inline'`
* `next-image` is using inline styling meaning we need `style-src 'unsafe-inline'` (`data/logo.svg` also uses inlines styles, but this could be changed without problems.)

**Comment by gillisandrew** [comment]
You shouldn't  be setting the HSTS header to `max-age=31536000; includeSubDomains; preload` by default. Non-https websites on subdomains could be impacted and removing a domain from the HSTS preload list takes well over a month.

Set it to a safer value e.g. `max-age=604800` and keep the current value commented out with a note about the impact of enabling it.

**Comment by timlrx** [comment]
Thanks for bringing this up. I think the best way to do it would be to keep the `max-age` and `includeSubDomains` but exclude `preload` by default.
 
To quote [HSTS preload org](https://hstspreload.org/):
> If you maintain a project that provides HTTPS configuration advice or provides an option to enable HSTS, do not include the preload directive by default. We get regular emails from site operators who tried out HSTS this way, only to find themselves on the preload list by the time they find they need to remove HSTS to access certain subdomains. [Removal](https://hstspreload.org/#removal) tends to be slow and painful for those sites.

Without the preload option ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security)):
>Should it be necessary to disable Strict Transport Security, setting the max-age to 0 (over an https connection) will immediately expire the Strict-Transport-Security header, allowing access via http.
