### ISSUE TITLE
Optional Project Images

### ISSUE THREAD

**Issue by lanbau** [timlrx/tailwind-nextjs-starter-blog#312]
**Is your feature request related to a problem? Please describe.**
Sometimes, we don't have images for a project. Leaving out imgSrc breaks the project.

**Describe the solution you'd like**
Make images for projects optional.

**Describe alternatives you've considered**
N.A

**Additional context**
N.A

**Comment by timlrx** [comment]
Happy to accept a PR, I believe you have already implemented it in your blog :)

**Comment by lanbau** [comment]
Here you go https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/314
