### ISSUE TITLE
Bug in switching between light dark mode

### ISSUE THREAD

**Issue by Hartha-aloufi** [timlrx/tailwind-nextjs-starter-blog#317]
**Describe the bug**
If the default theme set to "dark" then the dark theme will be shown after refreshing the page in any case, Even if I changed it to light theme by clicking switching button in the header. 

**To Reproduce**
1. Go to 'siteMetadata.js' file
2. Set `theme` to "dark"
3. Go to the site and switch it to light
4. Refresh the page
5. You will see the dark theme!

**Screenshots**
![bug](https://user-images.githubusercontent.com/15910965/147709196-0615fc38-2f12-4708-806a-a3a6222de7e3.png)

**Additional context**
I checked localStorage `theme` value, it is "light".

**Comment by timlrx** [comment]
Yes, that's the right behaviour, sorry if the readme is not clear. It's a result of #289 where a user wants a fixed theme irrespective of the user preference. To respect the user's preference, use `system`.

**Comment by Hartha-aloufi** [comment]
Thanks for the clarification

**Comment by llovvoll** [comment]
> Yes, that's the right behaviour, sorry if the readme is not clear. It's a result of #289 where a user wants a fixed theme irrespective of the user preference. To respect the user's preference, use `system`.

Maybe we can change to show theme switch button when siteMetadata.theme is "system"
