### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by haafidz-jp** [timlrx/tailwind-nextjs-starter-blog#318]
how can i change default dark mode color? i wanna change to bg-gray-900 like previous version.

**Comment by timlrx** [comment]
As in change the background color of the dark mode? It's in this line: https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/pages/_document.js#L37

It is already set to `bg-gray-900`. If you just want to change the gray palette, you can change this line: https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/tailwind.config.js#L23

**Comment by aloisdg** [comment]
Look into tailwind's config.

**Comment by haafidz-jp** [comment]
Alright thank you very much 🙏🙏
