### ISSUE TITLE
Disqus issue with security rules

### ISSUE THREAD

**Issue by MiltonAkash** [timlrx/tailwind-nextjs-starter-blog#319]
**Describe the bug**
![image](https://user-images.githubusercontent.com/21121073/147867125-44893583-9043-4f9a-9ff9-4d10773f3315.png)

Getting this error. Also Disqus not loading. Changed CSF from giscus.app to *.disqus.com in two places. 

**Screenshots**
![image](https://user-images.githubusercontent.com/21121073/147867142-c9880875-c77f-4576-9ccb-b468f8845a18.png)

Disqus loads only in the trusted domain and even in that this issue is there. Removing header as a whole brings CORS issue.

**Comment by timlrx** [comment]
1) As hinted by the error message, you would probably have to add `www.googletagmanager.com`  and `www.google-analytics.com` if you are using google analytics

2) Maybe you can take a look at this [post](https://csplite.com/csp/test66/) on how to configure the required CSP for disqus. There should be an error message if something is blocked by CSP. If removing the security issues, does not solve the issue, then I think there's something wrong with the setup and config.

**Comment by sreeram-venkitesh** [comment]
I was facing the same issue and for some reason I had to add `script-src 'self' 'unsafe-eval' 'unsafe-inline' *.googletagmanager.com *.google-analytics.com;` before the line about giscus in `ContentSecurityPolicy` for it to work. Like so

```
 `...
  script-src 'self' 'unsafe-eval' 'unsafe-inline' *.googletagmanager.com *.google-analytics.com;
  script-src 'self' 'unsafe-eval' 'unsafe-inline' giscus.app;
  ...
 `
```

Unlike @MiltonAkash giscus was working for me initially, but the Google analytics ID was not being loaded from the environment variables I had mentioned in Vercel. No idea why.

**Comment by timlrx** [comment]
It is consistent. He was talking about `disqus` not `giscus`. Yes, you have to manually opt-in and whitelist the services you are using. The template does not automatically deduce what external services you have configured. You could remove the CSP part and the site will work without issues as well. It's just that CSP is now a recommended best practice and I decided to include it for all sites. For more information - https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by sreeram-venkitesh** [comment]
Ah, my bad! Thanks for clearing it up!

**Comment by umarabdul-malik** [comment]
Hello,
I am getting this error when I try to use Adsense. Is anyone available to assist? Thank you
![image](https://user-images.githubusercontent.com/103819207/205927776-a31caf25-42e3-429a-8e7a-8d5ec039ce3f.png)

**Comment by sreeram-venkitesh** [comment]
@umarabdul-malik Did you try the following from my comment above?
> I was facing the same issue and for some reason I had to add `script-src 'self' 'unsafe-eval' 'unsafe-inline' *.googletagmanager.com *.google-analytics.com;` before the line about giscus in `ContentSecurityPolicy` for it to work. Like so
> 
> ```
>  `...
>   script-src 'self' 'unsafe-eval' 'unsafe-inline' *.googletagmanager.com *.google-analytics.com;
>   script-src 'self' 'unsafe-eval' 'unsafe-inline' giscus.app;
>   ...
>  `
> ```
> 
> Unlike @MiltonAkash giscus was working for me initially, but the Google analytics ID was not being loaded from the environment variables I had mentioned in Vercel. No idea why. Added this to the app and now it is working.

**Comment by umarabdul-malik** [comment]
@sreeram-venkitesh, I've added but still facing the same issues here.
