### ISSUE TITLE
Table header getting almost invisble in dark mode

### ISSUE THREAD

**Issue by MiltonAkash** [timlrx/tailwind-nextjs-starter-blog#323]
![image](https://user-images.githubusercontent.com/21121073/148004616-045041c3-132f-4293-ae39-737978107bd5.png)

**Comment by MiltonAkash** [comment]
th{
@apply dark:text-gray-100;
} 

will fix this

**Comment by timlrx** [comment]
Thanks, pushed the fix to `tailwind.config.js` instead.
