### ISSUE TITLE
Typographical Error

### ISSUE THREAD

**Issue by dephraiim** [timlrx/tailwind-nextjs-starter-blog#336]
The spelling of `License` in the readme is incorrect. If it can be corrected.

**Comment by llovvoll** [comment]
> The spelling of `License` in the readme is incorrect. If it can be corrected.

Most projects usually use uppercase "LICENSE", so i think not have any problem

https://github.com/nodejs/node/blob/master/LICENSE
https://github.com/microsoft/vscode/blob/main/LICENSE.txt
https://github.com/freeCodeCamp/freeCodeCamp/blob/main/LICENSE.md

**Comment by timlrx** [comment]
British spelling.
