### ISSUE TITLE
Font size should be responsive wrt device text size configuration

### ISSUE THREAD

**Issue by timlrx** [timlrx/tailwind-nextjs-starter-blog#340]
From @MiltonArkash:

>The current version is not respecting the device's text size configurations. I have set VERY LARGE in my mobile and many other sites adjust text like this but this template doesn't adjust for it. Hard to read the small text

**Comment by aloisdg** [comment]
What is _wrt_? Looking online yield _With Respect To_, _With Reference To_, _With Regard To_. I guess both are ok in this context. WRT can also be _Web Runtime_ or even _World Rally Team_.

**Comment by timlrx** [comment]
With Respect To.

**Comment by timlrx** [comment]
Hmm could not find what's wrong with this. It works when I change the font size for my desktop but not for my android chrome browser. If anyone knows what is the issue, would appreciate a PR, thanks!

**Comment by christiaanNagel** [comment]
> Hmm could not find what's wrong with this. It works when I change the font size for my desktop but not for my android chrome browser. If anyone knows what is the issue, would appreciate a PR, thanks!

```javascript
import Head from "next/head";
<Head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
</Head>
```

[link to forum discussion](https://www.reddit.com/r/tailwindcss/comments/kj146o/i_am_struggling_with_tailwinds_responsive_design/)
