### ISSUE TITLE
`hover` for the <a> on the MDX blog's page does not work when used markdown syntax for that link.

### ISSUE THREAD

**Issue by rsipakov** [timlrx/tailwind-nextjs-starter-blog#342]
In the `tailwind.config.js` specified custom `<a>` with `hover`, but `hover` does not work with MDX (on blog's page) when used markdown syntax for that link.

```js
// tailwind.config.js

color: theme('colors.gray.700'),
            a: {
              color: theme('colors.primary.500'),
              '&:hover': {
                color: theme('colors.primary.600'),
              },
              code: { color: theme('colors.primary.400') },
            },
```

https://user-images.githubusercontent.com/34224178/149857587-cdafcf4c-0fea-47b6-92a0-30ee9bb468c0.mp4

**Comment by timlrx** [comment]
It's a bug in tailwind 3.0. See https://github.com/tailwindlabs/tailwindcss-typography/issues/231

**Comment by rsipakov** [comment]
Thank you! Like this `prose-a:hover:text-[#BAE3FF]` work for me.
