### ISSUE TITLE
Blog post with draft true not working

### ISSUE THREAD

**Issue by jesielviana** [timlrx/tailwind-nextjs-starter-blog#348]
When blog post set draft: true, build not working. 
Show this error: TypeError: Cannot read properties of undefined (reading 'date')

**To Reproduce**
1. Set blog post `drat: true`
2. Run build
3. See log error

**Expected behavior**
Build not work, see log: TypeError: Cannot read properties of undefined (reading 'date')

**System Info (if dev / build issue):**
 - OS: Mac OS 12.1
 - Node version: 16.13.0
 - Npm version: 8.1.0

**Comment by timlrx** [comment]
I am unable to replicate the bug. Are you on an older version? Maybe the fix over here will help - https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/288

**Comment by jesielviana** [comment]
I am using  version 1.1.2. Forked from https://github.com/GautierArcin/i18n-tailwind-nextjs-starter-blog/tree/demo/next-translate

**Comment by timlrx** [comment]
Yes, the branch has not been updated for some time and this bug has since been patched. You can copy the fix over [here](https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/293/files) and apply them to your site

**Comment by jesielviana** [comment]
I update and worked very well, thanks Timothy.
