### ISSUE TITLE
Make 'draft' front matter field as optional implicitly

### ISSUE THREAD

**Issue by eunsukimme** [timlrx/tailwind-nextjs-starter-blog#349]
**Is your feature request related to a problem? Please describe.**
When I was migrating my blog posts from Gatsby, I noticed that posts which are 'draft' front matter field is not exist are not included on blog page. To include the posts on blog page, I had to add 'dratf' field and set the value as false. 

**Describe the solution you'd like**
What do you think about making 'draft' field as optional implicitly? Then, we don't need to add 'draft' field and set it's value as false explicitly.

Thank you!

**Comment by timlrx** [comment]
I think it is already set over [here](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/scripts/compose.js#L39)? Or let me know how you think we can make it more explicit.

**Comment by eunsukimme** [comment]
Sorry, I'm not specified the environment I'm running this repo. I'm using typescript version of this repo, so it might be problematic on typescript version only.

So I mean, when Next.js build pages, `getAllFilesFrontMatter` function is called in getStaticPaths and getStaticProps funcition. And it filters only posts which have 'draft' field in frontmatter and have it's value as `true` becuase of [this line](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/954dda9c3bfb2812f73dccad53bdb62476f26e38/lib/mdx.ts#L130).

Thus, posts not having 'draft' field in frontmatter are not included the result of `getAllFilesFrontMatter`. As a result, they are not exist final build output.

**Comment by timlrx** [comment]
Oh sorry, I misunderstood the question. Yes, that behaviour is the same for both the js and typescript versions. We don't publish draft posts. [Hugo](https://gohugo.io/getting-started/usage/#draft-future-and-expired-content) works the same way as well. 

If you want to publish draft posts, feel free to make the changes on your end - that's the benefit of building on top of nextjs, the user can configure all these details if he so wishes.
