### ISSUE TITLE
Unable to preview drafts

### ISSUE THREAD

**Issue by supermacro** [timlrx/tailwind-nextjs-starter-blog#350]
Hello, not sure if a "bug" per-se, but I do not see how to preview a `draft: true` post locally (or within, say, a staging environment). 

How would you recommend going about this?

**Comment by timlrx** [comment]
You could modify this [line](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/pages/blog/%5B...slug%5D.js#L48) to render the post all the time in dev and only in prod if draft !== true
