### ISSUE TITLE
Google Tag manager violates Content Security Policy directive 

### ISSUE THREAD

**Issue by ezzcodeezzlife** [timlrx/tailwind-nextjs-starter-blog#353]
**Describe the bug**

After adding the analytics.googleAnalyticsId I get the following error:

Refused to load the script 'https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXX' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'unsafe-inline' giscus.app". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**To Reproduce**
clone, install, add googleAnalyticsId and deploy to Vercel

Default ContentSecurityPolicy from next.config.js:

```
const ContentSecurityPolicy = `
  default-src 'self';
  img-src * blob: data:;
  style-src 'self' 'unsafe-inline' *.googleapis.com cdn.jsdelivr.net;
  script-src 'self' 'unsafe-eval' 'unsafe-inline' giscus.app;
  media-src 'none';
  connect-src *;
  font-src 'self' fonts.gstatic.com cdn.jsdelivr.net;
`
```

How can i fix it?

**Comment by AlexanderZeilmann** [comment]
See here: https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/319

**Comment by ezzcodeezzlife** [comment]
Ah, my bad! Thanks for clearing it up!
