### ISSUE TITLE
Add Reading Time On the blog posts

### ISSUE THREAD

**Issue by miladezzat** [timlrx/tailwind-nextjs-starter-blog#361]
Hello Mr @timlrx 
What about if we add a reading time for the blog posts?
![image](https://user-images.githubusercontent.com/27713902/151659799-b1cd15a6-4bad-48a1-81f6-864482c01be4.png)

I can add this feature.

**Comment by TszHong0411** [comment]
> 
This project already has this function

Go 'layouts\PostLayout.js' and add readingTime

```js
const { slug, fileName, date, title, tags, readingTime } = frontMatter
```

Usage:

```js
// words
<h3>{readingTime.words} words</h3>
// reading time
<h3>{readingTime.text}</h3>

// output
// 80 words
// 4 min read
```

**Comment by timlrx** [comment]
Not sure where the previous post went but as a user mentioned:

> This project already has this function
> 
> Go 'layouts\PostLayout.js' and add readingTime
> 
> const { slug, fileName, date, title, tags, readingTime } = frontMatter
> Usage:
> 
> // words
> <h3>{readingTime.words} words</h3>
> // reading time
> <h3>{readingTime.text}</h3>
> 
> // output
> // 80 words
> // 4 min read

**Comment by TszHong0411** [comment]
> 

That is me. 😄

**Comment by miladezzat** [comment]
Okay thanks

**Comment by dushyanth31** [comment]
Hey  Guys,

I just wondering on how to add this to my blog post? How to?

**Comment by stepcellwolf** [comment]
I'm also looking for this, how to enable it? Anyone could help?
