### ISSUE TITLE
Add open graph and socail media graph

### ISSUE THREAD

**Issue by miladezzat** [timlrx/tailwind-nextjs-starter-blog#375]
What about if I want to add custom dynamic meta tags for SEO like: 
`open graph`, Facebook, and so on?

to view my blog post as like:  when I share it on LinkedIn or any social media
![image](https://user-images.githubusercontent.com/27713902/152647272-017b0a4e-9681-493c-a9ae-0f4d0fd750f8.png)

**Comment by miladezzat** [comment]
@timlrx

**Comment by timlrx** [comment]
Tagging me 40mins after the first post lowers the probability of a helpful reply...

The template automatically gets all the properties set in the front matter of the blog and use it to generate the SEO headers, including open graph. What is the issue that you are facing? What have you tried? Have you taken a look at how [props from the layout template](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/layouts/PostLayout.js#L24-L28) gets passed to the [SEO component](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/components/SEO.js)?

**Comment by miladezzat** [comment]
Thanks for your response
