### ISSUE TITLE
small Refactoring of  `bundleMDX` in `mdx.js`

### ISSUE THREAD

**Issue by Sfitzg** [timlrx/tailwind-nextjs-starter-blog#378]
**Describe the Refactor**

I noticed a small section of code which I think could be refactored.

Just before the use of `bundleMDX` inside the `mdx.js` file the frontmatter is being parsed from graymatter with comment that it is needed this way to be able to pass the frontmatter as options to rehype plugin.

firstly I think that the file has been refactored before since the frontmatter is no longer being used in any of the plugins.
but secondly `xdmOptions` actually has its own frontmatter parameter built in as mdx-bundler already uses graymatter
therefore I think that the code can be refactored to use the internal frontmatter variable rather, removing 2 lines of code and making it a little bit cleaner in my view. 

```diff
-// Parsing frontmatter here to pass it in as options to rehype plugin
-const { data: frontmatter } = matter(source) 

- const { code } = await bundleMDX({
+ const { code, frontmatter } = await bundleMDX({  
 source,
    // mdx imports can be automatically source from the components directory
    cwd: path.join(root, 'components'),
-    xdmOptions(options) {
+    xdmOptions(options, frontmatter) { 
     // this is the recommended way to add custom remark/rehype plugins:
      // The syntax might look weird, but it protects you in case we add/remove
      // plugins in the future.
      options.remarkPlugins = [
        ...(options.remarkPlugins ?? []),
        remarkExtractFrontmatter,
        [remarkTocHeadings, { exportRef: toc }],
        remarkGfm,
        remarkCodeTitles,
        [remarkFootnotes, { inlineNotes: true }],
        remarkMath,
        remarkImgToJsx,
      ]
      options.rehypePlugins = [
        ...(options.rehypePlugins ?? []),
        rehypeSlug,
        rehypeAutolinkHeadings,
        rehypeKatex,
        [rehypeCitation, { path: path.join(root, 'data') }],
        [rehypePrismPlus, { ignoreMissing: true }],
        rehypePresetMinify,
      ]
      return options
    },
    esbuildOptions: (options) => {
      options.loader = {
        ...options.loader,
        '.js': 'jsx',
      }
      return options
    },
  })
**Additional context**
Add any other context about the problem here.

**Comment by timlrx** [comment]
Yes, that is right. Previously it was done this way but I had to extract the frontmatter out to pass it to one of the plugins. Now that the side effect has been clean up, we can revert to this more simplified code.
