### ISSUE TITLE
Error with tailwind.css

### ISSUE THREAD

**Issue by designingSparks** [timlrx/tailwind-nextjs-starter-blog#40]
I'm getting the following error message:
error - ./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[2].oneOf[6].use[1]!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[2].oneOf[6].use[2]!./css/tailwind.css
TypeError: Object.fromEntries is not a function

**Comment by timlrx** [comment]
Hmm ... is your code hosted somewhere where I could take a look? Or do you have a replicable example? Hard to help without more information

**Comment by designingSparks** [comment]
I'm running locally on a mac. Steps to reproduce:
>>npx degit https://github.com/timlrx/tailwind-nextjs-starter-blog.git
>>npm install
>>npm start

**Comment by timlrx** [comment]
What's your node version? Tailwind 2.0 requires node 12+

Might be similar to this issue: https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/30

**Comment by designingSparks** [comment]
It compiles now after upgrading node. But attempting to view http://localhost:3000 doesn't respond.

**Comment by timlrx** [comment]
Are you connecting to some virtual machine / container? If so, you might need to configure your network settings to get it to work. Otherwise, does the [basic next.js starter](https://github.com/vercel/next-learn-starter/tree/master/demo) run for you?

**Comment by designingSparks** [comment]
Yes, the basic next.js start runs. Has this repo been tested fully on mac os? I suspect there may be some small tweaks required or dependencies needed.

**Comment by designingSparks** [comment]
I can confirm this is working now. Thanks for sharing this repo!

**Comment by DoctorDerek** [comment]
Nice 👍 (Windows WSL / Ubuntu 18)

**Comment by designingSparks** [comment]
In the end it turned out just to be the node version.
