### ISSUE TITLE
How to customize this theme.

### ISSUE THREAD

**Issue by 0xShakhawat** [timlrx/tailwind-nextjs-starter-blog#401]
I love Minimal Blog Themes like these. 
I deployed this theme on Vercel and now, How can I customize this theme? 
Which CMS is better for this theme?

"I do not have a computer. But I can edit codes from GitHub"
'sorry for my English'

**Comment by timlrx** [comment]
Hi, I would not recommend this template for your use case. There's no external CMS support and it's meant for someone to edit and customize using an IDE.

**Comment by 0xShakhawat** [comment]
> Hi, I would not recommend this template for your use case. There's no external CMS support and it's meant for someone to edit and customize using an IDE.

https://blog.shakhawat.me . I've completed my blog customization. I've posted a blog. **That is not responsive**. You can check in my blog.
