### ISSUE TITLE
Add PWA by default?

### ISSUE THREAD

**Issue by yuxxeun** [timlrx/tailwind-nextjs-starter-blog#409]
supports PWA by default to make it easier to access, because I think people will prefer to press our website logo in the their device instead of typing in the url bar

**Comment by onegrit** [comment]
Yeah! This will be awesome feature!

**Comment by AlexanderZeilmann** [comment]
There has been a pull request for this [here](https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/332). The pull requests works as is, so you can apply it to your own blog.

The general consensus was, however, to not make this the default.

**Comment by yuxxeun** [comment]
> There has been a pull request for this [here](https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/332). The pull requests works as is, so you can apply it to your own blog.
> 
> The general consensus was, however, to not make this the default.

Ok i get it, thank you for your feedback.
