### ISSUE TITLE
Build fails on Windows but works on WSL

### ISSUE THREAD

**Issue by PWSys** [timlrx/tailwind-nextjs-starter-blog#41]
Running on Windows 10 `npm run build` fails with the output below: 

>10 silly lifecycle tailwind-nextjs-starter-blog@0.3.1 buildArgs: [ /d /s /c', 'next build && node ./scripts/generate-sitemap]
>11silly lifecycle tailwind-nextjs-starter-blog@0.3.1 build: Returned: code: 1  signal: null
>12 info lifecycle tailwind-nextjs-starter-blog@0.3.1~build: Failed to exec build script
>13 verbose stack Error: tailwind-nextjs-starter-blog@0.3.1 build: `next build && node ./scripts/generate-sitemap`
>13 verbose stack Exit status 1
>13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
>13 verbose stack     at EventEmitter.emit (events.js:315:20)
>13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
>13 verbose stack     at ChildProcess.emit (events.js:315:20)
>13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
>13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
>14 verbose pkgid tailwind-nextjs-starter-blog@0.3.1
>15 verbose cwd C:\Users\PWSys\Documents\Projects\nexts_va_v07\nextjs_va_07
>16 verbose Windows_NT 10.0.19042
>17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
>18 verbose node v14.16.1
>19 verbose npm  v6.14.12
>20 error code ELIFECYCLE
>21 error errno 1
>22 error tailwind-nextjs-starter-blog@0.3.1 build: `next build && node ./scripts/generate-sitemap`
>22 error Exit status 1
>23 error Failed at the tailwind-nextjs-starter-blog@0.3.1 build script.
>23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

Steps to reproduce
`npm install`
`npm run build`

This works in Linux.  Using the same directory through WSL V2, `npm run build` works without issue.  Any suggestions for why this may be failing on Windows?
Thanks!

**Comment by DoctorDerek** [comment]
Hey it's probably a npm / node version issue, I think some of the
dependencies require newer npm (like husky needing npm 7 or something
wacky). Mine sharing your `npm -v` and `node -v` output?

I'm on Windows 10x64 and don't have a successful build on `master` branch
either, but it's definitely a different stacktrace:
```

C:\dev
λ cd tailwind-nextjs-starter-blog\

C:\dev\tailwind-nextjs-starter-blog (master -> origin)
λ npm -v
7.11.2

C:\dev\tailwind-nextjs-starter-blog (master -> origin)
λ node -v
v15.14.0

C:\dev\tailwind-nextjs-starter-blog (master -> origin)
λ npm run build

> ***@***.*** build
> next build && node ./scripts/generate-sitemap

'next' is not recognized as an internal or external command,
operable program or batch file.

C:\dev\tailwind-nextjs-starter-blog (master -> origin)
λ npm install

> ***@***.*** prepare
> husky install

husky - Git hooks installed

added 958 packages, and audited 959 packages in 11s

7 vulnerabilities (1 moderate, 6 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

C:\dev\tailwind-nextjs-starter-blog (master -> origin)
λ npm run build

> ***@***.*** build
> next build && node ./scripts/generate-sitemap

info  - Using webpack 5. Reason: future.webpack5 option enabled
https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types

warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking
changes, and can change at any time.
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data

> Build error occurred
TypeError: Cannot read property 'page' of undefined
    at
C:\dev\tailwind-nextjs-starter-blog\node_modules\next\dist\export\index.js:24:30
    at Array.filter (<anonymous>)
    at
C:\dev\tailwind-nextjs-starter-blog\node_modules\next\dist\export\index.js:23:194
    at async Span.traceAsyncFn
(C:\dev\tailwind-nextjs-starter-blog\node_modules\next\dist\telemetry\trace\trace.js:6:584)
    at async
C:\dev\tailwind-nextjs-starter-blog\node_modules\next\dist\build\index.js:43:49
    at async Span.traceAsyncFn
(C:\dev\tailwind-nextjs-starter-blog\node_modules\next\dist\telemetry\trace\trace.js:6:584)
    at async
C:\dev\tailwind-nextjs-starter-blog\node_modules\next\dist\build\index.js:25:1475
    at async Span.traceAsyncFn
(C:\dev\tailwind-nextjs-starter-blog\node_modules\next\dist\telemetry\trace\trace.js:6:584)

C:\dev\tailwind-nextjs-starter-blog (master -> origin)
λ
```

>

**Comment by DoctorDerek** [comment]
@abstractvector Helped me sleuth out that this doesn't seem to be a reported Next.js issue, so it must be something for this project. (Thanks Matt!)

```
λ npm run build

> what-are-your-values@0.1.0 build
> next build

info  - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5 info  - Checking validity of types
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
info  - Generating static pages (3/3)
info  - Finalizing page optimization

Page                                Size     First Load JS
┌ ○ /                               7.37 kB        71.4 kB
├   └ css/48fe4f0a1886e63f0800.css  675 B
├   /_app                           0 B            64.1 kB
├ ○ /404                            3.68 kB        67.7 kB
└ λ /api/hello                      0 B            64.1 kB
+ First Load JS shared by all       64.1 kB
  ├ chunks/597.792d30.js            13.2 kB
  ├ chunks/778.98c823.js            7.11 kB
  ├ chunks/framework.bcc415.js      42 kB
  ├ chunks/main.9ca82e.js           151 B
  ├ chunks/pages/_app.017c26.js     565 B
  ├ chunks/webpack.a2d1e7.js        993 B
  └ css/9555fbe4118c83c59ab9.css    203 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
```

A `npx next-app` project works fine for me on Windows 10 (`npm run build`).

**Comment by PWSys** [comment]
I can also confirm that other next 10.2 projects build fine on Windowsx64.

**Comment by DoctorDerek** [comment]
Yep it does seem project specific, but I have no idea where it would be
coming from.

**Comment by timlrx** [comment]
That's the cause of the failed build. Have fix it and verified that it builds for Windows.

**Comment by PWSys** [comment]
Thanks @timlrx !
