### ISSUE TITLE
Just thought would be cool to add twin.macro features to this great template work

### ISSUE THREAD

**Issue by NetLancer** [timlrx/tailwind-nextjs-starter-blog#419]
I've been looking for this type of feature to eventually make use of things like: Styled-components & TailwindCss simultaneously and make code more concise, uncluttered and more pleasing to an eye. 
Here's an example: github.com/ben-rogerson/twin.examples/tree/master/next-stitches-typescript which i think i like most. 

Many thanx for this awesome template work :)

**Comment by timlrx** [comment]
Hi @NetLancer, thanks for the nice words :) 

I can understand the appeal of twin macro, but I would probably be sticking with tailwindCSS for this project. There are under efforts current under way to reduce the boiler plate and make things less cluttered in terms of the overall code base and maintenance overhead.

**Comment by NetLancer** [comment]
Yeah, many thanks
