### ISSUE TITLE
Contentlayer postbuild error

### ISSUE THREAD

**Issue by aozaki-kuro** [timlrx/tailwind-nextjs-starter-blog#426]
**Describe the bug**
After trying out the latest contentlayer branch, I bumped into some problems when trying to run the postbuild script.
![image](https://user-images.githubusercontent.com/28428951/160042885-4f0a965d-8b26-4372-a452-21d7a5b97106.png)

**To Reproduce**
1. Pull the repo and switch to contentlayer branch
2. `npm install`
3. `npm run build`

**Expected behavior**
Successfully run the postbuild script.

**System Info (if dev / build issue):**
 - OS: macOS Monterey 12.3 (ARM64)
 - Node version v16.14.2
 - npm version 8.5.2 / pnpm version 6.32.3

**Comment by timlrx** [comment]
Filed as a bug report over here: https://github.com/contentlayerdev/contentlayer/issues/153

As a workaround, use node < 16.14.0 or I might have to investigate in other solutions to make it compatible across node versions >=14

**Comment by aozaki-kuro** [comment]
Seemed like the problem was solved in `0.2.1` but I have no idea how to modify it since it was a breaking change 🥲
Waiting for the update~

**Comment by timlrx** [comment]
It has been updated: https://github.com/timlrx/tailwind-nextjs-starter-blog/tree/contentlayer

**Comment by aozaki-kuro** [comment]
Confirm fixed! Thank you ✌️
