### ISSUE TITLE
Giscus data-mapping property bug

### ISSUE THREAD

**Issue by karanpratapsingh** [timlrx/tailwind-nextjs-starter-blog#437]
**Describe the bug**

**To Reproduce**

Try changing the giscus properties for mapping, it's still using the `pathname`

```
-      mapping: 'pathname', // supported options: pathname, url, title
+      mapping: 'title', // supported options: pathname, url, title
```

**Expected behavior**

Looks like we don't need to compute title/href in switch in `Comments` component located at `components/comments` and pass it as text. This is becuase `giscus.js` picks it automatically. Seems like it's an enum not a string property.

```
-    script.setAttribute('data-mapping', mapping);
+    script.setAttribute('data-mapping', siteMetadata.comment.giscusConfig.mapping);
```

**Comment by timlrx** [comment]
Thanks, I have pushed a fix. Strange it went unnoticed for so long but it always fell back to the `pathname` default and appeared to be working.
