### ISSUE TITLE
Using swr inside postlayout component

### ISSUE THREAD

**Issue by SennR-1952135** [timlrx/tailwind-nextjs-starter-blog#447]
After adding an SWR data fetch to PostLayout component it crashes, if I comment it out it works fine. I get the following error when trying to fetch data with swr within PostLayout.

```code
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
![image](https://user-images.githubusercontent.com/71635860/165996808-0317d530-2d00-421d-92fa-27712368962b.png)
image of the error

I am using the latest typescript main branch

This is the component I am trying to add within postlayout

```javascript
import { useEffect } from 'react'
import useSWR from 'swr'

const fetcher = (url) => fetch(url).then((r) => r.json())

export default function ViewCounter({
  slug,
  addView = false,
}: {
  slug: string
  addView?: boolean
}) {
  const { data } = useSWR(`/api/views/${slug}`, fetcher)
  // const viewCount = new Number(data?.total)

  useEffect(() => {
    console.log('ViewCounter useEffect', slug, addView)
    const registerView = () =>
      fetch(`/api/views/${slug}`, {
        method: 'POST',
      })

    if (addView) {
      registerView()
    }

  }, [slug])

  // return `${viewCount > 0 ? viewCount.toLocaleString() : '–––'} views`
  return (
    <span className="flex items-center gap-1">
      {data && data?.total}
    </span>
  )
}
```
The full codebase, for reproduction, can be found here: https://github.com/SennR-1952135/sennr
To reproduce the error in my codebase make sure to go within the ViewCounter.tsx component and to uncomment the following line: ```const { data } = useSWR(`/api/views/${slug}`, fetcher)```.

If you simply want to reproduce the error in your own blog/codebase, use SWR to fetch any sort of data inside the PostLayout component.

**Comment by SennR-1952135** [comment]
Im new to nextjs, may it be due to static generation of blog posts? Can someone please help me or give me some guidelines? Or an alternative solution to using swr, on how to load api data?

**Comment by timlrx** [comment]
There's a related issue over here - https://github.com/timlrx/tailwind-nextjs-starter-blog/discussions/385. Try fixing it to `v1.1.2` and see if that works for you?

**Comment by SennR-1952135** [comment]
Changing the version of swr to `v1.1.2` successfully solved the issue, thanks for helping me!
