### ISSUE TITLE
Feature image in list of blog posts

### ISSUE THREAD

**Issue by SebDanielsson** [timlrx/tailwind-nextjs-starter-blog#45]
It would be great if you could pick a hero image for each blog post that could be shown to the left of the Title where thers is currently a lot of dead space.

**Comment by timlrx** [comment]
That would be fairly easy to implement as each blog posts already accepts at `images` property in the frontmatter. You would just need to modify `ListLayout.js` to render the images in the post preview. 

I don't plan on changing the default layout but by all means, use it as a starting point and customize it to your liking!
