### ISSUE TITLE
Hosting Tailwind NextJS stater blog on subpath /blog route

### ISSUE THREAD

**Issue by QuentinDela** [timlrx/tailwind-nextjs-starter-blog#451]
Hello,

I am trying to host this blog as static with `next export static` on a Cloudfront Distribution on the '/blog' path.  
as I have already a React website hosted on https://website.com.  
I have an issue with the NextJS configuration to deliver the blog on a subpath.  
I have tried to set `baseUrl: '/blog'` but it seems not to work, there are still some requests made to root.  
What would be the best way to use the baseUrl parameter from here ?

**Comment by jessycormier** [comment]
Hello [QuentinDela](https://github.com/QuentinDela), 

This problem and solution for this kind of problem could be many things. I suggest looking at how the React website deployment is managed. The server or service you are using may be configured to auto route any `/someurl` to root `/` for some routing purposes.
