### ISSUE TITLE
What new features would you like to see for v1?

### ISSUE THREAD

**Issue by timlrx** [timlrx/tailwind-nextjs-starter-blog#46]
Hi all,

I am thinking of improving the template by adding some new features. What would you like to see in the next major release? Feel free to add a comment with a new feature request and upvote (👍 ) the ones that you want!

Will add things that are being worked on or completed over here:

[Progress Tracker](https://github.com/timlrx/tailwind-nextjs-starter-blog/projects/1?add_cards_query=is%3Aopen)

- [x] Support for multiple authors
- [x] Copy button for code sections
- [x] Layout templates
- [x] Easier theming of tailwind config
- [ ] Documentation

**Comment by timlrx** [comment]
Support for multiple authors

**Comment by timlrx** [comment]
Support for different layouts for blog posts - i.e. add a new layout frontMatter field and map it to the correct layout template besides the current `PostLayout`

**Comment by timlrx** [comment]
[bibliography](https://bookdown.org/yihui/rmarkdown-cookbook/bibliography.html) - a feature I miss when migrating my rmd blog to mdx and nextjs. Downside is there does not appear to be any well-maintained remark package for it.

**Comment by CITIZENDOT** [comment]
Copy button for Code sections would be a nice addition.

**Comment by DoctorDerek** [comment]
I'd be happy to help implement any of these.

Also I wanted to run the idea by you of a TypeScript fork of this template
that would try to be paired to the current version / tag.

 If you're interested, I could start that when you launch V1.

**Comment by timlrx** [comment]
@CITIZENDOT something like the copy button in [docusaurus code blocks](https://docusaurus.io/docs/markdown-features/react)?

**Comment by timlrx** [comment]
@DoctorDerek sure, let me know which ones you are interested to work on and we can create a separate issue to track the discussion and avoid duplicate work. Currently, I am working on the multiple authors enhancement in the v1 branch.

Typescript is nice, but I will not have time to maintain it so it would be up to the community to maintain the fork. I considered using Typescript for the project but decided against it as it is one more thing to learn for someone unfamiliar with it and is a bit of an overkill for a blog :)

**Comment by timlrx** [comment]
[Tab component like docusaurus](https://docusaurus.io/docs/markdown-features/tabs)

**Comment by timlrx** [comment]
Admonitions / Notification component. [Docusaurus example](https://docusaurus.io/docs/markdown-features/admonitions)

**Comment by timlrx** [comment]
TOC component / passing down a toc prop for each mdx document. [Docusaurus example](https://docusaurus.io/docs/markdown-features/inline-toc)

**Comment by timlrx** [comment]
Richer excerpt and description. Instead of using the description frontmatter field to render the excerpt in the blog roll page we could split by `<!--more-->` as done in some [hugo templates](https://gohugo.io/content-management/summaries/). This allows non-text excerpts.

**Comment by CITIZENDOT** [comment]
> @CITIZENDOT something like the copy button in [docusaurus code blocks](https://docusaurus.io/docs/markdown-features/react)?

Yeah. Also, How about making it optional? All code-blocks aren't meant to be copied, Right? I mean we'll pass an argument `isCopyable=true` to code sections (something like that).

**Comment by timlrx** [comment]
Codeblocks are parsed from the triple tick markdown syntax in HTML divs appropriately styled. It's not a react component. I think having all code blocks copyable is fine. It's small and unobtrusive.

**Comment by faisalcep** [comment]
- Comment in blog post with staticman
- Feature Image for blog post

**Comment by osseonews** [comment]
Sorry, didn't see this issue, before I posted. Pagination and/or infinite scrolling would be great for the blog page where you list all the blog posts.

**Comment by osseonews** [comment]
> * Comment in blog post with staticman- example: https://mademistakes.com/articles/improving-jekyll-static-comments/
> * Feature Image for blog post- example: https://mademistakes.com/

For comments, I highly recommend using https://talk.hyvor.com/ - It's dead simple to integrate into any react blog and it works great.

**Comment by timlrx** [comment]
@osseonews no worries, it's better to discuss features on a new thread and keep this for upvoting new features. Should have gone with the discussions feature instead of a github issue but will live with this for now :)

**Comment by timlrx** [comment]
We can think of how to include a plugin system for more complicated integrations. Ideally, it should be optional but easy to integrate and the community can contribute what they want (staticman, disqus, hyvor etc.)

For the feature image, it should be relatively easy to implement by adding one or two lines to the existing template. There's already an images frontmatter field. I prefer not to use it directly for more control over the display. Though with the layout template option, it would be easy to create a version that supports feature image out of the box.

**Comment by frontendwizard** [comment]
I'd like to work on internationalization. I'd like to write in two languages and deploy them to different locations.

**Comment by timlrx** [comment]
@frontendwizard as in [domain routing](https://nextjs.org/docs/advanced-features/i18n-routing#domain-routing)?

**Comment by DoctorDerek** [comment]
> A how to update section might be a good idea for the docs for Version 1; I
> also had this question, and @timlrx is great about answering it, but it
> would now seem to qualify as a Frequently Asked Question.
_ copy-paste to close #57 _

Also I'll open an issue for the TypeScript conversion after we get Version 1 out.

My feature request for Version 1 is ... test coverage! And I'll write the tests! lol

Let's shoot for, IDK 50% and a badge on the repo.

@timlrx I'd lean toward react-testing-library unless you have another preference. Do you have a preferred code coverage tool? I like saying https://coveralls.io but don't have a strong preference.

**Comment by DoctorDerek** [comment]
Also I'll open an issue for the TypeScript conversion after we get Version 1 out.

My feature request for Version 1 is ... test coverage! And I'll write the tests! lol

Let's shoot for, IDK 50% and a badge on the repo.

@timlrx I'd lean toward react-testing-library unless you have another preference. Do you have a preferred code coverage tool? I like saying https://coveralls.io but don't have a strong preference.

**Comment by frontendwizard** [comment]
@timlrx yeah, it didn't crossed my mind before, but there's nothing to be done, I can just rely on next.js new i18n features :)

**Comment by kingchun1991** [comment]
I would like to suggest adding table of content

**Comment by sarumoina** [comment]
more options for customization. Right now, I am finding it very hard to change the location of the data folder. Have looked through most files but yet to find the parameter where I can change it.

**Comment by crisog** [comment]
I'm not sure if this is a valid feature request, but besides posting article/tech posts I'm interested in posting weekly journal entries which are more personal. It would be nice to have a tab that's called `Journal` gathering all these journal-like entries. 

This could work by just having the option to create tabs for specific tags that are invisible to the reader.

**Comment by timlrx** [comment]
@crisog I probably would not include such a feature out of the box, but the new template should make it easy to relatively to implement and customize - just copy the `pages/blog` folder and rename it to `page/journal`. Change all mention of `blog` to `journal` in the code and that should work. The content should then be accessible at `www.website/journal` but there's no navigation link to it. You can add a no index file if you don't want it to be indexed by the search engines and remove it from the sitemap.

**Comment by osseonews** [comment]
I'm not sure if the Multiple Author features includes this, but if not, I think it would be great, to have an Author Page that lists the posts associated with that Author, as well as some profile data for that author. I guess that also requires some markdown page for each author with a slug. thanks.

**Comment by timlrx** [comment]
Hi @osseonews, currently, the author page just renders the main author. I prefer to leave it flexible and allow someone to configure it to render a page for each author or some kind of all authors page like you mentioned. Would be open to having various design templates which can render various pages of interest - authors, journals and variants of home page etc as community contribution.

**Comment by ryadav96** [comment]
@timlrx will it be good if we Can separate blog's content in the different repo?

**Comment by AryaveerSR** [comment]
Hi @timlrx, I recently found this project, and I love it! I want to contribute in some way, I'm Good with Next.js and TailwindCSS and other stuff used in this repo. Is there something like a discord server or slack channel for discussion? Also, I probably could help with Documentation.

**Comment by timlrx** [comment]
hI @AryaveerSR, I have set-up a discussions page on Github so feel free to carry on the discussions over there. Docs is always appreciated. Feel free to add to the v1 readme and associated blog post, if there are areas that are not clear or should be made more explicit. Otherwise, if you are going through the code, comments over there are also welcome.

**Comment by aloisdg** [comment]
Support for typescript would be neat.

**Comment by aloisdg** [comment]
@DoctorDerek could we use cypress for end-to-end testing?

**Comment by DoctorDerek** [comment]
Hey @aloisdg I've converted a fork of this project to TypeScript for a client, so it can be done. Cypress for E2E testing would be a good idea. I like adding the TypeScript build step for code analysis. What parts of the blog do you think would benefit from E2E testing?

**Comment by timlrx** [comment]
Alright, thank you everyone for the feedback! If you have more feature requests or want to continue the conversation on some of the issues (e.g. typescript), feel free to use the discussions page.
