### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by catdrout420** [timlrx/tailwind-nextjs-starter-blog#48]
When i get to one of my posts i get this:

1 of 1 unhandled error
Server Error

TypeError: Cannot read property 'replace' of undefined
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source

layouts/PostLayout.js (60:55) @ PostLayout

  58 |       className="text-blue-500 hover:text-blue-600 dark:hover:text-blue-400"
  59 |       >
> 60 |                                   {siteMetadata.twitter.replace('https://twitter.com/', '@')}
     |                                   ^
  61 |     </Link>
  62 |   </dd>
  63 | </dl>

Please anyone help!

**Comment by DoctorDerek** [comment]
Hey @catdrout420! Hope I can help.

The template is meant to be used with a value in the `@/data/siteMetadata.json` file for `twitter`.

So if you deleted that, you'd need to comment out or delete that section of code, like I did in my project using this template.

```
                      <dd>
                        <Link
                          href={siteMetadata.twitter}
                          className="text-blue-500 hover:text-blue-600 dark:hover:text-blue-400"
                        >
                          {/*siteMetadata.twitter.replace(
                            "https://twitter.com/",
                            "@"
                          )*/}
                        </Link>
                      </dd>
```

[The typeof should be string](https://javascript.plainenglish.io/how-to-check-for-a-string-in-javascript-a16b196915ff) for the `siteMetadata.twitter` variable.

You could add it back to siteMetadata.json ([the JavaScript / JSON file](https://medium.com/swlh/what-is-json-used-for-in-javascript-programming-9d71284359a9) that got imported at the top) to fix the error.

Of course, this is could be seen as a bug, so I'll create a PR to prevent this error if someone deletes that value.
