### ISSUE TITLE
Site fails on fresh clone

### ISSUE THREAD

**Issue by nk9** [timlrx/tailwind-nextjs-starter-blog#485]
**Describe the bug**
The site fails to run after downloading the template from Git.

**To Reproduce**
1. Create new repo using "Use this template" button
2. Clone to local machine
3. `yarn install`
4. `yarn dev`

**Expected behavior**
The site should appear

**Screenshots**
Instead, there are katex errors:

```
error - ./pages/_app.js:3:0
Module not found: Can't resolve 'katex/dist/katex.css'
  1 | import '@/css/tailwind.css'
  2 | import '@/css/prism.css'
> 3 | import 'katex/dist/katex.css'
```

This despite katex being installed according to yarn.lock.

**System Info (if dev / build issue):**
 - OS: macOS 12.4
 - Node version 16.14.2
 - Yarn version 3.1.1

**Additional context**
Since I don't need katex, I tried commenting it out in `_app.js`. Then this error appeared:

```
./lib/remark-extract-frontmatter.js:2:0
Module not found: Can't resolve 'js-yaml'
  1 | import { visit } from 'unist-util-visit'
> 2 | import { load } from 'js-yaml'
```

Not sure what to do now.

**Comment by timlrx** [comment]
I tried installing a fresh version with no issues other than a few autoprefixer warnings. Could you try deleting node_modules and reinstalling the dependencies?

**Comment by nk9** [comment]
Thanks for the reply. I just tried again and have found that everything is working when I use `npm` instead of `yarn`. Is this expected?

**Comment by timlrx** [comment]
There's a `package.lock` in the repository so npm will install the exact dependencies. Using yarn, it will probably install the latest dependencies so that might cause some issues. But, I tried it out with yarn as well just now and it works.
