### ISSUE TITLE
Title tags issue

### ISSUE THREAD

**Issue by saqibameen** [timlrx/tailwind-nextjs-starter-blog#488]
I recently created ts template using this starter. When I deploy it to vercel, it shows the url in the browser tab instead of the actual <title>...</title>. Locally it works fine. On Google it indexes fine. But when you open site, this is how it looks like: 

<img width="106" alt="image" src="https://user-images.githubusercontent.com/31374163/174408705-dd3e8e14-b305-444a-869d-a64635d23b55.png">

When I inspect the website, <title> </title> tag is empty.
<img width="172" alt="image" src="https://user-images.githubusercontent.com/31374163/174408833-a4345786-1356-4d9e-ab42-1cac30f77162.png">

But if I see the page source, it is fine. I am not sure what is going on here. I tried other browsers as well. It is same.

**Comment by timlrx** [comment]
Can I check that [`siteMetadata.title`](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/data/siteMetadata.js#L2) has been filled and that the title is being passed to the [pageSEO component](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/pages/index.js#L21)? If so, could you link the repo and website and I could help take a look.

**Comment by saqibameen** [comment]
For sure, here is the [repo](https://github.com/saqibameen/blog). Here is the site [metadata](https://github.com/saqibameen/blog/blob/main/data/siteMetadata.js) and it is being passed to pageSEO component in [index](https://github.com/saqibameen/blog/blob/main/pages/index.tsx#L26).

**Comment by timlrx** [comment]
You must have cloned the repository from the Vercel "deploy" button? It seems like it automatically bumps next.js to the latest canary version which is 12.1.7-canary.30. It looks like they are making some big changes in preparation for nextjs 13 which might potentially break how the head component is rendered. I will take a look at the issue when it is officially released - strange that it works locally but not on Vercel. In the mean time, downgrading next.js to 12.1.6 fixes the issue!

I also see that you are on the typescript, non-contentlayer branch which I no longer intend to maintain. It will still work perfectly fine, but could I suggest trying out the [new project](https://github.com/timlrx/pliny)?

To bootstrap a new blog, run
```
npm i -g @pliny/cli
pliny new --template=starter-blog blog-name
```

I think the developer experience is much nicer with the new template :)

**Comment by saqibameen** [comment]
Thank you so much for taking a look and getting back quickly. 
Bumping down the version solved the issue. It is surprising to me, even the generated static files had the title and everything still they did not show up. I will definitely give the new project a try.
