### ISSUE TITLE
2h install.. don't know what i've done wrong!

### ISSUE THREAD

**Issue by EsimioJ** [timlrx/tailwind-nextjs-starter-blog#496]
weel 
it's got to be my fault but it takes 2 hours..
 I just used pliny new --template=starter-blog nextca

> husky install

fatal: not a git repository (or any of the parent directories): .git

added 1018 packages, and audited 1019 packages in 2h

322 packages are looking for funding
  run `npm fund` for details

**Comment by TszHong0411** [comment]
> weel it's got to be my fault but it takes 2 hours.. I just used pliny new --template=starter-blog nextca
> 
> > husky install
> 
> fatal: not a git repository (or any of the parent directories): .git
> 
> added 1018 packages, and audited 1019 packages in 2h
> 
> 322 packages are looking for funding run `npm fund` for details

Try to run `npm run prepare`

**Comment by timlrx** [comment]
Hi, the `new` script is just a simple wrapper over `create-next-app` - it should not take that long. Not sure if there are any network issues causing the problem.

The `husky` error is a known bug - https://github.com/timlrx/pliny/issues/23. Unfortunately, `create-next-app` automatically runs `npm install`.

**Comment by EsimioJ** [comment]
hello and sorry for the late reply.

maybe it's just my lack of knowledge :-)

I tried all 3 ways you recommend (pliny, ts and js) and the result is the same: the difference between the folder size and the folder size on disk are definitely different - I don't know how that translates, I have windows in Italian, but looking at the folder properties you should be able to see it.

folder size about 400 megs, folder size on disk over 10 gb?!?!

and I did it 3 times ...

after which I downloaded the zip and now everything works fine.
![tailwind-nextjs-starter-blog-master](https://user-images.githubusercontent.com/10819131/177036405-21169191-b653-491f-b38c-a27c9e9bfd18.png)

**Comment by timlrx** [comment]
Welcome to node.js 😁 

400MB looks about right to me. The node module dependencies take up quite a bit of space - nextjs by itself takes about 100MB.

**Comment by timlrx** [comment]
Resolved the husky error by not automatically initializing it for a new project.
