### ISSUE TITLE
Remove Sharp from package json

### ISSUE THREAD

**Issue by technolaaji** [timlrx/tailwind-nextjs-starter-blog#497]
When installing node modules if you have node version beyond 12 then it will not install 

When removing the sharp package from package.json and remove the package lock and node_modules folder it works

I did this while migrating from V0 to V1, it wouldn't install any dependencies till I removed sharp

**Comment by timlrx** [comment]
Strange, maybe it's some kind of dependency issue when you were migrating due to conflicting versions of sharp or other packages. A fresh install works fine.

**Comment by technolaaji** [comment]
Actually what I did is that I did a fresh repo with the updates on it then migrate the bits I wanted from V0

in other words: it was a fresh install and the fresh install on its own made this issue (I used degit to get V1, pliny install downloaded the repo but it wouldn't compile it)

**Comment by creativesully** [comment]
FWIW, I had that error with node v14.18.2 --> I just bumped to 16.16.0 and had no issues.

**Comment by timlrx** [comment]
Removed sharp from the default package. If someone wants to self-host they can add it back in.
