### ISSUE TITLE
Pagination?

### ISSUE THREAD

**Issue by osseonews** [timlrx/tailwind-nextjs-starter-blog#50]
Thanks for the amazing work on this. Any chance you can add pagination to the: layouts/ListLayout.js. - If we have alot of posts, it just shows all the posts on that page, which is not ideal (we have 100 posts). Would be better to have pagination, and 20 posts per page. Or infinite scrolling also would be a good idea. Thanks.

PS add a tip jar to this repo.

**Comment by timlrx** [comment]
Thanks, infinite scrolling would be nice! Happy to receive a PR on this if anyone is interested in taking this up otherwise, I will put it in the backlog.

**Comment by Music47ell** [comment]
I already implemented pagination and you can set the number of posts on each page.

**Comment by timlrx** [comment]
Nice! Do you mind sending in a PR?

**Comment by Music47ell** [comment]
I'm working on a PR right now. Just fixing few issues.

**Comment by syedsimanta03** [comment]
Let me when you are done

**Comment by timlrx** [comment]
Completed in the recent release (v0.3.4), thanks @Music47ell!

**Comment by syedsimanta03** [comment]
Pagination feature Merged to maater branch?

What is default posts value or number to show?

**Comment by timlrx** [comment]
Yes, https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/pages/blog.js#L6

**Comment by Music47ell** [comment]
> Completed in the recent release (v0.3.4), thanks @Music47ell!

You're welcome 😊

**Comment by syedsimanta03** [comment]
Can you please explain differences between npm run dev and npm run start. Whatvis that watch mode
-------- Original message --------From: Ahmad Al Maaz ***@***.***> Date: 29/05/2021  5:39 pm  (GMT+06:00) To: timlrx/tailwind-nextjs-starter-blog ***@***.***> Cc: syedsimanta03 ***@***.***>, Manual ***@***.***> Subject: Re: [timlrx/tailwind-nextjs-starter-blog] Pagination? (#50) 



Completed in the recent release (v0.3.4), thanks @Music47ell!



You're welcome 😊
