### ISSUE TITLE
"View on GitHub" link does not contain file extension

### ISSUE THREAD

**Issue by jvereecken** [timlrx/tailwind-nextjs-starter-blog#502]
**Describe the bug**
The 'view on Github' link does not work due to it receiving a slug instead of a filename

**To Reproduce**
1. Go to a Blog post
2. Click on View on Github
3. Link will not work

**Expected behavior**
View on Github link should work

**Comment by jvereecken** [comment]
Hmm, it looks like a version mismatch of sorts. I have installed the template by using the `npx degit 'timlrx/tailwind-nextjs-starter-blog#contentlayer'`command as shown in the readme. Looks like it is not working in that version

**Comment by timlrx** [comment]
This has been patched in pliny which I will be copying over to this repository soon.
