### ISSUE TITLE
glob-parent before 6.0.1 vulnerable to Regular Expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by josemiguel-alvarez** [timlrx/tailwind-nextjs-starter-blog#505]
glob-parent before 6.0.1 is vulnerable to Regular Expression Denial of Service (ReDoS).

The security issue was fixed [here](https://github.com/gulpjs/glob-parent/pull/49).

### Suggested solution
Require version ^6.0.1 of glob-parent using NPM overrides in package.json.

**Comment by josemiguel-alvarez** [comment]
I've created a PR to fix it: #506

**Comment by timlrx** [comment]
Hi, as mentioned in the PR,  I think there's no need for the patch. It's used internally only by tailwind, contentlayer, eslint and globby. No user is ever going to submit an input for parsing.
