### ISSUE TITLE
"No data received from your website yet."

### ISSUE THREAD

**Issue by Dev-Elie** [timlrx/tailwind-nextjs-starter-blog#511]
Hi. I wanted to use an analytics provider so added it to the content security policy in the `next.config.js`.
DataLayer adds events however on my Google analytics account I get `"No data received from your website yet."`

I have everything set up in the following files.
1. [siteMetadata.js](https://github.com/Dev-Elie/ondiek-elijah/blob/master/data/siteMetadata.js)
2. [next.config.js](https://github.com/Dev-Elie/ondiek-elijah/blob/master/next.config.js)

[Live site](https://www.ondiek-elijah.me/)
[GitHub repo](https://github.com/Dev-Elie/ondiek-elijah)

What could I be missing?

**Comment by timlrx** [comment]
It should be working. I see the google tag manager script inserted on your site with the G-tag setup. Were you trying it on development? The analytics script only runs in production since it looks for `process.env.NODE_ENV === 'production'` before loading the script.

**Comment by Dev-Elie** [comment]
I tried it in production but still GA shows "No data received from your website yet."

**Comment by Dev-Elie** [comment]
I just checked, and I'm sure it's now operational. I'm not convinced why it took so long. Thank you very much.
