### ISSUE TITLE
Building problem with fleek.co

### ISSUE THREAD

**Issue by TurkishENS** [timlrx/tailwind-nextjs-starter-blog#514]
**Building Problem**
Building problem with fleek.co

**To Reproduce**
Everything is smooth with Vercel.

**Expected behaviour**
It could not build up with fleek.co
<img width="950" alt="Screenshot 2022-07-26 at 02 19 51" src="https://user-images.githubusercontent.com/109963005/180902017-23d5ce8c-cd5e-43fc-879f-04835878b7d3.png">

**Comment by timlrx** [comment]
I have not tried fleek.co. Seems like it is trying to create a static build with `export`. The current application requires a bit more work if you want to do it that way (e.g. remove the API routes and all other server rendered functionality)

**Comment by TurkishENS** [comment]
I wanted to use Fleek; they have an IPFS option. Thanks a lot, indeed. I am not good enough to do those things. Now I'm using it as it is, which is very good. Again thank you so much.
