### ISSUE TITLE
Is there a way to change the blog url to something else?

### ISSUE THREAD

**Issue by technolaaji** [timlrx/tailwind-nextjs-starter-blog#518]
I want to publish several types of content that utilize the markdown mdx file structure but instead of having "blog/some-id" to become "content/some-id" or "entity/some-id".

my request is to have a base url that for the project that incase I want to use the template for more than just posting blog posts like right now I publish podcast episode show notes as a blog entry at the moment also working on publishing shorts/reels as posts on the site for reach. I understand that I can change the folder found in pages and add some modifications to the components to read from 

so the feature request is as follows:

- have a base url that the developer can change at will
- if the idea of base url is not doable due to a nextjs issue/limitation (which I understand) then documentation of how I can include multiple entities into the homepage and search? like if I create a podcast folder in the pages folder with the same structure as blogs then instructions and tips on how to make it visible on the homepage and search
- if structuring multiple types in the pages folder is also a hassle, instructions on how to change the base url manually to the developer's liking like changing the base url from "blog/some-id" to "entity/some-id" then I can add my content under a general umbrella like "content" and from it I can search for them based on the tags assigned to them

**Comment by timlrx** [comment]
You can add a new "content type" and path by copying the `/blog` folder and renaming it accordingly. Within the folder the paths follows the file directory pathing so sub folders in `data/blog` are supported. One possibility would be to rename `blog` to `content` and create subfolders over there accordingly so you can have `content/type1/id` and `content/type2/id` relatively easily.

**Comment by technolaaji** [comment]
I did actually rename blog to content where I shifted everything that relates to blog to content including routes and rss 

there are a lot of elements that rely on the blog folder where it expects the path to be always blog but it was successfully done where I searched for anything containing ```/blog``` and fill it with ```/content``` and it worked like a charm
