### ISSUE TITLE
Cloudinary image optimization 

### ISSUE THREAD

**Issue by vahidtakro** [timlrx/tailwind-nextjs-starter-blog#520]
Hello, through local images, and self hosted images in next.js, you can easily optimize images, adding lazy-load and blur version of images before opening. Meanwhile, this is not possible when you load your images through cloudinary. Is there a way to optimize cloudinary images?

Thanks

**Comment by timlrx** [comment]
You should be able to use [remote patterns](https://nextjs.org/docs/api-reference/next/image#remote-patterns) to serve images hosted elsewhere through Next.js Image Optimization API. Or if you want to serve the images using cloudinary api instead, you can change the [built in loader](https://nextjs.org/docs/api-reference/next/image#built-in-loaders).
