### ISSUE TITLE
How to remove blog from url?

### ISSUE THREAD

**Issue by techexpresslive** [timlrx/tailwind-nextjs-starter-blog#525]
Hello,

I have a blog in WordPress and where the URL is like domain.com/slug but here it's doamin.com/blog/slug. I don't want blog in the URLs to match with previous URL to avoid 404 error.

Apart from this, is it possible to replace tags with categories? or can use tags and categories both.

Thanks in advance.

**Comment by timlrx** [comment]
I would probably do a [rewrite](https://nextjs.org/docs/api-reference/next.config.js/rewrites) for the first and I have no plans on supporting both tags and categories, though you could modify the template from tags to categories.

**Comment by techexpresslive** [comment]
Thanks for your reply. According to rewrite I just need to add  
source: '/blog',
        destination: '/',

in next.config and changing tags to categories will solve my problem but what if my Wordpress blog has both and want to use both? Any suggestion?
