### ISSUE TITLE
HOW TO SET THE IMAGE THAT DISPLAYS WHEN YOUR WEBSITE IS SHARED ON SOCIAL MEDIA

### ISSUE THREAD

**Issue by dinakar17** [timlrx/tailwind-nextjs-starter-blog#530]
## **Instead of this**
![image](https://user-images.githubusercontent.com/85105044/185781652-cd245958-f771-44ef-91e9-e3281d5ae6fc.png)

## **How to display in this format?**
![image](https://user-images.githubusercontent.com/85105044/185781672-147cb758-1a33-4da4-9970-e515863757aa.png)

**Comment by timlrx** [comment]
Closing as there is an existing discussion thread
