### ISSUE TITLE
Disqus CORS Issue - Comments not loading

### ISSUE THREAD

**Issue by josh-may** [timlrx/tailwind-nextjs-starter-blog#543]
**Describe the bug**
First off, thanks for open sourcing this project. The site is lightning fast and super easy to use!

I've added Disque to my blog but when I try to load the comments I get this message:
<img width="400" alt="Screenshot at Sep 09 06-22-49" src="https://user-images.githubusercontent.com/72312238/189339225-336271ca-aceb-4ff9-a01c-a5154efec236.png">

I've added "access control allow origin" to my security headers:

<img width="664" alt="Screenshot at Sep 09 06-17-15" src="https://user-images.githubusercontent.com/72312238/189339024-3adf455b-5a18-4162-aec4-e06d7b61cd49.png">

And I've added my domains in disqus as "trusted domains":
<img width="595" alt="Screenshot at Sep 09 06-17-33" src="https://user-images.githubusercontent.com/72312238/189339117-60f06c38-f620-48bb-9932-f2aeca6d4b88.png">

**To Reproduce**
1. Go to https://www.joshmay.xyz/blog/july-2022
2. Open the console log
3. Go to the bottom of the page and click on "Load Comments"
5. See error in the console log

**Expected behavior**
I was expecting the Disqus comment field to populate

**Additional context**
Here's my public repo https://github.com/josh-may/joshmay.xyz. 

If anyone else has experienced this let me know. Thank you :)🙏

**Comment by timlrx** [comment]
Hi Josh, there's no need to add "access control allow origin" to the security headers. CORS issues is mostly due to the server backend configuration. You should be adding your domain, not "disqus.com" to the "trusted domains". I see that you have already added "joshmay.xyz" and I thought that that would suffice but maybe you can try adding the vercel URL as well i.e. "joshmay-xyz.vercel.app"

**Comment by josh-may** [comment]
@timlrx Thanks for looking into this. 

I removed "access control allow origin" and "disqus.com" as a trusted domain. And I added "joshmay-xyz.vercel.app" as a trusted domain and **I'm still seeing the error.** 

I can try to reach out to Disqus as well to see what they say. Let me know if you think of anything else :)

<img width="602" alt="Screenshot at Sep 09 11-14-22" src="https://user-images.githubusercontent.com/72312238/189395674-1a11f3fa-627c-43ed-9d83-e20d13f5ec67.png">

<img width="400" alt="Screenshot at Sep 09 11-13-16" src="https://user-images.githubusercontent.com/72312238/189395651-ce72e683-53f8-4a1c-9f59-0ac5c2834651.png">

<img width="520" alt="Screenshot at Sep 09 11-14-32" src="https://user-images.githubusercontent.com/72312238/189395783-c787bf27-366a-4efe-a9ac-70a290b97b98.png">

**Comment by timlrx** [comment]
`curl --head https://joshmay-xyz.disqus.com/embed.js`

returns

```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 79420
Server: openresty
Content-Type: application/javascript; charset=utf-8
X-Service: router
Date: Fri, 09 Sep 2022 16:26:46 GMT
Age: 0
Vary: Accept-Encoding
Cache-Control: private, max-age=60
Strict-Transport-Security: max-age=300; includeSubdomains
Cross-Origin-Resource-Policy: cross-origin
Link: <https://disqus.com>; rel=preconnect, <https://c.disquscdn.com>; rel=preconnect
```

Looks like the Cross-Origin-Resource-Policy is still not updated.

**Comment by josh-may** [comment]
@timlrx Got lost in the sauce so decided to just use Utterance. And it's working perfectly. Thanks again for making this. I bought a $70 Webflow template that wasn't half as good as this :)

**Comment by Drblessing** [comment]
Experiencing this same bug rn too :(

**Comment by mrded** [comment]
I'm also experiencing the same problem :/

**Comment by mrded** [comment]
related: https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/587
