### ISSUE TITLE
Watch if there is new markdown file in production

### ISSUE THREAD

**Issue by Mohammadreza99A** [timlrx/tailwind-nextjs-starter-blog#546]
Is there a way to not rebuild the entire project (with `yarn build`), every time there is a new markdown file added? 

For now, the `yarn start` command runs the project on dev mode if I am not mistaken. So how this can be changed so it stays in production without rebuilding every time there is a new markdown file in `data` directory ?

**Comment by timlrx** [comment]
That's not possible in the current project scope. Will probably need to change the rendering method and do a pure server side render.
