### ISSUE TITLE
Issue with `filename` and `slug` posts with Nested Routes

### ISSUE THREAD

**Issue by Music47ell** [timlrx/tailwind-nextjs-starter-blog#55]
If you check the [Nested Routes post](https://tailwind-nextjs-starter-blog.vercel.app/blog/nested-route/introducing-multi-part-posts-with-nested-routing), you'll see that at the bottom, both `Discuss on Twitter` and `View on GitHub` don't work properly.

In the `PostLayout`, a comma `,` is introduced in both `filename` and `slug` instead of a slash `/`.

Example: `nested-route,introducing-multi-part-posts-with-nested-routing`

**Comment by timlrx** [comment]
Thanks, have pushed a fix.
