### ISSUE TITLE
Ability to use Google Analytics 4 property (GA3 and GA4 support)

### ISSUE THREAD

**Issue by bozzmob** [timlrx/tailwind-nextjs-starter-blog#551]
**Is your feature request related to a problem? Please describe.**
Google Analytics dashboard shows an error-
```
Universal Analytics will no longer process new data in standard properties beginning 1 July 2023. Prepare now by setting up and switching over to a Google Analytics 4 property.
```
We will have to start migrating to GA4 at some point, sooner the better.

**Describe the solution you'd like**
Migrating to GA4

**Describe alternatives you've considered**
Currently using GA3

**Additional context**
https://support.google.com/analytics/answer/11583528

**Comment by darisi** [comment]
I have a similar problem. I added GA4 via Google Tag Manager and the GTM loads but not the GA4 tag and it's published.

**Comment by darisi** [comment]
My bad, forgot to add *.googletagmanager.com to script-src it works now with GTM + GA4.
