### ISSUE TITLE
404: NOT_FOUND for vercel deployment

### ISSUE THREAD

**Issue by rush86999** [timlrx/tailwind-nextjs-starter-blog#559]
**Describe the bug**
Follow the fresh package installation instructions

**To Reproduce**
1. follow installation instructions

**Expected behavior**
able to deploy on vercel

**Screenshots**
check github repo of blog: https://github.com/rush86999/atomic-app-blog

check deployment: https://atomic-app-blog-nhfsv4sxz-rush86999.vercel.app/blog

**Comment by timlrx** [comment]
Try using the latest version available at https://github.com/timlrx/pliny, it should work just fine.

**Comment by rush86999** [comment]
tried ```pliny new --template=starter-blog``` still the same. Any other advice? I'm missing something simple but not sure what that is.

**Comment by timlrx** [comment]
Can you check your vercel project settings page? It should like this:
![image](https://user-images.githubusercontent.com/28362229/197664649-d79cb102-66e2-41e1-ab90-5aab3107fe3b.png)

I just deployed a brand new template and it works fine

**Comment by rush86999** [comment]
you were right --- vercel registered the project as non-nextjs and all I did was select 'nextjs' from the drop down. Not sure why it was not recognized as a nextjs project. Maybe you can add a little side note about this.
