### ISSUE TITLE
ISR (Incremental Static Regeneration) is not working in dynamic routing pages

### ISSUE THREAD

**Issue by 15077693d** [timlrx/tailwind-nextjs-starter-blog#560]
Demo site: https://oscaryiu-com-i1dy-git-feat-view-count-15077693d.vercel.app/
PR: https://github.com/15077693d/oscaryiu.com/pull/3

In page /blog and /, Incremental Static Regeneration is perfectly working.
1. Go to https://oscaryiu-com-i1dy-git-feat-view-count-15077693d.vercel.app/blog/motivation-on-oscaryiu-2-0
2. Go to https://oscaryiu-com-i1dy-git-feat-view-count-15077693d.vercel.app/ 
3. View count change after refresh

However, In page /blog/[...slug] and /tags/[tag] is not working
1. Go to https://oscaryiu-com-i1dy-git-feat-view-count-15077693d.vercel.app/blog/motivation-on-oscaryiu-2-0
2. Refresh the page
3. View count doesn't change after refresh

According to https://stackoverflow.com/questions/67787456/what-is-the-difference-between-fallback-false-vs-true-vs-blocking-of-getstaticpa, I update getStaticPaths to return {fallback: true}.

However, it still not working. 
May I get some help?

**Comment by 15077693d** [comment]
![Screenshot 2022-10-24 at 5 59 35 PM](https://user-images.githubusercontent.com/51513183/197501785-cdba295b-ee43-4c80-a1b0-efa32fe0c622.png)
I found an error here, what is RSS feed using for?

**Comment by timlrx** [comment]
Try using the latest template version from https://github.com/timlrx/pliny. In the old code, the RSS feed (feed.xml) is generated within `getStaticProps`. In the new version, it's generated post build. Though this means that you have to find some way to incrementally modify or serve the sitemap and rss feed as well to be compatible with ISR.
