### ISSUE TITLE
Help me to setup emailoctopus

### ISSUE THREAD

**Issue by 0xShakhawat** [timlrx/tailwind-nextjs-starter-blog#563]
![image](https://user-images.githubusercontent.com/52792157/197958793-fed47978-aba4-4883-8fc3-2723a9f0249d.png)

is that the correct process I assigned?

**Comment by timlrx** [comment]
The API_URL is just "https://emailoctopus.com/api/1.6/". The rest looks fine.

**Comment by 0xShakhawat** [comment]
Thanks. It's working 🤗❤️
