### ISSUE TITLE
Unable to port app to typescript

### ISSUE THREAD

**Issue by okayplanet** [timlrx/tailwind-nextjs-starter-blog#567]
**Describe the bug**
Unable to port app to typescript following nextjs guide for "Existing Projects" https://nextjs.org/docs/basic-features/typescript

**To Reproduce**
1. clone repo
2. `touch tsconfig.json` and then follow package installation recommendations in terminal (might have to downgrade @types/react with `npm install --save-dev @types/react@18.0.1`
3. `npm run dev`
`ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /Users/okayplanet/dev/okayplanet-web/.env
error - ./pages/_app.js:1:0
Module not found: Can't resolve '@/css/tailwind.css'
> 1 | import '@/css/tailwind.css'
  2 | import '@/css/prism.css'
  3 | import 'katex/dist/katex.css'`

The @ alias seems to cause trouble with typescript. Any recommendations?

**Expected behavior**
Successful typescript upgrade.

**Screenshots**

**System Info (if dev / build issue):**
 - OS: MacOS 11.4
 - Node version v16.10.0
 - Npm version 7.24.0

**Comment by timlrx** [comment]
Can I suggest that you bootstrap a new version of the blog with https://github.com/timlrx/pliny. There have been multiple fixes and issues solved on that version. The only issue left before I copy it over is actually deciding whether it makes sense to use the new app director or stick with the existing page structure.
