### ISSUE TITLE
npm ERR! Could not resolve dependency: npm ERR! peer next@"^12" from next-contentlayer@0.2.8

### ISSUE THREAD

**Issue by agilatakishiyev** [timlrx/tailwind-nextjs-starter-blog#568]
**Describe the bug**
I tried to create the project using `@pliny/cli` and got an error because of the `next`, `contentlayer` or `next-contentlayer` version I guess.

**To Reproduce**
1. Open up a terminal window
2. Run `mkdir personal-website ; cd personal-website`
3. Inside the directory run `pliny new --template=starter-blog .`
4. Choose `Typescript`
5. You should face an error like in the image below

**Expected behavior**
Dependencies should be properly installed and I should be able to run the application.

**Screenshots**
<img width="1261" alt="Screen Shot 2022-11-10 at 03 05 19 AM" src="https://user-images.githubusercontent.com/57169563/200961660-db69b304-6007-4e55-b24e-4ad9c029c305.png">

**System Info (if dev / build issue):**
 - OS: macOS (Ventura 13.0.1)
 - Node version: 16.13.2
 - Npm version: 8.19.2

**Comment by agilatakishiyev** [comment]
Closing this because I saw this is not specifically an issue with this repo instead an issue with `@pliny/cli` and there is an [issue](https://github.com/timlrx/pliny/issues/78) in that project related to this issue.

**Comment by bgoldste** [comment]
In case anyone runs into this, I was able to deploy on vercel by modifying the install script to `npm install --legacy-peer-deps`
