### ISSUE TITLE
does "starter" mean I can't benefit from futur updates and won't be able to update code of the repo easily ?

### ISSUE THREAD

**Issue by smknstd** [timlrx/tailwind-nextjs-starter-blog#57]
thanx

**Comment by timlrx** [comment]
Nope, it means a template that works out of the box for most blogging needs - but you need to provide the content :)

Updating to the latest versions takes a little work, mostly replacing the old files with the updated ones but if the current template suffice than it's probably good enough!

**Comment by smknstd** [comment]
Thanx I get it ! Maybe readme should clarify this and mention if possible an "how to update". What do you think ?

There are some similar notions greatly written in here : https://www.gatsbyjs.com/blog/2018-11-11-introducing-gatsby-themes/

**Comment by DoctorDerek** [comment]
A how to update section might be a good idea for the docs for Version 1; I
also had this question, and @timlrx is great about answering it, but it
would now seem to qualify as a Frequently Asked Question.
