### ISSUE TITLE
Add my blog to the readme?

### ISSUE THREAD

**Issue by bgoldste** [timlrx/tailwind-nextjs-starter-blog#574]
**Is your feature request related to a problem? Please describe.**
Nope!

**Describe the solution you'd like**
Just to add my site, https://www.icanlearntocode.com/ to the readme. Saw some PRs but they didn't get merged so wanted to see what best practice here is

**Describe alternatives you've considered**

**Additional context**

**Comment by timlrx** [comment]
Closing all new listing PRs for now. Will be cleaning things up and migrating to a v2 version with react server components based on the app dir structure. Happy to accept new additions after that.
