### ISSUE TITLE
Dark theme not applied with JS disabled

### ISSUE THREAD

**Issue by iamkroot** [timlrx/tailwind-nextjs-starter-blog#576]
**Describe the bug**
Loading the blog with Javascript disabled results in light-theme rendering of the blog pages, even when `prefers-color-scheme: dark` is provided by the browser.

**To Reproduce**
1. Configure browser to set `prefers-color-scheme: dark` when loading sites
2. Go to https://tailwind-nextjs-starter-blog.vercel.app/
3. Open uBlock Origin and disable JS on the site
4. Refresh page
5. See light theme

**Expected behavior**
Page should be loaded with dark theme.

**Browser Info (if display / formatting issue):**
- Device: Desktop
- Browser: Firefox
- Version: 107.0b9

**Additional context**
* The code blocks inside blog posts _do_ get dark themes. I suspect this is just a CSS issue.
* Toggle for dark mode obviously doesn't work, since JS is disabled.

**Comment by iamkroot** [comment]
Huh, I found https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/482 and from there, got https://tailwind-nextjs-starter-blog-git-feat-meta-prefer-decb77-timlrx.vercel.app/ which _does_ work as expected.

So I'm guessing the https://tailwind-nextjs-starter-blog.vercel.app/ is simply not updated to v1.5.6.

Feel free to close this issue if you think no further action is needed

**Comment by timlrx** [comment]
It's a different issue from the above mentioned PR and I am able to replicate it on both sites. It's probably due to using the [manual class strategy of toggling dark mode](https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually) and the reliance on [next-themes](https://github.com/pacocoursey/next-themes) which uses js.

Will have to find a workaround to it when js is disabled.

**Comment by iamkroot** [comment]
Ah you're right, I hadn't properly disabled JS in the followup site. Seeing the same issue there too.

> Will have to find a workaround to it when js is disabled.

Wouldn't it be enough to query `prefers-color-scheme` in CSS and change the variables accordingly (all in CSS)?

**Comment by timlrx** [comment]
I don't think there's a work around. If you want the user to select and toggle the color scheme, this requires using a [class based approach](https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually), which requires a bit of js. This also means that you have to select a default when no-js is used and I don't think tailwind can switch to a `prefers-color-scheme` CSS media feature. The same "problem" exists on https://tailwindcss.com/. It defaults to dark over there even if the system is light when js is disabled.

**Comment by iamkroot** [comment]
Tailwind docs seem to have a solution for this- [Supporting system preference and manual selection](https://tailwindcss.com/docs/dark-mode#supporting-system-preference-and-manual-selection)
