### ISSUE TITLE
How do I replace the logo everywhere?

### ISSUE THREAD

**Issue by Gregliest** [timlrx/tailwind-nextjs-starter-blog#577]
In the Readme, it says "data/logo.svg - replace with your own logo." However, changing that file only affects the logo on the main website, not the icon in a browser tab, etc. Those icons appear to be in "public/static/favicons."

So, a couple of questions:
- How did you export all of those different sizes, with that naming convention? Is that something I can replicate somewhere, or should I just export all the sizes individually and then rename them? In particular, the mstile one seems weird: small image with a ton of padding. 
- Where are all the icons used? Some of them are obvious from the name, but others less so. I'm not familiar with this naming convention.

 I'm happy to help update the Readme with this information once I understand it. Thanks for all your hard work!

**Comment by AlexanderZeilmann** [comment]
Have a look at https://realfavicongenerator.net/ it should have all the information you are looking for.

**Comment by Gregliest** [comment]
Great thanks! I'll add this info to the readme.
