### ISSUE TITLE
disqus comment not working

### ISSUE THREAD

**Issue by MohammadTaseenKhan** [timlrx/tailwind-nextjs-starter-blog#587]
after updating the disqus shortname on env file there is no response on comment section

![image](https://user-images.githubusercontent.com/85288261/210061541-511ad67a-3eb2-400e-bdbd-bb212cd4cb0b.png)

![image](https://user-images.githubusercontent.com/85288261/210061560-67c4e1ec-c190-451e-93e1-805e88711bfb.png)

anyone help with this issue

**Comment by Zsemed** [comment]
It's a CORS error.

**Comment by MohammadTaseenKhan** [comment]
Any way to solve it

Is it blocked for csp

**Comment by timlrx** [comment]
You would need to modify the CSP as mentioned over here - https://www.sensibledefaults.io/blog/disqus-content-security-policy/index
