### ISSUE TITLE
Build error related to about and font

### ISSUE THREAD

**Issue by resistingdestiny** [timlrx/tailwind-nextjs-starter-blog#593]
Have made minimal/no changes to pliny built version of app, updated content and then deployed to Vercel. Seeing errors for the following that cannot seem to explain. Anyone else faced similar issues?

Error: @next/font/google failed to run or is incorrectly configured.
--
20:43:00.233 | at Object.<anonymous> (/vercel/path0/node_modules/@next/font/google/index.js:7:7)
20:43:00.233 | at Module._compile (node:internal/modules/cjs/loader:1159:14)
20:43:00.233 | at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
20:43:00.233 | at Module.load (node:internal/modules/cjs/loader:1037:32)
20:43:00.233 | at Module._load (node:internal/modules/cjs/loader:878:12)
20:43:00.233 | at Module.require (node:internal/modules/cjs/loader:1061:19)
20:43:00.233 | at require (node:internal/modules/cjs/helpers:103:18)
20:43:00.234 | at 7683 (/vercel/path0/.next/server/pages/_app.js:34:32)
20:43:00.234 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
20:43:00.234 | at __webpack_exec__ (/vercel/path0/.next/server/pages/_app.js:631:39)
20:43:00.235 |  
20:43:00.235 | > Build error occurred
20:43:00.237 | Error: Failed to collect page data for /about
20:43:00.239 | at /vercel/path0/node_modules/next/dist/build/utils.js:916:15
20:43:00.239 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

**Comment by timlrx** [comment]
Sorry for not checking in earlier but I just verified that the latest version works without issue.
