### ISSUE TITLE
author layout problem

### ISSUE THREAD

**Issue by MohammadTaseenKhan** [timlrx/tailwind-nextjs-starter-blog#595]
when there is more than two authors the layout becomes unresponsive to the width

screenshot:

![image](https://user-images.githubusercontent.com/85288261/212346512-a787dadf-5667-4ae3-b212-3c54146f7ce5.png)
![image](https://user-images.githubusercontent.com/85288261/212346561-c6131b0d-11d1-487f-a424-d1ab7bb6bef7.png)

@timlrx please help

**Comment by timlrx** [comment]
Thanks, I have fixed it. If you want to update the style you can just update to this line: https://github.com/timlrx/pliny/blob/main/starter-blog/layouts/PostLayout.tsx#L65
