### ISSUE TITLE
Using redux toolkit store with an mdx component

### ISSUE THREAD

**Issue by cordobadigitalmedia** [timlrx/tailwind-nextjs-starter-blog#60]
Hi
I using your template and it's working really great. Thanks so much
However, I've hit a wall related to make a redux toolkit store available to a component that's placed inside an mdx file.
I have wrapped my whole app with the store provider as usual but on the page that loads the mdx file that has a component that needs to load data from the store, I get this error
```
Error: Could not find "store" in the context of "Connect(NameofComponent)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(NameofComponent) in connect options.
```
Do you have any suggestions how I would make the store available to a component inside an mdx file. I've had a similar issue with trying to load data asynchronously in an MDX component and I've had to use a different strategy that was not too convenient.

**Comment by timlrx** [comment]
Hi, working with nextjs and redux is a little tricky as it depends on whether you are working on the client or server state. It seems that your setup is wrong as it is not able to locate the store. Nexjs documentation has an [example](https://github.com/vercel/next.js/tree/canary/examples/with-redux) on it. 

This is more of a nextjs / redux integration question and not related to the template so it's better to direct it to the nextjs repo.

**Comment by cordobadigitalmedia** [comment]
Thanks for your feedback. Sorry for re-opening this but I do think I am implementing the redux store correctly. I have done it the same way in another nextjs project before and it works fine. Furthermore, if I use the exact same component in a nextjs page, I don't get any error. But if I use it in an mdx page, it gives me the error above. So, I do think there needs to be some additional configuration to pass the store to the MDX components but I'm not sure what it is.
For implementing redux, I had used the [redux-toolkit example](https://github.com/vercel/next.js/tree/canary/examples/with-redux-toolkit) from nextjs
Any suggestions will be appreciated

- This is my [component](https://github.com/cordobadigitalmedia/shifra-life/blob/master/components/PrayerApplyTable.js)
- This is where I use it in a [page](https://github.com/cordobadigitalmedia/shifra-life/blob/master/pages/arabic/%5B...slug%5D.js) and it's fine
- And this is where it's added to an [mdx data](https://github.com/cordobadigitalmedia/shifra-life/blob/master/data/arabic/93/02/03_apply-verses.mdx) and I get the error
