### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'transition') -- caused by preact

### ISSUE THREAD

**Issue by PaulMest** [timlrx/tailwind-nextjs-starter-blog#600]
**Describe the bug**
I've spent a couple of days playing with various frameworks and really love the scaffolding you put together here. I'm in the process of updating one of my blogs to leverage your template and ran into an issue right before going live.

Since I've updated all of the dependencies to be their latest version, I'm guessing there is some new dependency that doesn't play well with preact. I'm getting weird errors only in production mode and never in dev.

```
TypeError: Cannot reading properties of undefined (reading 'transition')
...
Uncaught (in promise) Error: Cancel rendering route
```

**To Reproduce**
1. Upgrade all npm packages to their latest version
2. Launch in production mode (`yarn build && yarn serve`)
3. Open Chrome dev tools

**Expected behavior**
No errors should show up in console

**Screenshots**
<img width="874" alt="Screenshot 2023-01-27 at 11 43 17 PM" src="https://user-images.githubusercontent.com/1721104/215254284-404f21e9-a5d4-49d6-9840-163e6be232fd.png">

**System Info (if dev / build issue):**
 - OS: macOS Ventura 13.2
 - Node version: v18.13.0
 - Npm version: 8.19.3

**Additional context**
My workaround is to comment out the preact section in `next.config.js` and then my production builds work just fine.

**Comment by timlrx** [comment]
Yes, there's a bunch of compat issues with preact especially if you are using next 13 with react 18. In the latest version of the template at https://github.com/timlrx/pliny, I have also removed it.

**Comment by timlrx** [comment]
The new version (coming soon) uses react only so that's no such issues.
