### ISSUE TITLE
Use json instead of mdx

### ISSUE THREAD

**Issue by SundriedCorn** [timlrx/tailwind-nextjs-starter-blog#606]
**Is your feature request related to a problem? Please describe.**

I already have a blog that dynamically populates the index based on a json file. I was wondering if there was an easy way, or a way at all to be able to update the blog to use json instead of mdx?

**Describe the solution you'd like**

You can use a formatted json file

**Describe alternatives you've considered**

**Additional context**

**Comment by timlrx** [comment]
Would be possible with the new contentlayer setup but you would need to write the contentlayer part for that. Coming soon in v2.
