### ISSUE TITLE
Set my homepage to be blog instead of the latest posts page

### ISSUE THREAD

**Issue by sourstripe** [timlrx/tailwind-nextjs-starter-blog#608]
I am trying to adjust my blog to be the main page. the list layout one. when i move everything from listlayout to index it doesn't work anymore. it says pages not found even though pages was already used in index. now sure how to swap it
 get errors like TypeError: Cannot read properties of undefined (reading 'page')
 Error: getStaticPaths is only allowed for dynamic SSG pages and was found on '/'.

I also can't seem to use `const POSTS_PER_PAGE =6` for example. I start to get those errors

**Comment by sourstripe** [comment]
i figured it out.

**Comment by timlrx** [comment]
Closing the issue as we will be migrating to v2 with the new app dir setup.
