### ISSUE TITLE
Support for robots.txt 

### ISSUE THREAD

**Issue by pskd73** [timlrx/tailwind-nextjs-starter-blog#613]
**Is your feature request related to a problem? Please describe.**
robots.txt is an important tool in SEO. I am missing it in my own setup. Better we support it out of the box

I am happy to contribute if it is not implemented yet :)

**Comment by bravo-kernel** [comment]
Valid request IMO and one that could easily be realized with [Pliny](https://github.com/timlrx/pliny) and [next-sitemap](https://github.com/iamvishnusankar/next-sitemap). That way, both `robots.txt` and proper sitemaps will come out-of-the-box.

@timlrx are you open for a PR?

**Comment by sjwaight** [comment]
A simple workaround is to create a static 'robots.txt' file in the `public` folder and it will be deployed to your target hosting environment.

**Comment by bravo-kernel** [comment]
@sjwaight I have motivated my suggestion for using next-sitemap in more detail at https://github.com/timlrx/pliny/issues/101. 

If a PR is accepted I think that would be the correct way forward.

@pskd73 implementing is quite easy, see https://github.com/bravo-kernel/bravo-kernel.com/pull/169

**Comment by timlrx** [comment]
v2 which is based on app dir (coming soon) will allow you to add a robots.txt directly. I might just add it in the template as well.
