### ISSUE TITLE
Handle markdown inside frontmatter

### ISSUE THREAD

**Issue by iamkroot** [timlrx/tailwind-nextjs-starter-blog#614]
**Is your feature request related to a problem? Please describe.**
Just as the main blog contents might have markdown, so can the `title` and `summary` fields inside the frontmatter for a post. Today, these are displayed directly as raw strings ("An \_emphatic\_ title") instead of being decorated correctly ("An _emphatic_ title").

**Describe the solution you'd like**
Would be great if the framework could also parse and format the marddown present inside various frontmatter fields.

**Additional context**
I did try to implement this myself, but got way too confused by the complexity of `mdx-bundler` that we use today to parse the blog contents.
Considering that the frontmatter fields might be extremely straightforward, it would probably be ok to have a simple markdown parse instead of full `mdx` support. I managed to get this working somewhat using `remark-rehype`, but it used `dangerouslySetInnerHtml`, which might not be the best way to do this.

**Comment by timlrx** [comment]
gray-matter processes the yaml as raw strings and it would remain this work even after migrating to the new v2 with contentlayer. It exposes it as a `meta` js object so parsing to html does not make sense.

**Comment by iamkroot** [comment]
Forgive me, but the question can be rephrased as- if I provide markdown inside the title/summary fields, how do I get them to be styled as such? Is ContentLayer going to support this out of the box, or do we need to do something additional?

PS: thanks a lot for your work on V2! The improvements are very welcome. Will try to migrate soon :)
