### ISSUE TITLE
Empty metatags on Tags page

### ISSUE THREAD

**Issue by iliamrv** [timlrx/tailwind-nextjs-starter-blog#615]
Tags are categories which should have their unique description and metatags.

Is there a way to add unique meta data for every tag page? For example, for articles I can use Frontmatter to overwrite default meta tags. 

So how can I write custom meta tags for every tag page? I mean /tags/*

Thanks!

**Comment by timlrx** [comment]
In the new v2 version based on the app directory structure, you would be able to customize the metadata export file for that purpose.

**Comment by iliamrv** [comment]
great news! when do you plan to release the new version?

**Comment by timlrx** [comment]
It's going to be a new version of the template. Currently working on it, releasing it maybe in a week's time?
