### ISSUE TITLE
White background appearing in dark themes

### ISSUE THREAD

**Issue by ameliacode** [timlrx/tailwind-nextjs-starter-blog#617]
**Describe the bug**
https://tailwind-nextjs-starter-blog.vercel.app/blog/new-features-in-v1

If you scroll down all the way to comments section,
comments section has white background..

From what I remember, this error appeared recently in latest updates..
also, the width shrank too.

**Expected behavior**
dark background in dark theme!!

**Screenshots**
[Here's the link](https://tailwind-nextjs-starter-blog.vercel.app/blog/new-features-in-v1)

**System Info (if dev / build issue):**
 not an build issue

**Browser Info (if display / formatting issue):**
- Device: desktop, mobile both.
- Browser: chrome, edge, safari, firefox
- Version: -

**Additional context**

**Comment by ameliacode** [comment]
giscus migrated style.css, 
In order to work properly, add this line in next.config.js: `style-src 'self' 'unsafe-inline' giscus.app;`

I eventually find the solution my own.
I'm closing this now

**Comment by danieldanielecki** [comment]
bump on this!
