### ISSUE TITLE
Stackbit configuration 

### ISSUE THREAD

**Issue by benstaf** [timlrx/tailwind-nextjs-starter-blog#620]
**Is your feature request related to a problem? Please describe.**
It would be easier to have a Content Management System

**Describe the solution you'd like**
I tried Stackbit but I got the error message: 
stackbit.yaml configuration file not found

**Comment by timlrx** [comment]
Nope, this blog uses mdx files to manage content. We will be integrating with contentlayer for v2 and it's possible to add external content sources from there.
