### ISSUE TITLE
Publishing a new blog requires republishing

### ISSUE THREAD

**Issue by huanting** [timlrx/tailwind-nextjs-starter-blog#625]
**Is your feature request related to a problem? Please describe.**
When I want to publish a new blog, do I need to rebuild the project and publish it on Vercel?

**Describe the solution you'd like**
After adding a new blog, the blog file is transferred to the blog directory,  I refresh the page and the page displays the latest blog.

**Describe alternatives you've considered**

**Additional context**

**Comment by sjwaight** [comment]
The process you've described is how it works. 

If you want to manage when posts show up on your production site you can either:

- Use the "draft" post header value and set it to 'true'. The downside is you can't view the file locally or remotely.
- Create a git branch for each new blog post and then open a pull request on GitHub to merge it to master (but don't merge). This will cause Vercel to deploy that version of the site on a custom URL that you can then view. When you're ready to publish, merge the PR into the main/master branch and it will be published to your live site.

The second option is fairly standard across hosters like Vercel and Netlify and is actually a pretty slick experience. It really helps avoid accidentally posting content to your production site until you are really ready to publish!

Hope this helps.

**Comment by timlrx** [comment]
That's right, it's possible to modify the setup to do server side rendering and allowing incremental builds from an external content source but that's out of scope of the current template.
