### ISSUE TITLE
How can we add adsense code to header

### ISSUE THREAD

**Issue by mandeepsng** [timlrx/tailwind-nextjs-starter-blog#626]
**Is your feature request related to a problem? Please describe.**

this is my adsense code
`<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-xxxxxxxxxxx"
     crossorigin="anonymous"></script>`
need to add into header

How can I do that
I tried this but not working
`<Script id="Adsense-id" 
            async="true"
            onError={(e) => { console.error("Script failed to load", e);}}
            strategy="afterInteractive"
            src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-xxxxxxxxxxxx"
            crossorigin="anonymous"
          />`

**Comment by Abinaskarki** [comment]
Hi Mandeep, this issue will get resolved by adding the script to the Head of _document.tsx file in pages folder. 

<Head>
   <script
            async
            src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-xxxxxxxxxxxxx"
            crossOrigin="anonymous"
          ></script>
</Head>

Also, it is better to add ads.txt file with adsense credentials  you get from Google Adsense in the public folder.

**Comment by chandikaRT** [comment]
Hello! Can someone help me out with this, should I create a new _document.tsx in a new folder called pages and then add the script?
