### ISSUE TITLE
How do I go about to create Authors' page.

### ISSUE THREAD

**Issue by janparkio** [timlrx/tailwind-nextjs-starter-blog#63]
I would like to mimic what Tags does in `pages/tags/[tag.js]` but for authors,
How can I go about to modify the files and achieve something like that?

Also looking to add multiple authors not just one, so exactly like how tags work.

**Comment by janparkio** [comment]
Just checked that you are going to include this as a v1 release. I'm closing the issue :) and wait patiently.

**Comment by timlrx** [comment]
Feel free to try out v1. There are some new features I still want to introduce before rolling it out but if you want to start a head start, you can fork the branch. You can read more about the new features and how to use them in the preview deployed blog: https://tailwind-nextjs-starter-blog-k0sbybso9-timlrx.vercel.app/
