### ISSUE TITLE
Overcome the limitation of images required to be in static/images

### ISSUE THREAD

**Issue by avkonst** [timlrx/tailwind-nextjs-starter-blog#631]
**Is your feature request related to a problem? Please describe.**

The documents for images say: "All images have to be stored in the public folder e.g /static/images/ocean.jpeg"

**Describe the solution you'd like**
I would like to have images stored alongside mdx files where they belong to. And refer to it like the following `![Моя картинка](./teddy.jpg)`

**Describe alternatives you've considered**
I do not know alternatives

**Additional context**
None

**Comment by timlrx** [comment]
No, I don't think we would support such a feature.
