### ISSUE TITLE
 How to add Read Time feature to the blog posts?

### ISSUE THREAD

**Issue by dushyanth31** [timlrx/tailwind-nextjs-starter-blog#637]
Hey guys,

I knew that already a Read Time feature issue was closed, But that was not solved my issue.

Can anyone tell me how to use it by step-by-step ?

Thank you.

**Comment by haramishra** [comment]
You can access read time data using `content.readingTime.text` in the `/layouts` directory.

**Comment by haramishra** [comment]
ckeckout[ this](https://github.com/haramishra/hara-portfolio/blob/7c5e691302f4cb1a243f485531f5e9d4ee359811/layouts/PostLayout.tsx#L59) for reference

**Comment by timlrx** [comment]
Thanks @haramishra, that's how I would do it as well.
