### ISSUE TITLE
Localization with i18n

### ISSUE THREAD

**Issue by erengaygusuz** [timlrx/tailwind-nextjs-starter-blog#64]
Can you add localization option like i18n?

**Comment by timlrx** [comment]
Next.js has [built-in support for i18n](https://nextjs.org/docs/advanced-features/i18n-routing) so you can modify the next.config.js file to support it.

**Comment by arkhipov** [comment]
I think the question is about string translations, not just keeping URLs and locales in sync (@timlrx's link is about this). I am also interested in comprehensive i18n support for this great blog theme ;) If you do not mind using https://github.com/isaachinman/next-i18next I can try adding it to the current version.

**Comment by timlrx** [comment]
@GautierArcin maintains a full i18n version of the blog! Check it out over [here](https://github.com/GautierArcin/i18n-tailwind-nextjs-starter-blog/tree/demo/next-translate)

**Comment by arkhipov** [comment]
Wow, thanks a lot!
