### ISSUE TITLE
Add i18next Support

### ISSUE THREAD

**Issue by tawfiqh58** [timlrx/tailwind-nextjs-starter-blog#642]
### Description
I would like to request the addition of i18next support to the "tailwind-nextjs-starter-blog" repository. This feature would greatly enhance the localization capabilities of the project and allow for easy translation of the website content into multiple languages.

### Proposed Solution
Integrating i18next would involve adding the necessary configuration, libraries, and components to enable internationalization support within the project. This would include language files, language switchers, and proper handling of translated content.

### Benefits
- Improved user experience for international visitors by providing content in their native language.
- Increased reach and accessibility for non-English speaking users.
- Easier maintenance and management of translated content.

### Related Work
It seems that there are existing resources and examples available on how to integrate i18next with Next.js applications. Some potential references that could be helpful:
- [Official i18next documentation](https://www.i18next.com/)
- [Next.js internationalization example](https://github.com/vercel/next.js/tree/canary/examples/with-next-translate)
- [Next.js i18next starter template](https://github.com/isaachinman/next-i18next-starter)

### Additional Context
Please let me know if there is any additional information or clarification required regarding this feature request. I would be happy to provide further details or assist with the implementation if needed.

Thank you for considering this feature request!

**Comment by timlrx** [comment]
Currently the first priority would be to migrate to next 13 with app dir and react server components. Maybe someone from the community could make a i18n fork of it afterwards similar to the v1 version of the blog.

**Comment by PxlSyl** [comment]
Hello, I started to work on it a few days ago (en and fr). Almost finished (still some work to do), but getting a bug, or perhaps a misunderstanding on my part. At this point everything is working, except when the user clicks on a post to display it : I'm getting an error related to Pliny : 

Error: Cannot read properties of undefined (reading 'default')

Call Stack
default)
node_modules\pliny\mdx-components.js (10:37)

 So if there's some people interested to help and conttribute, it would be great and I'm publishing the repo with the bug right now. At least, it will show interested people how i18n works with the app router and how to globally set it up
