### ISSUE TITLE
Unhandled Runtime Error TypeError: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by krishnakanthpps** [timlrx/tailwind-nextjs-starter-blog#649]
**Describe the bug**
Getting this error :  When running the application on pm2.

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'includes')

Call Stack
resolveDynamicRoute
node_modules/next/dist/shared/lib/router/router.js (264:15)
_callee$
node_modules/next/dist/shared/lib/router/router.js (1066:30)
tryCatch
node_modules/next/dist/compiled/regenerator-runtime/runtime.js (45:15)
Generator.invoke [as _invoke]
node_modules/next/dist/compiled/regenerator-runtime/runtime.js (274:0)
prototype.<computed> [as next]
node_modules/next/dist/compiled/regenerator-runtime/runtime.js (97:0)
asyncGeneratorStep
webpack-internal:///./node_modules/next/dist/shared/lib/router/router.js (13:28)
_next
webpack-internal:///./node_modules/next/dist/shared/lib/router/router.js (31:17)

**To Reproduce**
Installed and Ran the blog on ubuntu OS. IT was working fine till yesterday. But suddenly this issue after a restart. 

Any ideas how to debug on where to find the issue is.

**Comment by timlrx** [comment]
No idea on deployment issues especially if it was working fine previously. Try restarting or asking in nextjs github.

**Comment by krishnakanthpps** [comment]
was an issue with the nginx settings. found the answer in nextjs github. Thank you
