### ISSUE TITLE
how to change port on production?

### ISSUE THREAD

**Issue by anastasiyamykolenko** [timlrx/tailwind-nextjs-starter-blog#65]
I have a problem with change port on production:
I added to package.json:
`    "start": "cross-env TAILWIND_MODE=watch next-remote-watch -p 3011 ./data",`
But it is not working, also not working npm run start -- -p 3011, the app still running in localhost:3000.

Can anyone help me?

**Comment by timlrx** [comment]
for `next-remote-watch` -p is the polling option. You can do `PORT=3011 TAILWIND_MODE=watch next-remote-watch ./data`
