### ISSUE TITLE
Enable SSG with Cloudinary for Image Optimization

### ISSUE THREAD

**Issue by mmccarthy404** [timlrx/tailwind-nextjs-starter-blog#650]
I don't need to have SSR for my blog, and would prefer to deploy it as a static site to AWS S3 for cost savings and fast load times. Currently, when running `next export` post build, an error is thrown due to `next/image`'s default image loader:
```
Error: Image Optimization using Next.js' default loader is not compatible with next export.
```

Ideally, a user could toggle between building a SSR site vs a SSG site. If building a SSG site, it would work with Cloudinary for static export image optimization like described here: https://nextjs.org/docs/pages/building-your-application/deploying/static-exports

**Comment by mmccarthy404** [comment]
Also, related, are there any other modifications needed to export the build as a static site? I've noticed that 'Subscribe to newsletter' and 'Comments' don't seem to work I'm guessing that there are other things breaking that I don't realize? Here's a demo deployment of the tailwind-nextjs-starter-blog as a static site in S3 (the only modification is this https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/231#issuecomment-915277585): https://d1xs66xjoxwam2.cloudfront.net/

**Comment by timlrx** [comment]
Other than the line specified in https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/231#issuecomment-915277585, you would need to delete the `pages/api` section as well as all `Newsletter` components since that relies on the internal api.  Comments should work fine since it relies on external services.

**Comment by timlrx** [comment]
I am in the midst of updating the template to use the new app directory setup. Would try to include a guide on how to create a static build after it.

**Comment by mmccarthy404** [comment]
If there are any items you'd like community help for please let me know!

**Comment by timlrx** [comment]
> @timlrx I'm wondering if there's any update on building this template as a static site with the release of v2.0?

Yes, check out the guide over here under the static hosting services section: https://github.com/timlrx/tailwind-nextjs-starter-blog#deploy

**Comment by mmccarthy404** [comment]
@timlrx in the new documentation you recommend adding `output: 'export'` in `next.config.js`, however when running `yarn build` I get an error thrown due to custom headers:  https://nextjs.org/docs/messages/export-no-custom-routes

Would you also recommend removing these security headers in `next.config.js`? Do they even work without a server?

**Comment by timlrx** [comment]
Yes, you are right. We have to remove the headers section in `next.config.js` as well. They don't work with a static build. I have updated the docs to reflect that.
