### ISSUE TITLE
Remove sample website

### ISSUE THREAD

**Issue by inwonakng** [timlrx/tailwind-nextjs-starter-blog#651]
Hi, I was looking through list of demo websites and noticed that [https://www.fiqrychoerudin.dev/](https://www.fiqrychoerudin.dev/) now leads to a spam website. Can this be removed?

**Comment by inwonakng** [comment]
[https://www.kittan.ru/](https://www.kittan.ru/)
[https://ghali.dev/](https://ghali.dev/)

also appear to have the same issue

**Comment by timlrx** [comment]
Most certainly, I have removed them from the readme. Thanks for letting me know.
