### ISSUE TITLE
Users rating and AggregateRating snippet

### ISSUE THREAD

**Issue by iliamrv** [timlrx/tailwind-nextjs-starter-blog#653]
I know that this feature may not be useful to everyone, but nevertheless it is needed on websites that have product reviews, recipes and other articles where user ratings are important. 

Schema allows you to output a metric like AggregateRating based on the average user rating. 

https://developers.google.com/search/docs/appearance/structured-data/review-snippet

However, I have not found a solution for React / Next js to save user ratings (e.g. in a database) and display it via Schema / JSON. 

Is there any way to do it?

**Comment by timlrx** [comment]
Same as https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/730
