### ISSUE TITLE
Error with quick start

### ISSUE THREAD

**Issue by yavuzsonmez** [timlrx/tailwind-nextjs-starter-blog#659]
When running the command: `pliny new --template=starter-blog my-blog` and choosing TypeScript, I am getting the following error:

`Could not locate the repository for "https://github.com/timlrx/pliny". Please check that the repository exists and try again`

**Comment by timlrx** [comment]
Thanks, I am in the midst of updating both pliny and this repository. The updated version, releasing soon is available on the v2 branch - https://github.com/timlrx/tailwind-nextjs-starter-blog/tree/v2

**Comment by timlrx** [comment]
It works with yarn since I added the node resolutions over there but if you are using npm you need to add overrides. See this issue for workarounds - https://github.com/contentlayerdev/contentlayer/issues/506

**Comment by yavuzsonmez** [comment]
I just used yarn at the end. But thank you @timlrx and @ttys3
