### ISSUE TITLE
What is siteMetadata.image currently used for in the application?

### ISSUE THREAD

**Issue by mmccarthy404** [timlrx/tailwind-nextjs-starter-blog#661]
siteMetadata has a property image seen here:
https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/data/siteMetadata.js#L11

Looking through the rest of the application, this property doesn't seem to have a use and is perhaps deprecated with the author avatars: https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/data/authors/default.md?plain=1#L3

Interested in what this property is used for!

**Comment by timlrx** [comment]
Yes, you are right, it's no longer being used! Will remove this property, thanks.
