### ISSUE TITLE
Trying to add Plausible Analytics 404 Goal (custom event) to 404.js .. and failing badly.

### ISSUE THREAD

**Issue by sjwaight** [timlrx/tailwind-nextjs-starter-blog#662]
I'm trying to add the 404 tracking event to the 404.js file that is rendered for a non-existent file.

I am following the Plausible guide for this from [their site](https://plausible.io/docs/error-pages-tracking-404) and no matter what combo of code I drop in I can't get it to publish the goal.

I can see the standard page view event fire, but I'd love to be able to add a '404' as well for any missing page.

I'm sure it's a really easy fix for someone who knows their way around JavaScript :)

**Comment by timlrx** [comment]
Have not tried it out, but I think you can add the following component to your `not-found` or 404 page.

```js
<Script id="plausible-404-script">
        {`
            window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }
        `}
</Script>
```

**Comment by sjwaight** [comment]
I had that and wasn't seeing it functioning, though that might have just been me being impatient with things. Thanks @timlrx for taking the time to respond!

**Comment by sjwaight** [comment]
Interestingly it doesn't fire the event. I wonder if the Lazy Loading of the plausible JS is the root cause. I can see the standard 'pageview' event fire, but not the call to 404.

**Comment by timlrx** [comment]
Hmm, not too sure about it. Maybe the folks over at plausible would have a better idea on this.

**Comment by sjwaight** [comment]
Just came here to add the missing bit was adding lazyLoading (which I thought I had already done). I could probably do away with 'window' reference, but this works... so I'm going to leave it!

```mdx
<Script id="plausible-404-script" strategy="lazyOnload">
  {`
      window.plausible?.("404",{ props: { path: document.location.pathname } });
  `}
</Script>
```
