### ISSUE TITLE
Bug in reloading blog posts on Firefox

### ISSUE THREAD

**Issue by t03i** [timlrx/tailwind-nextjs-starter-blog#663]
**Describe the bug**

On the v2 branch using yarn locally in Firefox: When I reload a blog post, Next.js throws an error: ` SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`  alongside a:

```
error app/blog/[...slug]/page.tsx (84:22) @ structuredData
- error TypeError: Cannot read properties of undefined (reading 'structuredData')
    at Page (./app/blog/[...slug]/page.tsx:101:25)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
```

I tried to track the issue down, and it appears that the page is rendered twice with the `search.json`  slug before the actual slug is used.  This seems to only happen in Firefox; Chrome is fine.

**To Reproduce**
1. Go to an arbitrary blog post using Firefox (115.0.2) 
2. Reload the page

**System Info (if dev / build issue):**
 - OS: arch Linux
 - Node version: 18.16.0
 - Yarn version: 3.6.1

**Browser Info (if display / formatting issue):**
- Device Desktop
- Browser Firefox 
- Version 115.0.2

Do you have any pointers about what could go wrong here?
Thanks for looking into it!

**Comment by timlrx** [comment]
Thanks for reporting this bug. It's due to `search.json` being loaded relative to the page rather than the base url. So it only loads correctly in the home page. Will fix it in the next pliny version.

**Comment by timlrx** [comment]
Fixed in the latest update on the branch!

**Comment by t03i** [comment]
Can confirm. 
Thanks for being so responsive and maintaining this outstanding blog template!
