### ISSUE TITLE
Giscus and Disqus has already been set up properly, but doesn't work

### ISSUE THREAD

**Issue by yoomiraa** [timlrx/tailwind-nextjs-starter-blog#664]
![image](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/124776067/429ebcfb-15fc-491b-868c-0f404b26d425)
giscus keeps on loading forever and disqus does not appear even though I have already set up the values in .env

**Comment by timlrx** [comment]
Are you testing it with the latest version over at https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/658?

**Comment by yoomiraa** [comment]
> Are you testing it with the latest version over at #658?

hm.. I just used the template from vercel, is it not the latest version?

**Comment by timlrx** [comment]
Which template is vercel linking? I guess it is to the master branch? I will be merging the latest changes to master shortly after updating the docs. If you are starting from fresh, I would recommend going with the new one :)

**Comment by yoomiraa** [comment]
> Which template is vercel linking? I guess it is to the master branch? I will be merging the latest changes to master shortly after updating the docs. If you are starting from fresh, I would recommend going with the new one :)

It must've been the master branch. I will be waiting for the new one version, buddy! Thank you
