### ISSUE TITLE
rss feed should be named differently than index.xml

### ISSUE THREAD

**Issue by ThangHuuVu** [timlrx/tailwind-nextjs-starter-blog#67]
Title. Sometime when I deploy to vercel and go to the main page, I got the rss feed instead of my homepage. This is because the feed is named `index.xml`. Rename it to something else E.G `feed.xml` fixes the issue for me.

**Comment by timlrx** [comment]
Same issue as my blog. See previous issue - https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/16

It's a vercel issue. Currently, the recommended approach is to use a re-direct. We could consider changing the to `feed.xml` or something else for new users.

**Comment by DoctorDerek** [comment]
Maybe that PR #17 should just be merged into the template for the redirect?

**Comment by timlrx** [comment]
Yup, would do that later today

**Comment by timlrx** [comment]
Patch merged to master and v1 - https://github.com/timlrx/tailwind-nextjs-starter-blog/commit/5945a724913f7313c9b58ce6dfaa917901828b25
