### ISSUE TITLE
search.json not found for kbar search on site deployed on sub-path

### ISSUE THREAD

**Issue by marekfs** [timlrx/tailwind-nextjs-starter-blog#684]
**Describe the bug**
`search.json` (kbar) cannot be found on static site deployed to github pages.

**To Reproduce**

Deploy to github pages making sure that you set `basePath` correctly.

**Expected behavior**
`searchDocumentsPath` prepends `basePath` configuration.

e.g.

https://marekfs.github.io/blog/search.json

instead of

https://marekfs.github.io/search.json

**Screenshots**
You can see the problem here:
https://marekfs.github.io/blog

**System Info (if dev / build issue):**

- OS: Ubuntu 22.04.2
- Node version 16.20.1
- Npm version 9.8.1

**Browser Info (if display / formatting issue):**
N/A

**Comment by timlrx** [comment]
Hi @marekfs, by default it constructs the path from `window.location.origin`. You can modify the `searchDocumentsPath` prop in the [config](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/main/data/siteMetadata.js#L78) to `blog/search.json` or the absolute path. Either should work.

**Comment by marekfs** [comment]
Hi @timlrx . Thanks for your response. I found the issue was in `contentlayer.config.ts`. I removed `searchDocumentsPath` where the search index is created and the deployment was successful.
