### ISSUE TITLE
Unbound variable "PWD"

### ISSUE THREAD

**Issue by thaison316** [timlrx/tailwind-nextjs-starter-blog#686]
I followed the starting guide after cloning the repo.
yarn to install but got Unbound variable "PWD" when try yarn dev.

deleted the repo and reclone but still getting the same thing.  Any else got this ?

**Comment by timlrx** [comment]
I am not able to replicate this error on a fresh clone

**Comment by thekoc** [comment]
you can set it manually by typing 

`export PWD="$(pwd)" `

**Comment by fhnasgf28** [comment]
hello, sorry I want to ask about the error "Unbound Variable 'PWD', where should I solve the problem. Thank you

**Comment by YWzzy** [comment]
windows,typing
`$Env:PWD = Get-Location
`
