### ISSUE TITLE
Search box with no Korean support

### ISSUE THREAD

**Issue by techroider** [timlrx/tailwind-nextjs-starter-blog#689]
It's not a problem in v1. In v2, there is a problem when entering Korean in the search input window.

for example : 

Normal : 감사합니다.
V2 Vug : ㄱ가감ㅅ사ㅏ합

pls check this

**Comment by timlrx** [comment]
Sorry, could you elaborate what's the problem and what search input window are you referring to?

**Comment by chasingboy95** [comment]
@techroider  @timlrx  [I had a same problem, when I try to input in Chinese, it ](https://github.com/timc1/kbar/issues/327)
seems caused by kbar

**Comment by timlrx** [comment]
Thanks, will monitor the issue and bump the version once a fix is push.

**Comment by thekoc** [comment]
> Thanks, will monitor the issue and bump the version once a fix is push.

Directly `git clone` their repository and `npm install && npm run dev` won't reproduce the problem. Chinese characters can be inputed correctly, as their developer [recorded](https://github.com/timc1/kbar/issues/327#issuecomment-1681142576).

I've tested it and can confirm if I run a untouched `kbar` project no problem inputing Chinese, while running a untouched `starter-blog` project the problem occurs.

Could it be a configuration issue when `pliny` calls Kbar?

**Comment by timlrx** [comment]
The simple code sandbox also shows the issue so I doubt it is a configuration issue.

**Comment by timlrx** [comment]
Waiting for this to be merged - https://github.com/timc1/kbar/pull/335

**Comment by techroider** [comment]
Thank you for support!

**Comment by timlrx** [comment]
Will close it after kbar is updated and everything is updated, it is still not working for the time being :)

**Comment by yuis-ice** [comment]
Note: While I believe that the issue is from the same root, the similar glitch happens on Japanese text input as well, on the phones and PCs.

**Comment by Aqours** [comment]
This issue has been fixed in kbar@0.1.0-beta.44

**Comment by ryuni-dev** [comment]
I still have the same problem in Korean...🥹

**Comment by Aqours** [comment]
Temp solution:
 
yarn(default):
add `"kbar": "0.1.0-beta.44"` to package.resolutions
```json
  "resolutions": {
    "kbar": "0.1.0-beta.44"
  },
```

pnpm(tested):
add pnpm filed to package.json 
```json
"pnpm": {
    "overrides": {
      "pliny>kbar": "npm:kbar@0.1.0-beta.44"
    }
  }
```

then run yarn/pnpm install cmd to update lockfile

**Comment by ryuni-dev** [comment]
Thank you so much! It works now :)

**Comment by timlrx** [comment]
I have updated pliny to the latest kbar version. Upgrade to v0.1.6 to fix the issue.
