### ISSUE TITLE
Unable to register on buttondown

### ISSUE THREAD

**Issue by edmondtam1** [timlrx/tailwind-nextjs-starter-blog#690]
**Describe the bug**

- Fresh clone of the template doesn't work with `buttondown`, both locally and deployed on Netlify

**To Reproduce**

1. Clone and start the repo
2. Update `siteMetadata.js` to use newsletter provider `buttondown`
3. Add `BUTTONDOWN_API_KEY` to `.env.local`
4. Enter an email in the subscription box
5. Receive the default error `Your e-mail address is invalid or you are already subscribed!`

**Expected behavior**

- Receive a successful subscription for a new email address

**Screenshots**

<img width="209" alt="image" src="https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/11762093/05d1f18f-35da-42bb-b421-0382876c6cdb">
<img width="301" alt="image" src="https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/11762093/39475303-ed4c-4953-a661-b1a852959bb1">

**Additional context**

Thanks for the wonderful template, it's been a joy to work with this. I have added the relevant details and, because of the use of `/api/newsletter` to do the server-side handler, I couldn't inject some `console.log` statements to see where the issue is within the `pliny` package. Any help will be much appreciated!

**Comment by timlrx** [comment]
Seems like buttondown flags `abc@gmail.com` automatically - that's why it returns an error. I tried a fresh clone with another email and it works.
