### ISSUE TITLE
is `next-compose-plugins` still being used?

### ISSUE THREAD

**Issue by bboydflo** [timlrx/tailwind-nextjs-starter-blog#70]
Hi, and thanks for this project. I am trying to understand how this project works so I am doing some research. I am quite new to Next.js and many of the tools that this project uses.

I stumbled upon a package called `next-compose-plugins` and I was wondering if this is still being used.

I also saw there is another issue here regarding some features for the v1 of this project. I can +1 on Documentation, especially on how all the packages work together and maybe even how did you come up with this solution? As I said I am very new to all this so I am looking forward to understand and learn more about how it's done.

**Comment by timlrx** [comment]
Hi, you're right, it's not being used. Will remove it, thanks.

This project is fairly standard next.js, e.g. page-based routing, static-rendering, next/link, next/images and they have a really good documentation page so I don't feel it's worth my time to explain various parts. For some features that require more explanation, I write them up in the blog itself (e.g. new v1 features). 

The other big part of the project is [next-mdx-remote](https://github.com/hashicorp/next-mdx-remote) which is used to take the markdown contents and convert them to html blog posts. It's a much more flexible approach to data sourcing than next/mdx which goes through webpack. There's a bunch of remark and rehype libraries to convert the markdown doc into html with other fancy add ons like syntax highlighting and automatic title links.

Lastly, we use tailwindcss for styling, which is quite popular and has a great documentation page as well.

There are many other blogs that take a similar approach. I just combine them all together and make sure that it works so you can have a fully-featured blog with minimal effort :)

A nice thing is that unlike Gatsby or other static site generators, there's very little magic beyond this code, so if you want to further customize it or understand a part in more detail, it's relatively straightforward to modify.

Of course, if there are further questions that you might have, simply create an issue and I will try to address it.
