### ISSUE TITLE
How to be compatible with md files in the latest version, v2.0.1

### ISSUE THREAD

**Issue by ita-code** [timlrx/tailwind-nextjs-starter-blog#703]
<img width="797" alt="image" src="https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/69387286/23e066c6-edff-450e-ad59-e54518bfc4bc">

**Comment by timlrx** [comment]
I recommend just renaming the `md` files to `mdx`. There would be more correct as the plugins are mostly meant to work with mdx files.

Alternatively, if you do you are just using strictly `md`, you can modify the `contentType` and `filePathPattern` in `defineDocumentType`. Note that certain plugins e.g. `remarkImgToJsx` might not be compatible and should be remove.

**Comment by ita-code** [comment]
Thank you. I know what to do.

**Comment by timlrx** [comment]
@ita-code any reasons for reopening this issue?

**Comment by stepcellwolf** [comment]
@timlrx is there possibility to use both contentTypes, md and mdx? I tried to adjust the settings in <contentlayer.config.ts> but it is still not working by adding md:
`filePathPattern: 'blog/**/*.mdx','blog/**/*.md',
  contentType: 'mdx','md',`

Any workaround to this problem? I have > 150 md files.

**Comment by timlrx** [comment]
> @timlrx is there possibility to use both contentTypes, md and mdx? I tried to adjust the settings in <contentlayer.config.ts> but it is still not working by adding md: `filePathPattern: 'blog/**/*.mdx','blog/**/*.md', contentType: 'mdx','md',`
> 
> Any workaround to this problem? I have > 150 md files.

I think you can glob the file path patterns but there might be further issues with parsing iirc. Easiest way would be renaming. Here's a script generated from gpt that might help:
```js
const { readdir, rename } = require('fs').promises;
const path = require('path');

async function renameMdToMdx(directoryPath) {
  try {
    const files = await readdir(directoryPath);
    for (const file of files) {
      if (file.endsWith('.md')) {
        const oldFilePath = path.join(directoryPath, file);
        const newFileName = file.replace('.md', '.mdx');
        const newFilePath = path.join(directoryPath, newFileName);
        await rename(oldFilePath, newFilePath);
        console.log(`Renamed ${file} to ${newFileName}`);
      }
    }
  } catch (err) {
    console.error('Error:', err);
  }
}

// Usage example
const directoryPath = '/path/to/your/directory';
renameMdToMdx(directoryPath);
```
