### ISSUE TITLE
worning when pnpm  is used

### ISSUE THREAD

**Issue by luz33c** [timlrx/tailwind-nextjs-starter-blog#711]
I removed  `"packageManager": "yarn@3.6.1"`  in package.json
then I run:
pnpm install 
pnpm dev
Then  I  look that in brower devtool :
<img width="1457" alt="image" src="https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/62172559/13e2387d-63d3-43c2-8cb7-76b1194f140a">

**Comment by timlrx** [comment]
Not sure about this as the project was configured to use yarn

**Comment by aolyang** [comment]
I switch to pnpm successfully,  win/mac/cloud debian linux, no error like this.

if you have installed by yarn before, or use nvm (node version manager),  please consider: 
1. **checkout node version first** (this will cause next or next plugin error, but error message can not lead you to this), probably you need restart your ternimal.
2. checkout pnpm version
3. restart next server (reinstall next or all modules if needed)

hopefully this will help.
