### ISSUE TITLE
Is there any way to automatically count the number of posts through tags?

### ISSUE THREAD

**Issue by tqt97** [timlrx/tailwind-nextjs-starter-blog#719]
The number change when we edit in app/tag-data.json

**Comment by timlrx** [comment]
Sorry if it was not clear but `app/tag-data.json` is automatically generated via contentlayer, so you should not be editing that manually.

**Comment by tqt97** [comment]
i see. i use Window so Contentlayer might not work as expected. Thanks sir to reply.

**Comment by timlrx** [comment]
I think you will get this issue: https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/704. There's a workaround there but it's easier to use WSL.
