### ISSUE TITLE
svg import error when upgrading to next 11

### ISSUE THREAD

**Issue by timlrx** [timlrx/tailwind-nextjs-starter-blog#72]
See related issue: https://github.com/vercel/next.js/issues/26130

It's supposedly fixed in the canary branch, but I will wait until 11.0.1 is out before trying to patch things up. 

Posting this in case anyone is getting upgrade problems..

**Comment by Himself65** [comment]
The bug has fixed in the next version

https://github.com/vercel/next.js/pull/26281
