### ISSUE TITLE
Adding Voting widget

### ISSUE THREAD

**Issue by iliamrv** [timlrx/tailwind-nextjs-starter-blog#730]
Hi, I would like to propose a voting function on nextjs blog pages to understand if the info on the page was useful or not. I am just starting my journey in react js, and I propose the following way: store the information in a database. I have described my method in more detail here: 

https://txt-log.com/blog/like-button-nextjs

I see a few problems:

- A user can vote multiple times after page reloading
- Somehow we need to synchronize the pages from the sitemap with the database

If you can suggest a better way and implement the changes in the project, I will be glad. 

Thanks.

**Comment by timlrx** [comment]
Hi, it's possible but definitely out of scope for this project. Everyone has their preferred way to handle authorization and their favourite backend of choice. You could consider next-auth with vercel's redis store or supabase if you want a more general purpose database and consult the relevant documentations to integrate the required functionality.
