### ISSUE TITLE
 Unbound variable "PWD"  on Windows

### ISSUE THREAD

**Issue by D3bo** [timlrx/tailwind-nextjs-starter-blog#737]
**Describe the bug**
Same as #686 : got Unbound variable "PWD" when try yarn dev.
if I type $PWD  on the terminal it output correctly the actual folder $PWD: *C:\dev\blog\nextj-blog*

**work on my mac with node 16.14 and npm 8.3.1**

**To Reproduce**

1. Clone the repo
2. Run Yarn
3. Run Yarn dev

**System Info (if dev / build issue):**

- OS: Windows 11
- Node version 21
- Npm version 10.2

**Comment by timlrx** [comment]
you can set it manually by typing

```
export PWD="$(pwd)" 
```

Duplicate of https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/686

Seems like you are on Windows and might encounter this issue later on as well: https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/704

**Comment by D3bo** [comment]
> you can set it manually by typing
> 
> ```
> export PWD="$(pwd)" 
> ```
> 

As I said the variable is already recognised by the terminal

**Comment by timlrx** [comment]
Ok will add to the documentation that you might have to define it on windows

**Comment by dariusz-wozniak** [comment]
Hi @timlrx - did you add that to the docs? I don't see any occurrence of the "PWD" in the readme. Thank you :)

**Comment by mischiefCloud** [comment]
> you can set it manually by typing
> 
> ```
> export PWD="$(pwd)" 
> ```
> 
> Duplicate of #686
> 
> Seems like you are on Windows and might encounter this issue later on as well: #704

On windows it's `set PWD="$(pwd)"`

**Comment by jeffiscow2** [comment]
Im having the same problem in windows 11 and  `set PWD="$(pwd)"`  is not helping.

**Comment by anshul360** [comment]
I used `set PWD="$(pwd)"` command following with replacing `$PWD` with just `PWD` in package.json
After that followed https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/704#issuecomment-1772106953 comment

OS: Win10 Home Edition

**Comment by EpistemicPolymath** [comment]
I am still running into this issue even after applying the above fixes. Is there something I am missing? Is this still working for people?

**Comment by RayRemnant** [comment]
In VS Code, on the top right corner of your terminal, press "+" and open a "Command Prompt".

![Capture](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/49475467/3bf3d2b4-8559-46dc-a21e-39805869b9fc)

My default was set to "Powershell" and I kept receiving the same error. Hope it helps someone.

**Comment by francisaguilar21** [comment]
> In VS Code, on the top right corner of your terminal, press "+" and open a "Command Prompt".
> 
> ![Capture](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/49475467/3bf3d2b4-8559-46dc-a21e-39805869b9fc)
> 
> My default was set to "Powershell" and I kept receiving the same error. Hope it helps someone.

Thank you for this! This helped me a lot!
