### ISSUE TITLE
Add a time on published date and last modified date since this is important for SEO

### ISSUE THREAD

**Issue by saliksik** [timlrx/tailwind-nextjs-starter-blog#738]
**Suggestion: Add a time on published date and last modified date since this is important for SEO**

Search engines use the published date and last modified date of a web page to determine how fresh and relevant the content is. This is especially important for news articles and other time-sensitive content.

Currently, the published date and last modified date on Next.JS Starter Blog only display the date, not the time. This can make it difficult for search engines to accurately determine how fresh the content is.

I suggest adding a time to the published date and last modified date. This would help search engines to better understand how fresh and relevant the content is, and could lead to improved SEO performance.

Here are some of the benefits of adding a time to the published date and last modified date on GitHub:

* Improved SEO performance: Search engines use the published date and last modified date of a web page to determine how fresh and relevant the content is. Adding a time to these dates would help search engines to more accurately determine how fresh the content is, and could lead to improved SEO performance.
* More accurate information for users: The published date and last modified date of a web page can be useful for users to understand how recent the content is. Adding a time to these dates would provide users with more accurate information about the content.
* Easier to track changes: Adding a time to the published date and last modified date would make it easier to track changes to content. This could be useful for developers, project managers, and other stakeholders.
* More accurate sitemap: The sitemap is a file that lists all of the pages on a website. The sitemap is used by search engines to crawl and index a website. Adding a time to the published date and last modified date in the sitemap would help search engines to more accurately understand how fresh and relevant the content on the website is.
* More accurate open graph data: Open graph data is a set of tags that are used to describe a web page on social media. The open graph data is used by social media platforms to display information about the web page when it is shared. Adding a time to the published date and last modified date in the open graph data would help social media platforms to more accurately display information about the web page.

Here is an example of how the published and last modified date with time could be included in the open graph data:

`<meta property="og:published_time" content="2023-10-18T13:51:20+08:00">`
`<meta property="og:modified_time" content="2023-10-18T13:51:20+08:00">`

I hope you will consider my suggestion. Thank you for your time.

**Comment by timlrx** [comment]
"og:published_time" and "og:modified_time" are not valid open graph properties. Based on https://ogp.me/, the agreed upon properties are `article:published_time` and `article:modified_time`. The current website supports both of them automatically - yes even down to to the time, you just have to specify that in the article markdown via the `lastmod` property.

See https://tailwind-nextjs-starter-blog.vercel.app/blog/introducing-tailwind-nextjs-starter-blog for example. You can verify that it inserts the date information for both LD+JSON: https://validator.schema.org/#url=https%3A%2F%2Ftailwind-nextjs-starter-blog.vercel.app%2Fblog%2Fintroducing-tailwind-nextjs-starter-blog and OG meta properties

**Comment by saliksik** [comment]
I can verify that it inserts the date information but not the time. The time should be included when it was published or last modified. 
![Web capture_19-10-2023_11277_search google com](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/122975898/872b7fd2-18a0-4cd0-8383-f143bdc383d7)

More info: https://developers.google.com/search/docs/appearance/publication-dates

**Comment by timlrx** [comment]
You just have to change `date` or `lastmod` to a datetime string and it will display it accordingly: https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/main/data/blog/introducing-tailwind-nextjs-starter-blog.mdx#L4

I do not wish to automatically infer from the file itself when it was created or last modified.
