### ISSUE TITLE
Is head.tsx still used?

### ISSUE THREAD

**Issue by lucavallin** [timlrx/tailwind-nextjs-starter-blog#739]
Is [head.tsx](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/main/app/head.tsx) still used? If I make a change there, nothing really happens. That file is also not mentioned in the Next.js documentation anymore, but I have seen comments online about it becoming deprecated.

It seems the same configuration is also present in the `layout.tsx` file.

**Comment by timlrx** [comment]
Sorry for the confusion. You are right that it is deprecated and not used in the template. Please modify the `meta` and `link` tags in `layout.tsx` or `seo.tsx`. I will delete it in the next PR.
