### ISSUE TITLE
Static Generation Build Error Following Instructions on README

### ISSUE THREAD

**Issue by greynewell** [timlrx/tailwind-nextjs-starter-blog#744]
**Describe the bug**
I am unable to generate static pages following the instructions in the `README`.

**To Reproduce**
Steps to reproduce the behavior (taken from the README):

1. Add `output: 'export'` in `next.config.js`. See [static exports documentation](https://nextjs.org/docs/app/building-your-application/deploying/static-exports#configuration) for more information.
2. Comment out `headers()` from `next.config.js`.
3. Change `components/Image.tsx` to use a standard `<img>` tag instead of `next/image`:

   ```ts
   /* eslint-disable jsx-a11y/alt-text */
   /* eslint-disable @next/next/no-img-element */
   import NextImage, { ImageProps } from 'next/image'

   // @ts-ignore
   const Image = ({ ...rest }: ImageProps) => <img {...rest} />

   export default Image
   ```

   Alternatively, to continue using `next/image`, you can use an alternative image optimization provider such as Imgix, Cloudinary or Akamai. See [image optimization documentation](https://nextjs.org/docs/app/building-your-application/deploying/static-exports#image-optimization) for more details.

4. Remove `api` folder and components which call the server-side function such as the Newsletter component. Not technically required and the site will build successfully, but the APIs cannot be used as they are server-side functions.
5. Run `yarn build`. You will receive the following error:
```
> Build error occurred
Error: Page "/tags/[tag]" is missing "generateStaticParams()" so it cannot be used with "output: export" config.
    at /Users/grey/Projects/greynewell.com/node_modules/next/src/build/index.ts:1613:37
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Span.traceAsyncFn (/Users/grey/Projects/greynewell.com/node_modules/next/src/trace/trace.ts:110:14)
    at async Promise.all (index 11)
    at /Users/grey/Projects/greynewell.com/node_modules/next/src/build/index.ts:1427:9
    at Span.traceAsyncFn (/Users/grey/Projects/greynewell.com/node_modules/next/src/trace/trace.ts:110:14)
    at /Users/grey/Projects/greynewell.com/node_modules/next/src/build/index.ts:1322:11
    at Span.traceAsyncFn (/Users/grey/Projects/greynewell.com/node_modules/next/src/trace/trace.ts:110:14)
    at build (/Users/grey/Projects/greynewell.com/node_modules/next/src/build/index.ts:361:25)
    at main (/Users/grey/Projects/greynewell.com/node_modules/next/src/bin/next.ts:134:3)
```
**Expected behavior**
I expect `yarn build` to generate a static version of the blog.

**System Info (if dev / build issue):**

- OS: `macOS`
- Node version (please ensure you are using 18+) `v18.2`
- Npm version `8.9.0`

**Additional context**

**Comment by greynewell** [comment]
You can see an example of this issue occurring here:
https://github.com/greynewell/greynewell.com

Worth noting that (of course) `generateStaticParams()` _is_ in fact defined.

Another user seems to have the same issue with `next.js`:
https://github.com/vercel/next.js/issues/54393#issuecomment-1773808636

**Comment by timlrx** [comment]
Strange, I just tested it a month ago and it worked. Not sure if there was a bug introduced in the new version of next.

**Comment by greynewell** [comment]
@timlrx will give it another go with a fresh clone in the morning.

According to the comments on the Next issue I linked, error message was not displayed before, but the static files were not being generated. (I have not rolled back to test this assertion myself).

**Comment by timlrx** [comment]
@greynewell any further issues? Recently, I wrote up a guide on [deploying it to Github pages ](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/main/faq/github-pages-deployment.md)and verified that the static build process works.

**Comment by iamkroot** [comment]
Managed to get it running ([here](https://iamkroot.github.io/)) by following the guide, thanks @timlrx!

One thing though- the RSS feed is [giving a 404](https://timlrx.github.io/tailwind-nextjs-starter-blog/feed.xml) for some reason :( I do see the `feed.xml` file generated when I run `yarn build` locally and can access the file when I do a local serve, so not sure why the GH pages site is giving trouble.

**Comment by hallucinogenizer** [comment]
Anyone else still facing this issue?

**Comment by patrickstorm** [comment]
For people seeing this in the future: I was running into this, and it was because I didn't have any posts with tags. I just added a tag to one of my posts, and the builds started passing.

**Comment by greynewell** [comment]
@patrickstorm would it add value to have a descriptive error message here?

**Comment by patrickstorm** [comment]
> @patrickstorm would it add value to have a descriptive error message here?

@greynewell I suppose, but probably not worth the effort since it seems so few people run into this issue. And now if they find this github issue, they have a solution. I think the real fix would be to allow builds without any tags present.
