### ISSUE TITLE
Disqus theme switch issue

### ISSUE THREAD

**Issue by bdani93** [timlrx/tailwind-nextjs-starter-blog#754]
**Describe the bug**
I'm using the v2 template, and I have an issue with disqus when switching theme.
The first issue was it didn't inherit the dark theme background color, it was always white.
I found solution for this specific problem with adding the following line to the tailwind.css:
`#disqus_thread { color-scheme: none; }`

Now the only issue is that after clicking on the load comment and the switching theme it always inheriting the wrong theme.
So when the color should be dark it always white and vica-versa.
But for the first time it always load the correct theme, so something brokes after the first loading.

**To Reproduce**

1. Use disqus for commenting
2. For a blog page click on Load Comments
3. Switch theme

**Expected behavior**
Disqus should inherit the correct color, after the theme switch.

**Screenshots**
As you can see for the first time it always loads the correct theme:

![kép](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/36195643/6dbc2f05-6122-4463-80ba-e5c57d2b52e9)
![kép](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/36195643/c017899c-634f-4d38-bad5-6d68364ef0cf)

But after this point if you switch theme it always loads the wrong theme:

![kép](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/36195643/93c5f929-37ed-4253-a611-cfa507dd8d9e)
![kép](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/36195643/45671b59-6d01-426a-9fe6-3f932e457795)

**Browser Info (if display / formatting issue):**

- Device Tried on Mac, Android, Windows
- Browser Tried with multiple broswers (Safari, Firefox, Chrome, Duckduckgo)

**Additional context**
You can check the bug in my website:
https://zsebinformatikus-zsebinformatikus.vercel.app/

Maybe it's a bug in the pliny package, that is reseting the comments windows immidiatelly, after switching theme, and disqus getting the previous theme?
In the develeoper page I can see it always downloading the wrong theme, after the first sucessful loading. 

This is the extra data section for the disqus GET request after switching to light theme:
extra_data | {"color_scheme":"dark","anchor_color":"rgb(209,213,219)","typeface":"sans-serif","width":762}

And after switching to dark theme:
extra_data | {"color_scheme":"light","anchor_color":"rgb(55,65,81)","typeface":"sans-serif","width":762}

**Comment by timlrx** [comment]
Yes, it's a bug on the pliny component. I did not account for theme switching and reloading the script. Seems like disqus does it automatically so all that needs to be done is to force a reload: https://stackoverflow.com/questions/64960793/toggling-dark-light-mode-in-disqus

Will let you know when I fix it.

**Comment by bdani93** [comment]
I tried with the new pliny release, working as intended.
Thank you very much!

**Comment by armujahid** [comment]
I think we still have this issue. You can check https://armujahid.me/blog/tmux-basics
I get incorrect theme even without switching theme. you can select dark mode and then refresh to reproduce that issue. Not sure if anything is wrong in my config. 
![image](https://github.com/user-attachments/assets/01b7b731-11d1-4732-b9d6-fd0e8ceb4b9c)

**Comment by bdani93** [comment]
> I think we still have this issue. You can check https://armujahid.me/blog/tmux-basics I get incorrect theme even without switching theme. you can select dark mode and then refresh to reproduce that issue. Not sure if anything is wrong in my config. Note that disqus color scheme is Auto. ![image](https://private-user-images.githubusercontent.com/3725386/362423154-01b7b731-11d1-4732-b9d6-fd0e8ceb4b9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MzE0ODgsIm5iZiI6MTcyNDkzMTE4OCwicGF0aCI6Ii8zNzI1Mzg2LzM2MjQyMzE1NC0wMWI3YjczMS0xMWQxLTQ3MzItYjlkNi1mZDBlOGNlYjRiOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMTEzMzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDZiNTQxYzFiOTljNDk2NzQ4ZTY2OWJiZmJlM2I0YTM2N2E2YjM0NGY3OWUzZWVhZTMyNjgxYmUxMjEzN2JhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NwWPWgtEcAxIPatOeRGnhxNF23hqURWJiZ_3qlpST98)

I checked my config and the 
#disqus_thread { color-scheme: none; } 
line is still in the tailwind.css

Could you check and try with it?
Could you check which pliny version that you're using?
