### ISSUE TITLE
Citation (rehype-citation) does not work

### ISSUE THREAD

**Issue by dariusz-wozniak** [timlrx/tailwind-nextjs-starter-blog#755]
**Describe the bug**

I have added the following text to the .mdx file: `Check citations.[@Nash1950]`

The .bib file remains untouched and it contains Nash1950:

```
@article{Nash1950,
  title={Equilibrium points in n-person games},
  author={Nash, John},
  journal={Proceedings of the national academy of sciences},
  volume={36},
  number={1},
  pages={48--49},
  year={1950},
  publisher={USA}
}
```

Citation does not work. Rendered markdown does not recognize it:

![image](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/5969160/c41c8b59-85c6-4229-b7f7-c655828e4632)

**To Reproduce**
- See the branch code: https://github.com/dariusz-wozniak/dariuszwozniak.net-v2/pull/8
- And deployed version: https://dariuszwozniak-net-v2-git-feat-6c2f69-dariusz-wozniaks-projects.vercel.app/blog/2023-11-02-hello-world

**Expected behavior**

Citation should work.

**System Info (if dev / build issue):**

- OS: (Vercel one)
- Node version: 18.x

**Browser Info (if display / formatting issue):**

Any

**Additional context**

No

**Comment by timlrx** [comment]
You will need to add the location of the bib file to the frontmatter i.e. `bibliography: references-data.bib` like https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/12b4ed236fd75d59f2941b651d83d180f611c92e/data/blog/new-features-in-v1.mdx#L9C1-L9C34.

Or if you prefer to use one BibTex file for all posts, you can also add it to the [options in the plugin](https://github.com/timlrx/rehype-citation#optionsbibliography).

**Comment by dariusz-wozniak** [comment]
@timlrx : works like a charm, thank you!
