### ISSUE TITLE
Need help with importing images in mdx files.

### ISSUE THREAD

**Issue by linuxdotexe** [timlrx/tailwind-nextjs-starter-blog#781]
Hello, I'm reletively new to Next.js and I really appreciate your template. I used it to start a blog and wanted to add a component to use in my posts.

The component contains an image that I configured to be passed as a prop. In a .tsx file, I am able to import the image as follows:
```
import img from '@/data/tracks/track1.png'
```

and pass it as a prop. It works. I do the same thing in the .mdx file I want to use this in, I am getting the following error:

```
X [ERROR] No loader is configured for ".png" files: data/tracks/track1.png
```

I know I am doing something wrong here, but I am not able to figure out what that is. I googled the error and I tried a few things I found and nothing seem to work. Can you please guide me on how I can fix this error, or even a different approach to the image importing? Thanks in advance.

**Comment by linuxdotexe** [comment]
Bringing an image into the blog would work like this, but I want to pass the image I import to a component I want to use in the blog. This image will change for each blog so I can't add the link in the component.

Or if there is a more optimal way to approach the component creation, please advice. Thanks in advance.

**Comment by timlrx** [comment]
You can import or register and use a MDX component in the blog, but you still would not be able to import images like what you are doing above. That requires additional bundling magic that is not available in the MDX compiler. Pass the location of the image in the public folder or from an external host.
