### ISSUE TITLE
Add asciinema player

### ISSUE THREAD

**Issue by phannhat17** [timlrx/tailwind-nextjs-starter-blog#782]
[asciinema](https://asciinema.org/) is a free and open source solution for recording terminal sessions and sharing them on the web.

I want to add asciinema player to blog post but I'm not familiar with tsx and nextjs. Has anyone done it or knows how to do it? Pls help me

**Comment by timlrx** [comment]
You can try it with https://github.com/timlrx/remark-webembed. See https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/618#issuecomment-1776504085 for more details.
