### ISSUE TITLE
how to set ` invisiable?

### ISSUE THREAD

**Issue by JcobCN** [timlrx/tailwind-nextjs-starter-blog#786]
![image](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/19268110/7a020327-fbbb-4eab-b9f0-a3ead3cd2f99)

how to set \` something...\' invisible?  like github `just hightlight or render blackground color`

**Comment by timlrx** [comment]
Modify tailwind config like so: https://stackoverflow.com/a/70267619

**Comment by JcobCN** [comment]
thx
