### ISSUE TITLE
What happened to `scripts/compose.js`?

### ISSUE THREAD

**Issue by arximughal** [timlrx/tailwind-nextjs-starter-blog#789]
I had recently upgraded my blog from a very older version to the latest one and realized that `scripts/compose.js` is no where to find. 

Did you guys decide to completely ditch it? Or am I missing something and cannot locate it?

**Comment by timlrx** [comment]
Sorry about that, I felt it was not really needed and it's easier to just copy an existing markdown file and edit from there. If you want to re-introduce it for your own blog, the script should still work. You can get it from the [last updated v1 tag](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/v1.5.6/scripts/compose.js)

**Comment by arximughal** [comment]
No problem at all. I will try this script out and see if it works. Otherwise, I guess I can just copy/past like everyone else 😂
