### ISSUE TITLE
Is there a part of writing markdown files where I apply a different thumbnail to each file?

### ISSUE THREAD

**Issue by HA-SEUNG-JEONG** [timlrx/tailwind-nextjs-starter-blog#791]
Every time I write a markdown blog, I want to apply a different thumbnail to each blog.

I added `images` but thumbnail can't see..

// markdown file

---
title: xxxx
date: '2023-09-27'
tags: ['markdown', 'canada', 'images']
draft: false
layout: PostBanner
images: ['/static/images/minutes.jpg']
summary: xxxx
---

my repo: https://github.com/HA-SEUNG-JEONG/nextjs-blog-v2

production link : https://haseung.vercel.app/blog/%20%EC%9E%85%EC%82%AC%20%ED%95%9C%EB%8B%AC%20%EC%B0%A8%20%ED%9A%8C%EA%B3%A0

**Comment by timlrx** [comment]
By thumbnail, you mean the box in orange? That's not supported by default, it's just my preference for a more minimalist style but you could modify `Main.tsx`, to [get the image from the post](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/main/app/Main.tsx#L24C42-L24C42) and render it there.
![CleanShot 2023-12-09 at 15 33 48@2x](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/28362229/ed06b2e6-da0c-4a99-a720-81b740ead337)

**Comment by HA-SEUNG-JEONG** [comment]
Thanks!
