### ISSUE TITLE
Expected component `DonutChart` to be defined

### ISSUE THREAD

**Issue by yuis-ice** [timlrx/tailwind-nextjs-starter-blog#794]
**Describe the bug**

Despite of the document, [tailwind-nextjs-starter-blog/faq/custom-mdx-component.md at main · timlrx/tailwind-nextjs-starter-blog](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/main/faq/custom-mdx-component.md), the custom components do not work on the author mdx files (e.g. ./data/authors/default.mdx), while for blog posts it does work as described.

**Comment by timlrx** [comment]
This was intentional on my part - you could include the relevant components for each section and it does not have to be the same.
