### ISSUE TITLE
If summary is too long it will hide the entire blog

### ISSUE THREAD

**Issue by BrentFM** [timlrx/tailwind-nextjs-starter-blog#799]
When writing a few blogs, I noticed when the summary was too long, it would just hide the specific blog (Not shown anywhere).

**To Reproduce**
I havent made significant changes to this so I believe this should occur for everyone - If not I can try to dig into what I've changed!

**Expected behavior**
Just cut off at a certain limit

- Device - Mac
- Browser - Edge

**Additional context**
Inside of Main.tsx (within App), I did:
{summary.length > 149 ? `${summary.substring(0, 149)}...` : summary}

instead of
{summary}

**Comment by timlrx** [comment]
This was intentional. I feel that it is better for a user to edit the summary to an appropriate length without having it be arbitrarily truncated. If you prefer to do it automatically, your suggested change works well!
