### ISSUE TITLE
How do to change font family for this theme

### ISSUE THREAD

**Issue by kmyn** [timlrx/tailwind-nextjs-starter-blog#8]
Hi,

I'm trying to change the font family of this theme. How do I do it? I tried changing it in `tailwind.config.js` to -

```
      fontFamily: {
        //sans: ['Inter', ...defaultTheme.fontFamily.sans],
        serif: ['Literata', 'Georgia', 'Times New Roman', 'serif', ...defaultTheme.fontFamily.serif],
      },
```
and running `npm run dev` that does not seem to have any effect.

Thanks.

**Comment by timlrx** [comment]
Hi,

Have you also updated `_document.js` to import the font from google? https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/pages/_document.js

I believe sans is the default font as well so if you want to use serif you would need to modify the body to include the correct class `<body class="font-serif">`

**Comment by kmyn** [comment]
this this works now. Thanks @timlrx
