### ISSUE TITLE
Is there a good way to display the changes to the post on the website in real time?

### ISSUE THREAD

**Issue by KangodYan** [timlrx/tailwind-nextjs-starter-blog#800]
**Is your feature request related to a problem? Please describe.**

When I used it, I found that the MDX file is always static, and some changes on the file need to be rebuilt.

**Describe the solution you'd like**

Display on the website in real time after every mdx update.

**Describe alternatives you've considered**

I am currently thinking of putting mdx files in the public directory, although this can be achieved, but as far as I know it will affect SEO, and it is not very safe.

**Additional context**

It's actually acceptable even if the articles are not updated in real-time, so I would also like to ask you if you need to rebuild the project after modifying or adding articles on github.

**Comment by timlrx** [comment]
Yes, currently it rebuilds each time content is added. You could refactor the site to use Server Side Rendering or Incremental Static Regeneration instead. The trade-off over there is that it would no longer be able to create a static build and hosting the site is more challenging. I don't see an out of the box solution to support both rendering modes, so if you are interested you would need to reference the Next.js docs and make the appropriate changes.

**Comment by KangodYan** [comment]
Sorry for not replying for so long, thank you for your answer, it was very helpful for me.
