### ISSUE TITLE
Navigation and Scrolling Issues in Responsive Blog Template

### ISSUE THREAD

**Issue by Bamschool** [timlrx/tailwind-nextjs-starter-blog#803]
Hi! Thank you so much for making those templates for people. 

I found some issues. 

Context & Functionality: In the blog template, there are options to navigate to the previous ('PRE') and next ('NEXT') blog posts. The navigation links are responsive, appearing on the left side in wide screen layouts and at the bottom of the post content in narrow screen layouts.

Observed Issue: When using the template in a narrow screen layout (where navigation links are positioned at the bottom), clicking on the 'next'(under Next Article) link to navigate to the following blog post results in an unexpected scrolling behavior. Specifically, upon transitioning to the next page, the scrollbar automatically moves downwards, scrolling through the page content 

Thank you.

<img width="829" alt="스크린샷 2023-12-18 오후 9 55 32" src="https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/87596687/88f97d07-4450-427c-8816-7b181dae33e7">

**Comment by timlrx** [comment]
Hmm, I am not able to replicate, it always navigates and remain at the top of the page. Could you provide more details on the browser that you are using?
