### ISSUE TITLE
Error analytics umami

### ISSUE THREAD

**Issue by Karhdo** [timlrx/tailwind-nextjs-starter-blog#806]
When attempting to load the script 'https://umami.example.com/umami.js', the browser refused to load it due to a Content Security Policy violation. The specific violation is related to the 'script-src' directive, which is set to "'self' 'unsafe-eval' 'unsafe-inline' giscus.app analytics.us.umami.is". Additionally, it's noted that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

![image](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/79818873/f95c49a7-9171-444e-9b11-9c13909aad85)

![image](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/79818873/c22e1c9f-4b6e-4bd7-8eb2-b8ea38e8be41)

![image](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/79818873/4e1d0d62-dff8-4476-9abe-7cfca829a7a8)

Please, help me fix it :(((

**Comment by timlrx** [comment]
I don't see any script at the link, but in any case the instruction to fix it is right in the error message. You need to add umami.example.com to `script-src`. Please refer to https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy for more info.
