### ISSUE TITLE
Possible to generate static HTML vs XML?

### ISSUE THREAD

**Issue by akuzni2** [timlrx/tailwind-nextjs-starter-blog#81]
I'd like to get HTML outputs when running `npm run build` so I could deploy this static site to AWS S3. I noticed that the build output is XML which I'm guessing is what Vercel wants. Is there a way this can build to HTML output?

**Comment by timlrx** [comment]
> As the template uses `next/image` for image optimization, additional configurations has to be made to deploy on other popular static hosting websites like [Netlify](https://www.netlify.com/) or [Github Pages](https://pages.github.com/). An alternative image optimization provider such as Imgix, Cloudinary or Akamai has to be used. Alternatively, replace the `next/image` component with a standard `<img>` tag. See [`next/image` documentation](https://nextjs.org/docs/basic-features/image-optimization) for more details.

After making the above change you can run `next build && next export` to export it to static HTML. Check out [next js docs page](https://nextjs.org/docs/advanced-features/static-html-export) for more info.
