### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Client')

### ISSUE THREAD

**Issue by Mimileo** [timlrx/tailwind-nextjs-starter-blog#813]
**Describe the bug**
After following [vercel docs](https://nextjs.org/learn/dashboard-app/setting-up-your-database) , this error is thrown. I'm unsure how to connect to a database with the configuration of this template. Has anyone resolved this?
**To Reproduce**
1. Create and connect postgres database
2. Copy credentials from postgres to local with: vercel env pull .env.development.local
3. [Create a table in your database](https://vercel.com/docs/storage/vercel-postgres/quickstart#create-a-table-in-your-database) with provided code

**Expected behavior**
Run next dev to start your app locally
Visit the route's path in your app: http://localhost:3000/api/create-pets-table
{
  result: {
    command: "CREATE",
    fields: [],
    rowCount: null,
    rows: [],
    viaNeonFetch: true,
  },
};
Erro:
**Screenshots**
<img width="1074" alt="Screenshot 2023-12-26 at 6 04 03 PM" src="https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/16566472/b994709a-4958-40ff-b93c-0e1489e9d35a">

**System Info (if dev / build issue):**

- Node version (please ensure you are using 18+)
- Npm version

**Browser Info (if display / formatting issue):**

- Device [e.g. Desktop, iPhone6]

**Additional context**

**Comment by timlrx** [comment]
Seems like some javascript / next error unrelated to the template. Please ask it on next.js page.
