### ISSUE TITLE
[Feature Request] Customize slug with front matter

### ISSUE THREAD

**Issue by tddschn** [timlrx/tailwind-nextjs-starter-blog#815]
**Is your feature request related to a problem? Please describe.**
I wish I could customize slug for posts / pages with front matter, like this:

```yaml
slug: /post-1
# link for this page would be mydomain.com/post-1
```
```
# OR:
slug: post-1
# link for this page would be mydomain.com/<the-parent-dir-for-the-post's-relative-path-from-/data/blog>/post-1
# this is how the slug in front matter customize page URL in docusaurus
```

Sometimes the filename / path for the post file is really long, or not easy to read for non-authors, and sometimes I want to have a cool short URL for a specific page, and I wish I could do that with this feature.

**Comment by timlrx** [comment]
Hi @tddschn, unfortunately there are no plans to support this feature. The blog fully embraces the next.js file based routing approach. Breaking out of it is non-trivial.
