### ISSUE TITLE
update github slugger package to v 2.0

### ISSUE THREAD

**Issue by PxlSyl** [timlrx/tailwind-nextjs-starter-blog#817]
Hi! It's me again lol

While working on the internationalization version, I updated github-slugger to the last version.

Now, the import should looks like this : 

import { slug } from 'github-slugger'

and in rss.mjs and contentlayer.config.ts, instead of, (for example) this usage :

 const formattedTag = GithubSlugger.slug(tag)

It should be :

 const formattedTag = slug(tag)

So it's quite simple and straightforward, if anyone ever tried to update without success

**Comment by timlrx** [comment]
Thanks! There must have been some reason why I stick with v1 previously, but I will take note of it in the next dependency update.
