### ISSUE TITLE
Image syntax for videos do not work e.g. ![](/static/demo.mp4)

### ISSUE THREAD

**Issue by juskek** [timlrx/tailwind-nextjs-starter-blog#824]
**Describe the bug**
Using the following syntax throws an error: 
example.mdx
```
![](/static/demo.mp4)
```
console error
```
 [ERROR] TypeError: Cannot read properties of null (reading 'width')
...
```

**Expected behavior**
A video should be shown in the article

**Comment by juskek** [comment]
Seems like the markdown processor does not support videos in image tags? 

I used html instead:
```
<video
      width="100%"
      style={{ width: '100%', height: '100%', position: 'relative', borderRadius: '0.25rem' }}
      autoPlay
      loop
      muted
    >
      <source src={src} type={type} />
    </video>
```

**Comment by timlrx** [comment]
Yes, you are right. It's not part of the gfm spec: https://github.github.com/gfm/, though it is supported in GIthub and thus not supported by remark-gfm as well.
