### ISSUE TITLE
Help !! Navigation tabs not visible in Brave browser. 

### ISSUE THREAD

**Issue by Crazz-Zaac** [timlrx/tailwind-nextjs-starter-blog#827]
I am trying to understand this starter-blog and use it as a github page for my personal blog. Due to dependency errors, I upgraded Node to the latest version as well as other packages. 

I have no experience with Node but trying to understand. Everything worked so far but I'm finding difficult to debug this one error. In Brave browser the navigation tabs (Blog, Tags, projects, about) isn't visible except Search and Mode slider. But surprisingly when I open the localhost in Chrome it is visible. I think this is due to the Font compatibility. 

How can I resolve this? Help please!!

![Brave Browser](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/20120016/871485ef-be90-4c98-ad6c-ea88a0e46ba3)

![Chrome Browser](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/20120016/75047d50-2dd7-4836-953a-1a0343253f51)

**Comment by PxlSyl** [comment]
Hi! I don't know why the error occurs, but I'm using Brave everyday as my main browser and even did an internationalization version for this repo. So I can tell you this is not related to Brave!

**Comment by Crazz-Zaac** [comment]
> Hi! I don't know why the error occurs, but I'm using Brave everyday as my main browser and even did an internationalization version for this repo. So I can tell you this is not related to Brave!

Any idea why this issue might be arising? One more thing, does your navigation bar on both the browser have the same fonts?

**Comment by PxlSyl** [comment]
I don't use Chrome at all... But you must know that there's fallback fonts included in the code, that's mean that even if a browser don't support the main font defined by the developer, an another font will automatically be displayed instead. 

Anyway, were you able to resolve the issue?

**Comment by aryanjsingh** [comment]
<img width="978" alt="Screenshot 2024-01-20 at 9 30 43 AM" src="https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/140542415/2616ae29-9a3e-4fc6-af6c-918b8ef3227c">
Can you just turn brave shield off and try again.

**Comment by Crazz-Zaac** [comment]
![image](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/20120016/65b47c7b-f449-466f-a357-368a70cc7056)

It didn't really work bro. I'm surprised what might be the issue.

**Comment by aryanjsingh** [comment]
are you self hosting it, is it visible in the demo website provided ?

**Comment by Crazz-Zaac** [comment]
> are you self hosting it, is it visible in the demo website provided ?

I don't know what you meant by self hosting but it's localhost... it's visible in the demo website as well..
