### ISSUE TITLE
The list style is wrong

### ISSUE THREAD

**Issue by demonhunter3333** [timlrx/tailwind-nextjs-starter-blog#833]
**Describe the bug**
The list style is wrong

**To Reproduce**
Go to the demo

**Expected behavior**
Nested lists should look like this:
- item
  - subitem

But this template looks like this:

**Screenshots**
![Screenshot 2024-01-24 at 5 39 55 PM](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/43437154/7d1b3883-f203-4da3-96cb-9978bdeb13a8)

**Comment by timlrx** [comment]
Currently it's not nested, just indented. Fair enough, I could make it an actual nested list implementation.

**Comment by timlrx** [comment]
@demonhunter3333 I have updated the code, so if you install pliny 0.1.7, the TOC component is now uses an actual list implementation. However, to get the default HTML style, you would still need to override tailwind's list styling. You can do that with the new `ulClassname` prop e.g. <TOCInline toc={props.toc} exclude="Introduction" ulClassName="[&_ul]:list-[revert]"/>

**Comment by demonhunter3333** [comment]
it worked perfectly! thank you!
