### ISSUE TITLE
Gisus comment is not working

### ISSUE THREAD

**Issue by HackingGate** [timlrx/tailwind-nextjs-starter-blog#842]
**Describe the bug**

[Gisus](https://github.com/laymonage/giscus) comment is not working.

**To Reproduce**

1. Go to https://tailwind-nextjs-starter-blog.vercel.app/blog/release-of-tailwind-nextjs-starter-blog-v2.0
2. Click on 'Load Comments'
3. See error `Uncaught (in promise) ReferenceError: exports is not defined`

**Expected behavior**
The Gisus comment componet loads up and user can comment.

**Comment by timlrx** [comment]
Thanks, able to replicate, seems like the error was introduced over here: https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/838

**Comment by timlrx** [comment]
Verified that it fails on Next 14.1.0 but works on the previous version 14.0.4. Please downgrade if you are using giscus. Will check on this again when the next release is published and hopefully it will be resolved then.

**Comment by HackingGate** [comment]
I cannot verify it after downgrading to Next 14.0.4. The bug remains the same.

**Comment by HackingGate** [comment]
Thanks, I have verified downgrading to Next 14.0.4 fixes the issue on my blog instance.

**Comment by huykon** [comment]
I have same issue when using the Next v14.1.0. It's working well when downgrade to v14.0.4

**Comment by sonicoder86** [comment]
any update on this? i've posted this issue to the Gisqus repository https://github.com/giscus/giscus/issues/1322
