### ISSUE TITLE
Contentlayer is no longer maintained and causing multiple build errors on first try

### ISSUE THREAD

**Issue by eltel** [timlrx/tailwind-nextjs-starter-blog#844]
**Describe the bug**
Loads of build errors on first try due to contentlayer

**To Reproduce**
download zip of repo, open zip and npm install dependencies

**Expected behavior**
the app to build out of the box

**Screenshots**
![image](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/4655660/bba3b83b-0851-48ed-8a63-3e67f77c0620)

**System Info (if dev / build issue):**

- OS: [e.g. iOS] Linux Fedora 39, VSCode latest
- Node version (please ensure you are using 18+)
- 18.18
- Npm version
- 10.2.5

**Browser Info (if display / formatting issue):**

- Device [e.g. Desktop, iPhone6]

**Additional context**
I think V3 should abandon contentlayer if it's not being maintained/causing dependency issues

Many thanks

Terry

**Comment by eltel** [comment]
> **Describe the bug** A clear and concise description of what the bug is. Loads of build errors on first try due to contentlayer
> 
> **To Reproduce** Steps to reproduce the behavior: download zip of repo, open zip and npm install dependencies
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen. the app to build out of the box
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. ![image](https://private-user-images.githubusercontent.com/4655660/302041155-bba3b83b-0851-48ed-8a63-3e67f77c0620.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NzAzOTQsIm5iZiI6MTcwNjk3MDA5NCwicGF0aCI6Ii80NjU1NjYwLzMwMjA0MTE1NS1iYmEzYjgzYi0wODUxLTQ4ZWQtOGE2My0zZTY3Zjc3YzA2MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDNUMTQyMTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjk5Mzk3NDcwMmM1YTMwNjQyYjI0MjA3M2ViNjU0NmVhOWJhZjNmMDdmNjc1MjU3ZTFmYjQzZjEyMzE3NGRiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.X8ChGEz1obpdisbhgbb3HJvfLtp1LZsEIer4bKpYNis)
> 
> **System Info (if dev / build issue):**
> 
> * OS: [e.g. iOS] Linux Fedora 39, VSCode latest
> * Node version (please ensure you are using 18+)
> * 18.18
> * Npm version
> * 10.2.5
> 
> **Browser Info (if display / formatting issue):**
> 
> * Device [e.g. Desktop, iPhone6]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here. I think V3 should abandon contentlayer if it's not being maintained/causing dependency issues
> 
> Many thanks
> 
> Terry

OK, upon restoring the Yarn lock file and using Yarn instead of NPM (I generally find NPM far more stable on my devices) I was able to build successfully - however there are still multiple warnings for Contentlayer and I'm a littlw worried about this going forward in regards to maintaining updated dependencies, etc. Is there any news on what's happening regarding Contentlayer?

Many thanks for all your work

Terry

**Comment by timlrx** [comment]
I am trying to get it updated- https://github.com/contentlayerdev/contentlayer/pull/638, otherwise I might just maintain a fork of it.

**Comment by d90375** [comment]
@timlrx How long may it take to fix a problem with Contentlayer ? i wanna to use your blog starter kit ^^

**Comment by timlrx** [comment]
@d90375 any specific problem you faced? Or just in general. The current setup with the blog actually works fine using yarn as eltel noted above. Npm complains about some peer dependency issues but you can just skip them. On the unified / markdown packages side, you just have to use the older version of most packages as the blog does or add a `// @ts-ignore` line above every plugin as the typing have changed. 

So mostly minor inconveniences. In any case, if it were to be updated, the main change would just be to bump up the package versions - I don't expect much changes required.

**Comment by eltel** [comment]
> I am trying to get it updated- [contentlayerdev/contentlayer#638](https://github.com/contentlayerdev/contentlayer/pull/638), otherwise I might just maintain a fork of it.

That sounds like a good move. Thanks for getting back to me - looking forward to continuing to use what is, IMO, one of the best starter templates for Next.js.

Thanks again for all you do.

**Comment by cobmin** [comment]
maybe i am looking in the wrong spot but their might have been a fix made? https://github.com/tudoujunha/next-contentlayer/blob/main/components/mdx-components.tsx

**Comment by dcmalk** [comment]
Somewhere along the way I must have upgraded `remark-gfm` to v4 and this error started happening. I downgraded to v3.0.1 and it works again.

**Comment by cjambrosi** [comment]
I have the same problem with the Vercel deployment. Do you have any idea about changing the contentlayer lib to another tool? Does it indicate any?

**Comment by eltel** [comment]
> Somewhere along the way I must have upgraded `remark-gfm` to v4 and this error started happening. I downgraded to v3.0.1 and it works again.

I'll give this a try. It's a pity, though, as I like to keep my dependencies up to date as much as possible. Downgrading always seems like just sticking a Bandaid on a bigger problem and invariably leads to dependency issues further down the line.
