### ISSUE TITLE
Newsletter Color Scheme Change for Light and Dark mode. [Accessibility]

### ISSUE THREAD

**Issue by EpistemicPolymath** [timlrx/tailwind-nextjs-starter-blog#853]
**Describe the bug**
This isn't a bug specifically, but I am trying to figure out how to change the Newsletter button color scheme for dark and light mode. I updated to version 2.0 and now I am not sure how to only change the Newsletter button for light and dark mode separately like I was before. Using the Tailwind.css colors without customization usually results in color contrast issues. I just would like an explanation on how to change that now with the implementation of plini for maintaining the Newsletter. I am trying my best to make this website and template as accessible as possible. 

I am still learning about JAMStack and Next.js as I go along so, be please be patient. 

For instance, I am trying to make this button customized differently for light and dark mode. Currently in neither mode is it accessible and I am unsure how to access this component directly after the update:

**Light Mode:**
![chrome_omuOZIGkqh](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/16484276/3dc8a82f-b183-4e9a-937a-0bb71fede0ac)

**Dark Mode:**
![chrome_Bxcc5J83Od](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/16484276/75cec504-c103-4b77-bf3e-56d928e224b5)

**Comment by brohvis** [comment]
Hey there, bear with me, as I'm learning too, but - I got around this by taking a look in the repository for Pliny and when I saw this note on the Pliny page. 

> Note: The previous cli and starter template have been deprecated. Please use the new components directly in your favourite Next 13 websites.

 I then (believe the term is "scaffolded"?), took the source "NewsletterForm" that was being imported, (from [here](https://github.com/timlrx/pliny/blob/main/packages/pliny/src/ui/NewsletterForm.tsx))and then added `use client` and I was able to call and use the form and verify that it still works, as well as style the button and divs inline with tailwind. Can't speak to the "correct"ness or anything as I'm just getting started but it works and it's pretty!

**Comment by EpistemicPolymath** [comment]
Thank you for responding I will look into this solution. I appreciate you sharing it. I was discussing this in a Discord and I think this feels more like a solution that I am comfy exploring.

**Comment by EpistemicPolymath** [comment]
This fix did work and it seems to be the best solution currently. For more context I followed @brohvis suggestion and copied the NewletterForm source code from (https://github.com/timlrx/pliny/blob/main/packages/pliny/src/ui/NewsletterForm.tsx) and added it to my app directory with ``use client`` at the top. Then in Main.tsx I simply changed it to import to that file instead of from pliny.
