### ISSUE TITLE
Integrating YT video canvases in MD

### ISSUE THREAD

**Issue by artajohan369** [timlrx/tailwind-nextjs-starter-blog#863]
**Is your feature request related to a problem? Please describe.**
Currently there is no possibility to add a YT video in md

**Describe the solution you'd like**
I want it to be like in other templates like `<Youtube id="ZEe-IFezQok" title="Play:Youtube"/>`

**Describe alternatives you've considered**

**Additional context**

**Comment by rhokstar** [comment]
here's what i did: https://github.com/rhokstar/rhokstar.com/blob/main/components/YouTube.tsx

**Comment by mensenvau** [comment]
![Screenshot 2024-04-13 at 16 17 47](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/58214867/fd3919e2-a4f0-47f6-bca8-e20932245513)

I think we need to add the domain to the ContentSecurityPolicy variable in next.config.js.

**Comment by timlrx** [comment]
Yup, the approach by rhokstar works, or I have a remark-webembed plugin that you could try using as well: https://github.com/timlrx/remark-webembed

**Comment by fess932** [comment]
> Yup, the approach by rhokstar works, or I have a remark-webembed plugin that you could try using as well: https://github.com/timlrx/remark-webembed

ConfigReadError (/Users/fess932/git/blog/contentlayer.config.ts): Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/fess932/git/blog/node_modules/async/tryEach' imported from /Users/fess932/git/blog/node_modules/remark-webembed/dist/src/modules/webembed-handler.js
Did you mean to import "async/tryEach.js"?

Error

**Comment by armujahid** [comment]
> > Yup, the approach by rhokstar works, or I have a remark-webembed plugin that you could try using as well: https://github.com/timlrx/remark-webembed
> 
> ConfigReadError (/Users/fess932/git/blog/contentlayer.config.ts): Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/fess932/git/blog/node_modules/async/tryEach' imported from /Users/fess932/git/blog/node_modules/remark-webembed/dist/src/modules/webembed-handler.js Did you mean to import "async/tryEach.js"?
> 
> Error

@timlrx I can also confirm this error while using remark-webembed. Note that I have imported remark-directive before that as you mentioned at https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/618#issuecomment-1776504085

**Comment by Jaikant** [comment]
One of the changes missed by @rhokstar which I found by browsing his code is:
We also need to add the `YouTube` component mentioned by @rhokstar to the MDXComponents so it can be used by the blogs.
https://github.com/rhokstar/rhokstar.com/blob/main/components/MDXComponents.tsx

And then we need to update the content security policy in next.config.js, with youtube 

```
const ContentSecurityPolicy = `
  default-src 'self';
  script-src 'self' 'unsafe-eval' 'unsafe-inline' giscus.app analytics.umami.is;
  style-src 'self' 'unsafe-inline';
  img-src * blob: data:;
  media-src *.s3.amazonaws.com;
  connect-src *;
  font-src 'self';
  frame-src giscus.app https://www.youtube.com;
`

```
