### ISSUE TITLE
[Feature request] navbar dropdown

### ISSUE THREAD

**Issue by tddschn** [timlrx/tailwind-nextjs-starter-blog#867]
**Is your feature request related to a problem? Please describe.**

I want to add more entries to the nav bar but don't want to create too much visual cluster. A drop down would be nice, as it allows me to group multiple navbar links together, taking less space by default.

**Describe the solution you'd like**

```ts
const headerNavLinks = [
  { href: '/', title: 'Home' },
  { href: '/blog', title: 'Blog' },
  { href: '/tags', title: 'Tags' },
  { title: 'Dropdown 1', children: {
href: '/link1', title: 'title 1',
href: '/link2', title: 'title 2',
} // this becomes a dropdown navbar item
]
```

**Describe alternatives you've considered**

**Additional context**

**Comment by timlrx** [comment]
I don't mind supporting such a feature. To avoid creating too much clutter, I think just a one level menu would work and it should display well on mobile as well.

If anyone is interesting in contributing a pull request on this item, let me know, thanks!

**Comment by pratikkabade** [comment]
@timlrx 
I'd like to contribute, Would it be okay if I take on this one?

**Comment by timlrx** [comment]
****

> @timlrx I'd like to contribute, Would it be okay if I take on this one?

Sure! Take a look at the recently updated [ThemeSwitch](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/main/components/ThemeSwitch.tsx) component. It contains a menu implementation using `@headlessui/react`. Try to follow a similar approach for consistency, thanks!

**Comment by pratikkabade** [comment]
Exactly what I was planning on doing!
