### ISSUE TITLE
Tambouille is on!

### ISSUE THREAD

**Issue by aloisdg** [timlrx/tailwind-nextjs-starter-blog#87]
Hello,

A quick message to thanks timlrx and all contributors for the work done here. I used this template as a base for a cookbook aimed to my family: https://tambouille.vercel.app/

The code lives over there: https://github.com/aloisdg/tambouille

Have a nice day everyone

**Comment by timlrx** [comment]
Awesome, nice icon! Can I add it to the examples blog in the readme page?

**Comment by aloisdg** [comment]
Yes of course!
