### ISSUE TITLE
Fails to deploy to Github Pages

### ISSUE THREAD

**Issue by SK-Crow** [timlrx/tailwind-nextjs-starter-blog#871]
**Describe the bug**
After forking the repo, I am attempting to deploy to Github pages using the test-gh-pages-static branch.  When GH pages tries to build, it fails.  I am uncertain as to what I am doing incorrectly.  Initially I was trying to modify the MAIN branch on a fork following the steps provided in the documentation to enable static for Github pages, but I was unable to get any CSS to function, so I opted for a version with no changes to see if I just didn't follow the instructions correctly.  Any idea what I might be doing incorrectly?

I did also try the v2 branch which was mostly successful, but it only builds a single static page from what I can tell.

![image](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/1341176/781d6cf8-4627-47db-b015-9312b4c1a0bd)

Error from test-gh-pages-static error below:
![image](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/1341176/d8adf9a4-30e0-44fc-bdab-5009fadfaf44)
`/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv[10](https://github.com/SK-Crow/tailwind-nextjs-starter-blog/actions/runs/8238432433/job/22529368086#step:4:11)12_33d5ef --label 4b6470 --workdir /github/workspace --rm -e "INPUT_SOURCE" -e "INPUT_DESTINATION" -e "INPUT_FUTURE" -e "INPUT_BUILD_REVISION" -e "INPUT_VERBOSE" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/tailwind-nextjs-starter-blog/tailwind-nextjs-starter-blog":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.12
Configuration file: none
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
     Build Warning: Layout 'PostSimple' requested in data/blog/new-features-in-v1.mdx does not exist.
     Build Warning: Layout 'PostBanner' requested in data/blog/pictures-of-canada.mdx does not exist.
  Liquid Exception: Liquid syntax error (line 357): Variable '{{ searchDocumentsPath: 'search.json', defaultActions: [ { id: 'homepage', name: 'Homepage', keywords: '', shortcut: ['h', 'h'], section: 'Home', perform: () => router.push('/'), }' was not properly terminated with regexp: /\}\}/ in README.md
/usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:136:in `raise_missing_variable_terminator': Liquid syntax error (line 357): Variable '{{ (Liquid::SyntaxError)
        searchDocumentsPath: 'search.json',
        defaultActions: [
          {
            id: 'homepage',
            name: 'Homepage',
            keywords: '',
            shortcut: ['h', 'h'],
            section: 'Home',
            perform: () => router.push('/'),
          }' was not properly terminated with regexp: /\\}\\}/
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:128:in `create_variable'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:39:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/document.rb:10:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/document.rb:5:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:130:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:[11](https://github.com/SK-Crow/tailwind-nextjs-starter-blog/actions/runs/8238432433/job/22529368086#step:4:12)4:in `parse'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/liquid_renderer/file.rb:[12](https://github.com/SK-Crow/tailwind-nextjs-starter-blog/actions/runs/8238432433/job/22529368086#step:4:13):in `parse'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/renderer.rb:121:in `render_liquid'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/renderer.rb:79:in `render_document'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/renderer.rb:62:in `run'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:479:in `render_regenerated'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:472:in `block in render_pages'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:471:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:471:in `render_pages'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:192:in `render'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:71:in `process'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/local/bundle/gems/github-pages-231/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-231/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
Error:  Logging at level: debug GitHub Pages: github-pages v231 GitHub Pages: jekyll v3.9.5 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... Generating: JekyllOptionalFrontMatter::Generator finished in 0.000[14](https://github.com/SK-Crow/tailwind-nextjs-starter-blog/actions/runs/8238432433/job/22529368086#step:4:15)405 seconds. Generating: JekyllReadmeIndex::Generator finished in 0.002325936 seconds. Generating: Jekyll::Paginate::Pagination finished in 2.976e-06 seconds. GitHub Metadata: Generating for SK-Crow/tailwind-nextjs-starter-blog GitHub Metadata: Calling @client.pages("SK-Crow/tailwind-nextjs-starter-blog", {}) Generating: JekyllRelativeLinks::Generator finished in 0.290569[19](https://github.com/SK-Crow/tailwind-nextjs-starter-blog/actions/runs/8238432433/job/22529368086#step:4:20)8 seconds. Generating: JekyllDefaultLayout::Generator finished in 0.0001[22](https://github.com/SK-Crow/tailwind-nextjs-starter-blog/actions/runs/8238432433/job/22529368086#step:4:23)53 seconds. Generating: JekyllTitlesFromHeadings::Generator finished in 7.[23](https://github.com/SK-Crow/tailwind-nextjs-starter-blog/actions/runs/8238432433/job/22529368086#step:4:24)05e-05 seconds. Rendering: data/blog/code-sample.mdx Pre-Render Hooks: data/blog/code-sample.mdx Rendering Markup: data/blog/code-sample.mdx Rendering Layout: data/blog/code-sample.mdx Rendering: data/authors/default.mdx Pre-Render Hooks: data/authors/default.mdx Rendering Markup: data/authors/default.mdx Rendering Layout: data/authors/default.mdx Rendering: data/blog/deriving-ols-estimator.mdx Pre-Render Hooks: data/blog/deriving-ols-estimator.mdx Rendering Markup: data/blog/deriving-ols-estimator.mdx Rendering Layout: data/blog/deriving-ols-estimator.mdx Rendering: data/blog/github-markdown-guide.mdx Pre-Render Hooks: data/blog/github-markdown-guide.mdx Rendering Markup: data/blog/github-markdown-guide.mdx Rendering Layout: data/blog/github-markdown-guide.mdx Rendering: data/blog/guide-to-using-images-in-nextjs.mdx Pre-Render Hooks: data/blog/guide-to-using-images-in-nextjs.mdx Rendering Markup: data/blog/guide-to-using-images-in-nextjs.mdx Rendering Layout: data/blog/guide-to-using-images-in-nextjs.mdx Rendering: data/blog/nested-route/introducing-multi-part-posts-with-nested-routing.mdx Pre-Render Hooks: data/blog/nested-route/introducing-multi-part-posts-with-nested-routing.mdx Rendering Markup: data/blog/nested-route/introducing-multi-part-posts-with-nested-routing.mdx Rendering Layout: data/blog/nested-route/introducing-multi-part-posts-with-nested-routing.mdx Rendering: data/blog/introducing-tailwind-nextjs-starter-blog.mdx Pre-Render Hooks: data/blog/introducing-tailwind-nextjs-starter-blog.mdx Rendering Markup: data/blog/introducing-tailwind-nextjs-starter-blog.mdx Rendering Layout: data/blog/introducing-tailwind-nextjs-starter-blog.mdx Rendering: data/blog/my-fancy-title.mdx Pre-Render Hooks: data/blog/my-fancy-title.mdx Rendering Markup: data/blog/my-fancy-title.mdx Rendering Layout: data/blog/my-fancy-title.mdx Rendering: data/blog/new-features-in-v1.mdx Pre-Render Hooks: data/blog/new-features-in-v1.mdx Rendering Markup: data/blog/new-features-in-v1.mdx Rendering Layout: data/blog/new-features-in-v1.mdx Rendering: data/blog/pictures-of-canada.mdx Pre-Render Hooks: data/blog/pictures-of-canada.mdx Rendering Markup: data/blog/pictures-of-canada.mdx Rendering Layout: data/blog/pictures-of-canada.mdx Rendering: data/blog/release-of-tailwind-nextjs-starter-blog-v2.0.mdx Pre-Render Hooks: data/blog/release-of-tailwind-nextjs-starter-blog-v2.0.mdx Rendering Markup: data/blog/release-of-tailwind-nextjs-starter-blog-v2.0.mdx Rendering Layout: data/blog/release-of-tailwind-nextjs-starter-blog-v2.0.mdx Rendering: data/authors/sparrowhawk.mdx Pre-Render Hooks: data/authors/sparrowhawk.mdx Rendering Markup: data/authors/sparrowhawk.mdx Rendering Layout: data/authors/sparrowhawk.mdx Rendering: data/blog/the-time-machine.`

**To Reproduce**
Fork repo
Enable Github pages with test-gh-pages-static branch
Under actions, review error

**Expected behavior**
Expecting page to build successfully

**Screenshots**

**System Info (if dev / build issue):**
Fork with no changes

**Comment by jonas-kgomo** [comment]
I have this issue too, what is the current workaround?

**Comment by timlrx** [comment]
Try it with the latest version. The dependencies have been updated.
