### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by suyashcjoshi** [timlrx/tailwind-nextjs-starter-blog#873]
**Describe the bug**

**To Reproduce**

1. run 'npm install'
2. See error

**Expected behavior**
It should install dependencies and then should run npm start

** BUG**
sj~$ npm install
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: tailwind-nextjs-starter-blog@2.1.0
npm ERR! Found: next@14.1.0
npm ERR! node_modules/next
npm ERR!   next@"14.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^12 || ^13" from next-contentlayer@0.3.4
npm ERR! node_modules/next-contentlayer
npm ERR!   next-contentlayer@"0.3.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by Udaay** [comment]
Yes I have been facing the sam issue

**Comment by whitedark9** [comment]
I kinda made it work.
First, open `package.json` and delete `next-contentlayer`.
Then, install all packages with `npm install`.
Then, install `npm next@13` which will install `next@^13.5.6`.
Then, install `npm install next-contentlayer`.
Finally, use `npm run dev`. 
It works for me now. I still don't know what kind of error I will encounter in the future.

**Comment by suyashcjoshi** [comment]
> `npm install next-contentlayer`

thanks, that worked, closing this issue but they probably should fix the README for others.
