### ISSUE TITLE
deploy vercel go wrong

### ISSUE THREAD

**Issue by nicekate** [timlrx/tailwind-nextjs-starter-blog#878]
Yesterday, I successfully deployed the modified blog to vercel. Today, I modified it and cannot deploy it. After that, I directly clicked deploy on the author's template and found the following error (consistent with the error occurred in my modified version):

Previous build cache not available
--
00:01:23.570 | Cloning completed: 563.551ms
00:01:24.151 | Running "vercel build"
00:01:25.284 | Vercel CLI 33.6.1
00:01:26.354 | Installing dependencies...
00:01:28.107 | ➤ YN0000: ┌ Resolution step
00:01:28.842 | ➤ YN0002: │ @algolia/autocomplete-core@npm:1.9.3 doesn't provide @algolia/client-search (pbc410), requested by @algolia/autocomplete-shared
00:01:28.843 | ➤ YN0002: │ @algolia/autocomplete-core@npm:1.9.3 doesn't provide algoliasearch (p8ad5b), requested by @algolia/autocomplete-shared
00:01:28.843 | ➤ YN0002: │ @algolia/autocomplete-core@npm:1.9.3 doesn't provide search-insights (pfdb70), requested by @algolia/autocomplete-plugin-algolia-insights
00:01:28.843 | ➤ YN0002: │ @algolia/autocomplete-plugin-algolia-insights@npm:1.9.3 [e43f4] doesn't provide @algolia/client-search (pdf3b9), requested by @algolia/autocomplete-shared
00:01:28.844 | ➤ YN0002: │ @algolia/autocomplete-plugin-algolia-insights@npm:1.9.3 [e43f4] doesn't provide algoliasearch (p0f6bb), requested by @algolia/autocomplete-shared
00:01:28.844 | ➤ YN0002: │ @docsearch/react@npm:3.5.2 [3a011] doesn't provide @algolia/client-search (pc4bb2), requested by @algolia/autocomplete-preset-algolia
00:01:28.844 | ➤ YN0060: │ tailwind-nextjs-starter-blog@workspace:. provides next (p2b7de) with version 14.1.0, which doesn't satisfy what next-contentlayer requests
00:01:28.845 | ➤ YN0060: │ tailwind-nextjs-starter-blog@workspace:. provides react (p89967) with version 18.2.0, which doesn't satisfy what pliny and some of its descendants request
00:01:28.845 | ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
00:01:28.864 | ➤ YN0000: └ Completed in 0s 756ms
00:01:29.083 | ➤ YN0000: ┌ Fetch step
00:02:40.564 | ➤ YN0066: │ typescript@patch:typescript@npm%3A5.3.2#~builtin<compat/typescript>::version=5.3.2&hash=14eedb: Cannot apply hunk #2
00:02:40.622 | ➤ YN0013: │ 54 packages were already cached, 1089 had to be fetched
00:02:40.626 | ➤ YN0000: └ Completed in 1m 12s
00:02:40.766 | ➤ YN0000: ┌ Link step
00:02:54.095 | ➤ YN0007: │ esbuild@npm:0.18.11 must be built because it never has been before or the last one failed
00:02:54.096 | ➤ YN0007: │ esbuild@npm:0.18.20 must be built because it never has been before or the last one failed
00:02:54.097 | ➤ YN0007: │ protobufjs@npm:7.2.5 must be built because it never has been before or the last one failed
00:02:54.487 | ➤ YN0007: │ contentlayer@npm:0.3.4 must be built because it never has been before or the last one failed
00:02:55.793 | ➤ YN0000: └ Completed in 15s 71ms
00:02:55.894 | ➤ YN0000: Done with warnings in 1m 28s
00:02:56.124 | Detected Next.js version: 14.1.0
00:02:56.126 | Running "yarn run build"
00:02:56.855 | Unbound variable "PWD"
00:02:56.891 | Error: Command "yarn run build" exited with 1

hope someone can solve it ,thank you

**Comment by DzmitryUr** [comment]
I just removed `cross-env INIT_CWD=$PWD` from `build` command https://github.com/DzmitryUr/dev-web-blog/pull/4/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R8. That fixed the build for me

**Comment by nicekate** [comment]
> I just removed `cross-env INIT_CWD=$PWD` from `build` command https://github.com/DzmitryUr/dev-web-blog/pull/4/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R8. That fixed the build for me

Thank you very much. It has been successfully deployed.Thank you for the exquisite template.

**Comment by emmanuelh-dev** [comment]
This works fine, but, what is the difference, is necessary add the cross-env INIT_CWD=$PWD o is optional? I have this question because is the default

**Comment by DzmitryUr** [comment]
> This works fine, but, what is the difference, is necessary add the cross-env INIT_CWD=$PWD o is optional? I have this question because is the default

I do not know maybe to ensure that the environment variables are set correctly or some old settings or some other reason. I just removed this INIT_CWD because it caused errors during deployment.

**Comment by DKulan** [comment]
Had this issue as well. The only thing mentioned in the docs is this:

_**Please note, that if you are using Windows, you may need to run:**_

`set PWD="$(pwd)"`

**Comment by sgardn** [comment]
Same thing happened to me as well. Thanks for posting your fix - I'm slightly worried though that Vercel broke something on their end about how this is hosted without communicating it. It's not like I bumped versions of anything to cause the break. :/

**Comment by timlrx** [comment]
I updated a bunch of dependencies and deployed a new version of the site at #881. Did not run into any issue. Maybe you could try again? Or does this bug only occur on newly created deployments?

**Comment by emmanuelh-dev** [comment]
> I updated a bunch of dependencies and deployed a new version of the site at #881. Did not run into any issue. Maybe you could try again? Or does this bug only occur on newly created deployments?

Is a bug with newly deployments

**Comment by James-Clark12** [comment]
Hey, I just got this after downloading the repo and trying to deploy on vercel. What fixed it for me was just deleting yarn.lock and then doing yarn install. Hope that helps someone.
