### ISSUE TITLE
Tags not updated

### ISSUE THREAD

**Issue by zhengbi-yong** [timlrx/tailwind-nextjs-starter-blog#892]
**Describe the bug**
I wrote a blog with some new tags in it , but the tags page doesn't show the newly added tags.

Did I do something wrong? Or do I need to add the tags somewhere?

**Comment by timlrx** [comment]
Try exiting and restarting the dev server again. Contentlayer should write the tags to a `tag-data.json` file and it should be picked up by next.js to correctly populate the pages.
