### ISSUE TITLE
New Icons added request

### ISSUE THREAD

**Issue by heyjumanji** [timlrx/tailwind-nextjs-starter-blog#898]
Please add a new icon of X along with Twitter icon option in that case people will find their preferable one to use. Some people like new and some people like the old Twitter icon so add that soon. Also please add the icon of website! Where user can add their other websites links to the bio or footer.

Also have a question: can i host the site on cf ?

**Comment by PxlSyl** [comment]
> Please add a new icon of X along with Twitter icon option in that case people will find their preferable one to use. Some people like new and some people like the old Twitter icon so add that soon. Also please add the icon of website! Where user can add their other websites links to the bio or footer.
> 
> Also have a question: can i host the site on cf ?

Hi, just in case, I did it for the i18n version (choice between X or Blue bird icon) so it should be easy for @timlrx or for you to implement it and just copy/paste what I did. Maybe I'll do a PR for this, if I have some time!

**Comment by heyjumanji** [comment]
> > Please add a new icon of X along with Twitter icon option in that case people will find their preferable one to use. Some people like new and some people like the old Twitter icon so add that soon. Also please add the icon of website! Where user can add their other websites links to the bio or footer.
> > Also have a question: can i host the site on cf ?
> 
> Hi, just in case, I did it for the i18n version (choice between X or Blue bird icon) so it should be easy for @timlrx or for you to implement it and just copy/paste what I did. Maybe I'll do a PR for this, if I have some time!

Thankyou but i have copy the code of the social icon files both files and i show me error in the deployment in vervel.

**Comment by timlrx** [comment]
Yes, I can add an X logo, will do that tomorrow.
