### ISSUE TITLE
Add z-index to ThemeSwitch menu

### ISSUE THREAD

**Issue by PxlSyl** [timlrx/tailwind-nextjs-starter-blog#904]
Hi!

There's a small fix to do with the new ThemeSwitch menu, and with the PostBanner layout, see by yourself there :

https://tailwind-nextjs-starter-blog.vercel.app/blog/pictures-of-canada

Solution :

Add a z-index (z-50) to the menu, like this :

 <Menu.Items className="absolute right-0 z-50 mt-2 w-32 origin-top-right divide-y divide-gray-100 rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none dark:bg-gray-800">

**Comment by timlrx** [comment]
Yes, that's definitely a bug - do you mind contributing a PR :)
