### ISSUE TITLE
tag-data.json file not created

### ISSUE THREAD

**Issue by X-leaf7** [timlrx/tailwind-nextjs-starter-blog#919]
**Describe the bug**
I deleted tag-data.json file.
And when I install the package by yarn, and yarn dev, got following error in terminal and the tag-data.json file is not created
 ✓ Starting...
(node:14862) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ✓ Ready in 2.8s
Contentlayer config change detected. Updating type definitions and data...
successCallback /home/ubuntu/@Projects/one/tailwind-nextjs-starter-blog/.contentlayer
SuccessCallbackError: SyntaxError: Unexpected identifier 'assert'

**To Reproduce**

1. Delete tag-data.json file in App directory.
2. yarn in cmd to install package
3. yarn dev

**Expected behavior**

**System Info (if dev / build issue):**

- OS: ubuntu 24.04
- Node version 22.1.0
- Npm version 10.7.0

**Browser Info (if display / formatting issue):**

- Device Desktop
- Browser chrome

**Comment by timlrx** [comment]
Seems related to #930
