### ISSUE TITLE
[documentation]

### ISSUE THREAD

**Issue by kaestro** [timlrx/tailwind-nextjs-starter-blog#924]
**Describe the bug**
typescript branch deleted from v2 but introduction page in 2021 still directs towards it and is deprecated

**To Reproduce**

npx degit timlrx/tailwind-nextjs-starter-blog#typescript

**Expected behavior**
~~the tpescript part~~ and check it as deprecated. Also, will be better if leading comment saying v1 is no longer supported and direct to v2. README.md of this repo posted will be of perfect solution I think

**Screenshots**
![image](https://github.com/timlrx/tailwind-nextjs-starter-blog/assets/32026095/59276254-af42-4007-a28c-3310c621c7a5)

**Comment by timlrx** [comment]
Yes indeed, apologies for the misleading documentation
