### ISSUE TITLE
comment provider disqus 

### ISSUE THREAD

**Issue by rth1972** [timlrx/tailwind-nextjs-starter-blog#926]
really love the script. i'm new to nextjs. I"m trying to alter the script to my needs.

i have a question though.
I'm using disqus as my comment provider but i'm getting an error message.
"chunk-ZGZNY22A.js:19 
 Refused to load the script 'https://undefined.disqus.com/embed.js"

instead of undefind how can i get 'https://shortname.disqus.com/embed.js'.

any help is appreciated, 
thanks in advance,

Robin

ps thank you for the great script, i'm really learning a lot by looking at the code.

**Comment by rth1972** [comment]
I've figured it out.

in siteMetadata.js i added 
`disqusConfig: {
        shortname: 'shortname',
    },`

**Comment by rth1972** [comment]
> really love the script. i'm new to nextjs. I"m trying to alter the script to my needs.
> 
> i have a question though. I'm using disqus as my comment provider but i'm getting an error message. "chunk-ZGZNY22A.js:19 Refused to load the script 'https://undefined.disqus.com/embed.js"
> 
> instead of undefind how can i get 'https://shortname.disqus.com/embed.js'.
> 
> any help is appreciated, thanks in advance,
> 
> Robin
> 
> ps thank you for the great script, i'm really learning a lot by looking at the code.

**Comment by S1Mojojojo** [comment]
How did you get discus to work? I [tried](https://green-card-priority-date.com/) configuring the properties but it's still not working
