### ISSUE TITLE
Notes on deploying vercel in a Windows environment

### ISSUE THREAD

**Issue by Samdasoo1076** [timlrx/tailwind-nextjs-starter-blog#929]
**I think I need some notes when deploying vercel in a Windows environment.**
The README only describes localhost hosting. 

**I need to explain if I am developing hosted by Vercel.**
Ex. When committing to a repository just before deploying to vercel, use the command 'yarn prettier --write.'

**Comment by timlrx** [comment]
Happy to accept a PR to improve the readme or add a section to the FAQ that explains what else needs to be done.
