### ISSUE TITLE
Umami cloud won't track navigated pages

### ISSUE THREAD

**Issue by jachsu** [timlrx/tailwind-nextjs-starter-blog#953]
**Describe the bug**
I'm using umami cloud.
When I land on page A and then navigate to page B, only page views on page A is tracked, not page B. Page B is only tracked if I refresh it. 
Anyone experiencing the same issue?

**Comment by timlrx** [comment]
It should work, I am also using it

**Comment by jachsu** [comment]
That's odd. I'm still working on it. It turns out that upon navigation, no POST request is being sent, though it should be. This might be an issue specific to Umami Cloud. I'll keep debugging.

**Comment by heyjumanji** [comment]
> It should work, I am also using it

Hey im using the same but the website dont collect any data why also i have added index.js and umami.js file in components and replace us.umami.is on next file
