### ISSUE TITLE
Support for Self Hosted Plausible

### ISSUE THREAD

**Issue by EmilMoe** [timlrx/tailwind-nextjs-starter-blog#965]
**Is your feature request related to a problem? Please describe.**
I'm hosting my own Plausible server, I don't see how I can integrate that?

**Describe the solution you'd like**
An optional parameter with domain

**Describe alternatives you've considered**
I tried to update my config to this, but that didn't seem to work

```js
plausibleAnalytics: {
  plausibleDataDomain: '<domain in plausible>', // e.g. tailwind-nextjs-starter-blog.vercel.app
  plausibleSrc: 'https://<my domain>/js/script.js',
},
```

**Comment by colkito** [comment]
I think it depends on the [pliny](https://github.com/timlrx/pliny) module. 
Have you tried by setting the `dataApi` prop? https://github.com/timlrx/pliny/blob/b91eb82057989d428496cf8e94accf70564b175b/packages/pliny/src/analytics/Plausible.tsx#L4

**Comment by EmilMoe** [comment]
> I think it depends on the [pliny](https://github.com/timlrx/pliny) module. Have you tried by setting the `dataApi` prop? https://github.com/timlrx/pliny/blob/b91eb82057989d428496cf8e94accf70564b175b/packages/pliny/src/analytics/Plausible.tsx#L5 Its possible to proxy the domain: https://github.com/timlrx/pliny/blob/b91eb82057989d428496cf8e94accf70564b175b/packages/pliny/src/analytics/Plausible.tsx#L11

Thanks, it even seems to be this simple:

```javascript
plausibleAnalytics: {
  plausibleDataDomain: '<domain in plausible>', // e.g. tailwind-nextjs-starter-blog.vercel.app
  src: 'https://<my domain>/js/script.js',
},
```

**Comment by chienxx** [comment]
> > I think it depends on the [pliny](https://github.com/timlrx/pliny) module. Have you tried by setting the `dataApi` prop? https://github.com/timlrx/pliny/blob/b91eb82057989d428496cf8e94accf70564b175b/packages/pliny/src/analytics/Plausible.tsx#L5 Its possible to proxy the domain: https://github.com/timlrx/pliny/blob/b91eb82057989d428496cf8e94accf70564b175b/packages/pliny/src/analytics/Plausible.tsx#L11
> 
> Thanks, it even seems to be this simple:
> 
> plausibleAnalytics: {
>   plausibleDataDomain: '<domain in plausible>', // e.g. tailwind-nextjs-starter-blog.vercel.app
>   src: 'https://<my domain>/js/script.js',
> },

## Hello, how did you solve this problem? I used the latest code repository, with the following configuration:
`siteMetadata.js`:
`plausibleAnalytics: {
      plausibleDataDomain: 'my-domain.com',
      src: 'https://plausible.my-domain.com/js/script.js',
    }
`

`next.config.js`:
`
  default-src 'self';
  script-src 'self' 'unsafe-eval' 'unsafe-inline' giscus.app https://plausible.io;
  style-src 'self' 'unsafe-inline';
  img-src * blob: data:;
  media-src *.s3.amazonaws.com;
  connect-src *;
  font-src 'self';
  frame-src giscus.app
`

**Comment by chienxx** [comment]
> 我认为这取决于[pliny](https://github.com/timlrx/pliny)模块。 你试过设置`dataApi`prop 吗？https://github.com/timlrx/pliny/blob/b91eb82057989d428496cf8e94accf70564b175b/packages/pliny/src/analytics/Plausible.tsx#L5 可以代理域名：[https ://github.com/timlrx/pliny/blob/b91eb82057989d428496cf8e94accf70564b175b/packages/pliny/src/analytics/Plausible.tsx#L11](https://github.com/timlrx/pliny/blob/b91eb82057989d428496cf8e94accf70564b175b/packages/pliny/src/analytics/Plausible.tsx#L11)

I just started using Next.js, and I'm currently using the code from the main repository. I have set up plausibleAnalytics and made the following configurations.：
`siteMetadata.js：
plausibleAnalytics:
 { 
   plausibleDataDomain: 'my-domain.com', 
   src: 'https://plausible.my-domain.com/js/script.js', 
}`
But when I visit the blog website,i  can't able to view the calls for script as well as api/event in the Networks tab.
How can i solve it? Looking forward to your reply
