### ISSUE TITLE
Static deploy can't load site.webmanifest

### ISSUE THREAD

**Issue by daklod2k3** [timlrx/tailwind-nextjs-starter-blog#970]
**Describe the bug**
Can't load site.webmanifest when using static deploy. Vercel deploy is ok, but when using static build (Github Page in my case and this repo case) got wrong path like this image
![image](https://github.com/user-attachments/assets/608ade77-4399-40ac-9465-ab1f94e99274)

**Comment by abernier** [comment]
https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/972 should fix this

**Comment by abernier** [comment]
PR has been merged, can you pull and close the issue if solved?

**Comment by timlrx** [comment]
Looks solved, closing the issue
