### ISSUE TITLE
How to create the nested post with the next and previous button showing the post form that nested series

### ISSUE THREAD

**Issue by sidx8** [timlrx/tailwind-nextjs-starter-blog#98]
I couldn't understand how to change the sort by date with the sort by the post in the nested folder any help would awsome

**Comment by timlrx** [comment]
You could try filtering [allPosts](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/pages/blog/%5B...slug%5D.js#L22) to those from the same root path

**Comment by sidx8** [comment]
is there any example i cant link them to the next and prev button

**Comment by timlrx** [comment]
Closing as the issue is stale and a solution has already been proposed.
